INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anchorage', 61.21, -149.9, 'Anchorage Municipality', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethel', 60.7922222, -161.7558333, 'Bethel Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coffman Cove', 56.01, -132.82, 'Prince of Wales-Outer Ketchikan Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cordova', 60.54, -145.75, 'Valdez-Cordova Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Craig', 55.4763889, -133.1483333, 'Prince of Wales-Outer Ketchikan Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delta Junction', 64.03, -145.73, 'Southeast Fairbanks Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dillingham', 59.0397222, -158.4575, 'Dillingham Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairbanks', 64.83, -147.71, 'Fairbanks North Star Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haines', 59.23, -135.44, 'Haines Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homer', 59.64, -151.54, 'Kenai Peninsula Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Juneau', 58.3, -134.41, 'Juneau City and Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kaktovik', 70.1319444, -143.6238889, 'North Slope Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenai', 60.55, -151.25, 'Kenai Peninsula Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ketchikan', 55.34, -131.64, 'Ketchikan Gateway Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kodiak', 57.79, -152.4, 'Kodiak Island Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kotzebue', 66.8983333, -162.5966667, 'Northwest Arctic Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nome', 64.5, -165.4, 'Nome Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Pole', 64.75, -147.34, 'Fairbanks North Star Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pelican', 57.9608333, -136.2275, 'Skagway-Hoonah-Angoon Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Petersburg', 56.81, -132.95, 'Wrangell-Petersburg Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seldovia', 59.4380556, -151.7113889, 'Kenai Peninsula Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sitka', 57.05, -135.33, 'Sitka City and Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skagway', 59.45, -135.31, 'Skagway-Hoonah-Angoon Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Soldotna', 60.48, -151.05, 'Kenai Peninsula Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Unalaska', 53.8736111, -166.5366667, 'Aleutians West Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valdez', 61.13, -146.34, 'Valdez-Cordova Census Area', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wasilla', 61.58, -149.43, 'Matanuska-Susitna Borough', 'AK', 'Alaska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wrangell', 56.47, -132.37, 'Wrangell-Petersburg Census Area', 'AK', 'Alaska');
