INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dauphin Island', 30.25, -88.1, 'Mobile', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decatur', 34.6, -86.98, 'Morgan', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Demopolis', 32.51, -87.83, 'Marengo', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Robertsdale', 30.55, -87.71, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dothan', 31.22, -85.39, 'Houston', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Russellville', 34.5, -87.72, 'Franklin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saraland', 30.82, -88.07, 'Mobile', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elba', 31.41, -86.06, 'Coffee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sardis City', 34.17, -86.12, 'Etowah', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Satsuma', 30.85, -88.05, 'Mobile', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottsboro', 34.67, -86.03, 'Jackson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selma', 32.4, -87.02, 'Dallas', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sheffield', 34.76, -87.69, 'Colbert', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Enterprise', 31.31, -85.85, 'Coffee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shorter', 32.39, -85.91, 'Macon', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eufaula', 31.89, -85.14, 'Barbour', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairhope', 30.52, -87.9, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayette', 33.68, -87.83, 'Fayette', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 34.79, -87.67, 'Lauderdale', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summerdale', 30.48, -87.69, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Foley', 30.4, -87.68, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sylacauga', 33.17, -86.25, 'Talladega', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Deposit', 31.98, -86.57, 'Lowndes', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Payne', 34.44, -85.71, 'DeKalb', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Talladega', 33.43, -86.1, 'Talladega', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tallassee', 32.53, -85.89, 'Elmore', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fultondale', 33.6, -86.79, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gadsden', 34.01, -86, 'Etowah', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thomasville', 31.91, -87.73, 'Clarke', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gardendale', 33.66, -86.81, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 31.8, -85.96, 'Pike', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trussville', 33.61, -86.6, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tuscaloosa', 33.2, -87.56, 'Tuscaloosa', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tuskegee', 32.42, -85.69, 'Macon', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union Springs', 32.14, -85.71, 'Bullock', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Uniontown', 32.44, -87.51, 'Perry', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley', 32.81, -85.17, 'Chambers', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grant', 34.52, -86.25, 'Marshall', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vernon', 33.75, -88.1, 'Lamar', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vestavia Hills', 33.44, -86.78, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guin', 33.96, -87.91, 'Marion', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gulf Shores', 30.24, -87.7, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guntersville', 34.35, -86.29, 'Marshall', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamilton', 34.14, -87.98, 'Marion', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartselle', 34.44, -86.93, 'Morgan', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wetumpka', 32.54, -86.21, 'Elmore', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winfield', 33.92, -87.81, 'Marion', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Heflin', 33.64, -85.58, 'Cleburne', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Helena', 33.29, -86.84, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homewood', 33.47, -86.8, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoover', 33.4, -86.81, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hueytown', 33.45, -86.99, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntsville', 34.73, -86.58, 'Madison', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irondale', 33.53, -86.7, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 33.81, -85.76, 'Calhoun', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jasper', 33.83, -87.27, 'Walker', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leeds', 33.54, -86.54, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leesburg', 34.17, -85.76, 'Cherokee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln', 33.61, -86.11, 'Talladega', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lineville', 33.31, -85.75, 'Clay', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Livingston', 32.58, -88.18, 'Sumter', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abbeville', 31.57, -85.25, 'Henry', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Luverne', 31.71, -86.26, 'Crenshaw', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alabaster', 33.24, -86.81, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alexander City', 32.94, -85.95, 'Tallapoosa', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 34.69, -86.74, 'Madison', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andalusia', 31.3, -86.48, 'Covington', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 32.63, -87.31, 'Perry', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anniston', 33.65, -85.83, 'Calhoun', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arab', 34.31, -86.49, 'Marshall', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 33.27, -85.83, 'Clay', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Athens', 34.8, -86.97, 'Limestone', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millbrook', 32.47, -86.36, 'Elmore', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Attalla', 34.02, -86.08, 'Etowah', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 32.6, -85.48, 'Lee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mobile', 30.69, -88.04, 'Mobile', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroeville', 31.52, -87.32, 'Monroe', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montevallo', 33.1, -86.86, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montgomery', 32.36, -86.29, 'Montgomery', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baileyton', 34.26, -86.61, 'Cullman', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay Minette', 30.88, -87.77, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beatrice', 31.73, -87.2, 'Monroe', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Brook', 33.5, -86.75, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muscle Shoals', 34.74, -87.66, 'Colbert', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bessemer', 33.4, -86.95, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Birmingham', 33.52, -86.8, 'Jefferson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boaz', 34.2, -86.16, 'Marshall', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brantley', 31.58, -86.25, 'Crenshaw', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brewton', 31.1, -87.07, 'Escambia', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeport', 34.94, -85.71, 'Jackson', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northport', 33.22, -87.57, 'Tuscaloosa', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookwood', 33.25, -87.32, 'Tuscaloosa', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brundidge', 31.72, -85.81, 'Pike', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calera', 33.1, -86.75, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Opelika', 32.64, -85.37, 'Lee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orange Beach', 30.29, -87.57, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Bluff', 34.22, -85.6, 'Cherokee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 33.61, -85.83, 'Calhoun', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ozark', 31.45, -85.64, 'Dale', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centre', 34.15, -85.67, 'Cherokee', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pelham', 33.28, -86.8, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pell City', 33.58, -86.28, 'St. Clair', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Childersburg', 33.27, -86.35, 'Talladega', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Phenix City', 32.47, -85, 'Russell', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Citronelle', 31.09, -88.22, 'Mobile', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clanton', 32.83, -86.62, 'Chilton', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Piedmont', 33.92, -85.61, 'Calhoun', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collinsville', 34.26, -85.86, 'DeKalb', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbiana', 33.17, -86.6, 'Shelby', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prattville', 32.46, -86.45, 'Autauga', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Courtland', 34.66, -87.3, 'Lawrence', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rainbow City', 33.95, -86.04, 'Etowah', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crossville', 34.28, -85.99, 'DeKalb', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cullman', 34.17, -86.84, 'Cullman', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Daleville', 31.31, -85.71, 'Dale', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Daphne', 30.6, -87.9, 'Baldwin', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rehobeth', 31.12, -85.45, 'Houston', 'AL', 'Alabama');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tallassee', 32.53, -85.89, 'Tallapoosa', 'AL', 'Alabama');
