INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rogers', 36.33, -94.11, 'Benton', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayetteville', 36.06, -94.15, 'Washington', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Russellville', 35.27, -93.13, 'Pope', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Smith', 35.38, -94.39, 'Sebastian', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Searcy', 35.25, -91.73, 'White', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sherwood', 34.81, -92.22, 'Pulaski', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Siloam Springs', 36.18, -94.54, 'Benton', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Memphis', 35.14, -90.18, 'Crittenden', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hot Springs', 34.5, -93.05, 'Garland', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 34.86, -92.11, 'Pulaski', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jonesboro', 35.84, -90.7, 'Craighead', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arkadelphia', 34.12, -93.05, 'Clark', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lavaca', 35.33, -94.17, 'Sebastian', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Little Rock', 34.74, -92.28, 'Pulaski', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bentonville', 36.37, -94.2, 'Benton', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maumelle', 34.86, -92.4, 'Pulaski', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melbourne', 36.05, -91.9, 'Izard', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mena', 34.58, -94.23, 'Polk', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlisle', 34.78, -91.74, 'Lonoke', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nashville', 33.94, -93.84, 'Howard', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cherokee Village', 36.29, -91.51, 'Sharp', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Little Rock', 34.76, -92.26, 'Pulaski', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conway', 35.08, -92.44, 'Faulkner', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crossett', 33.12, -91.96, 'Ashley', 'AR', 'Arkansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eureka Springs', 36.4, -93.73, 'Carroll', 'AR', 'Arkansas');
