INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wickenburg', 33.96, -112.72, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willcox', 32.25, -109.83, 'Cochise', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williams', 35.24, -112.19, 'Coconino', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winslow', 35.02, -110.69, 'Navajo', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yuma', 32.72, -114.62, 'Yuma', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Apache Junction', 33.41, -111.54, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avondale', 33.43, -112.34, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benson', 31.96, -110.29, 'Cochise', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bisbee', 31.44, -109.92, 'Cochise', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buckeye', 33.37, -112.58, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bullhead City', 35.14, -114.56, 'Mohave', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camp Verde', 34.56, -111.85, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carefree', 33.82, -111.91, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Casa Grande', 32.87, -111.75, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cave Creek', 33.83, -111.95, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chandler', 33.3, -111.84, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chino Valley', 34.75, -112.45, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarkdale', 34.77, -112.05, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coolidge', 32.97, -111.51, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottonwood', 34.73, -112, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duncan', 32.72, -109.1, 'Greenlee', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagar', 34.11, -109.29, 'Apache', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Mirage', 33.61, -112.32, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eloy', 32.75, -111.55, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flagstaff', 35.19, -111.65, 'Coconino', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 33.03, -111.38, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fountain Hills', 33.61, -111.71, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gilbert', 33.35, -111.78, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 33.53, -112.18, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goodyear', 33.43, -112.35, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guadalupe', 33.37, -111.96, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holbrook', 34.9, -110.15, 'Navajo', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kearny', 33.05, -110.91, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingman', 35.18, -114.05, 'Mohave', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Havasu City', 34.48, -114.32, 'Mohave', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Litchfield Park', 33.49, -112.35, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marana', 32.43, -111.22, 'Pima', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maricopa', 33.05, -112.04, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mesa', 33.42, -111.82, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nogales', 31.34, -110.93, 'Santa Cruz', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oro Valley', 32.39, -110.96, 'Pima', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Page', 36.91, -111.45, 'Coconino', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paradise Valley', 33.53, -111.94, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parker', 34.15, -114.28, 'La Paz', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Payson', 34.23, -111.32, 'Gila', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peoria', 33.58, -112.23, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Phoenix', 33.44, -112.07, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinetop-Lakeside', 34.14, -109.96, 'Navajo', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prescott', 34.54, -112.46, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prescott Valley', 34.61, -112.31, 'Yavapai', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quartzsite', 33.66, -114.22, 'La Paz', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Queen Creek', 33.24, -111.63, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Safford', 32.83, -109.7, 'Graham', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sahuarita', 31.95, -110.95, 'Pima', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Johns', 34.5, -109.36, 'Apache', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottsdale', 33.5, -111.89, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sedona', 34.86, -111.76, 'Coconino', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Show Low', 34.25, -110.02, 'Navajo', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sierra Vista', 31.55, -110.3, 'Cochise', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snowflake', 34.51, -110.07, 'Navajo', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springerville', 34.13, -109.28, 'Apache', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Superior', 33.29, -111.09, 'Pinal', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Surprise', 33.63, -112.33, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tempe', 33.41, -111.9, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thatcher', 32.84, -109.75, 'Graham', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tolleson', 33.45, -112.25, 'Maricopa', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tombstone', 31.71, -110.06, 'Cochise', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tucson', 32.22, -110.92, 'Pima', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wellton', 32.67, -114.14, 'Yuma', 'AZ', 'Arizona');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Queen Creek', 33.24, -111.63, 'Pinal', 'AZ', 'Arizona');
