INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marina', 36.68, -121.8, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Martinez', 38.01, -122.13, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marysville', 39.14, -121.59, 'Yuba', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maywood', 33.98, -118.18, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McFarland', 35.67, -119.22, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mendota', 36.75, -120.38, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Menlo Park', 37.45, -122.18, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Adelanto', 34.58, -117.4, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Merced', 37.3, -120.48, 'Merced', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Agoura', 34.14, -118.73, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mill Valley', 37.9, -122.54, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alameda', 37.76, -122.24, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millbrae', 37.59, -122.38, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 37.88, -122.29, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milpitas', 37.42, -121.9, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alhambra', 34.09, -118.12, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mission Viejo', 33.6, -117.67, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aliso Viejo', 33.6, -117.74, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Modesto', 37.63, -120.99, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alturas', 41.48, -120.54, 'Modoc', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monrovia', 34.14, -117.99, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('American Canyon', 38.17, -122.26, 'Napa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montclair', 34.07, -117.68, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anaheim', 33.83, -117.91, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monte Sereno', 37.23, -121.99, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anderson', 40.44, -122.29, 'Shasta', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montebello', 34, -118.1, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Angels Camp', 38.06, -120.53, 'Calaveras', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monterey', 36.6, -121.89, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Antioch', 38, -121.8, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monterey Park', 34.06, -118.12, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Apple Valley', 34.5, -117.18, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moorpark', 34.28, -118.88, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcadia', 34.13, -118.03, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moraga', 37.83, -122.12, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcata', 40.86, -124.08, 'Humboldt', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moreno Valley', 33.93, -117.23, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arroyo Grande', 35.11, -120.59, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morgan Hill', 37.13, -121.65, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Artesia', 33.86, -118.08, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morro Bay', 35.36, -120.84, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Shasta', 41.3, -122.31, 'Siskiyou', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atascadero', 35.48, -120.67, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain View', 37.38, -122.08, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atherton', 37.46, -122.19, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Murrieta', 33.55, -117.21, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atwater', 37.34, -120.6, 'Merced', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Napa', 38.29, -122.28, 'Napa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 38.89, -121.07, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('National City', 32.67, -117.09, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avalon', 33.34, -118.32, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Needles', 34.84, -114.61, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Azusa', 34.13, -117.9, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newark', 37.52, -122.04, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bakersfield', 35.37, -119.01, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newman', 37.31, -121.02, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baldwin Park', 34.08, -117.96, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport Beach', 33.61, -117.92, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Banning', 33.92, -116.87, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norco', 33.93, -117.54, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barstow', 34.89, -117.02, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwalk', 33.9, -118.08, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaumont', 33.92, -116.97, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Novato', 38.1, -122.56, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bell', 33.97, -118.18, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakdale', 37.76, -120.84, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bell Gardens', 33.96, -118.15, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakland', 37.8, -122.27, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellflower', 33.88, -118.11, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakley', 37.99, -121.71, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belmont', 37.52, -122.27, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oceanside', 33.19, -117.37, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belvedere', 37.87, -122.46, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ojai', 34.44, -119.24, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benicia', 38.04, -122.15, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ontario', 34.06, -117.65, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berkeley', 37.87, -122.27, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orange', 33.78, -117.85, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beverly Hills', 34.07, -118.4, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Bear Lake', 34.24, -116.91, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orinda', 37.87, -122.17, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Biggs', 39.41, -121.71, 'Butte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oroville', 39.51, -121.55, 'Butte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxnard', 34.19, -119.17, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pacific Grove', 36.61, -121.91, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bradbury', 34.14, -117.97, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pacifica', 37.61, -122.48, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brawley', 32.97, -115.53, 'Imperial', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Desert', 33.72, -116.37, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brea', 33.91, -117.9, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Springs', 33.83, -116.54, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brentwood', 37.93, -121.69, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palmdale', 34.57, -118.11, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brisbane', 37.68, -122.39, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palo Alto', 37.44, -122.14, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buellton', 34.61, -120.19, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palos Verdes Estates', 33.8, -118.39, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paradise', 39.75, -121.62, 'Butte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burbank', 34.18, -118.3, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paramount', 33.88, -118.15, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlingame', 37.58, -122.36, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parlier', 36.61, -119.52, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calabasas', 34.15, -118.63, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pasadena', 34.14, -118.14, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calexico', 32.67, -115.49, 'Imperial', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paso Robles', 35.62, -120.69, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Patterson', 37.47, -121.12, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calimesa', 34, -117.06, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perris', 33.78, -117.22, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Petaluma', 38.23, -122.63, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calistoga', 38.57, -122.57, 'Napa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pico Rivera', 33.98, -118.09, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camarillo', 34.21, -119.03, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Campbell', 37.28, -121.94, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinole', 38, -122.29, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canyon Lake', 33.68, -117.27, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Capitola', 36.97, -121.95, 'Santa Cruz', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pismo Beach', 35.14, -120.64, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlsbad', 33.15, -117.35, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsburg', 38.02, -121.88, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carmel-by-the-Sea', 36.55, -121.92, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Placentia', 33.87, -117.87, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carpinteria', 34.39, -119.51, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Placerville', 38.72, -120.79, 'El Dorado', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carson', 33.83, -118.28, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Hill', 37.94, -122.06, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cathedral City', 33.77, -116.46, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasanton', 37.66, -121.87, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ceres', 37.59, -120.95, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cerritos', 33.85, -118.06, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chico', 39.72, -121.83, 'Butte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pomona', 34.05, -117.75, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chino', 34.01, -117.68, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Hueneme', 34.14, -119.19, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chino Hills', 33.89, -117.72, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Porterville', 36.06, -119.01, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chowchilla', 37.12, -120.26, 'Madera', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portola', 39.81, -120.46, 'Plumas', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chula Vista', 32.64, -117.08, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portola Valley', 37.38, -122.23, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Citrus Heights', 38.7, -121.28, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poway', 32.96, -117.03, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Claremont', 34.09, -117.71, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rancho Cordova', 38.58, -121.3, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clayton', 37.94, -121.93, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rancho Cucamonga', 34.1, -117.59, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearlake', 38.95, -122.62, 'Lake', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rancho Mirage', 33.73, -116.41, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cloverdale', 38.8, -123.01, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rancho Palos Verdes', 33.74, -118.38, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clovis', 36.82, -119.7, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rancho Santa Margarita', 33.64, -117.6, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coachella', 33.68, -116.17, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Bluff', 40.17, -122.23, 'Tehama', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coalinga', 36.13, -120.36, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redding', 40.58, -122.39, 'Shasta', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colfax', 39.1, -120.95, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redlands', 34.05, -117.18, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colma', 37.67, -122.45, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redondo Beach', 33.84, -118.38, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colton', 34.07, -117.31, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redwood City', 37.48, -122.23, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reedley', 36.59, -119.45, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Commerce', 34, -118.15, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rialto', 34.1, -117.37, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Compton', 33.89, -118.22, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 37.93, -122.34, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Concord', 37.97, -122.03, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgecrest', 35.62, -117.67, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corcoran', 36.09, -119.56, 'Kings', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corning', 39.92, -122.17, 'Tehama', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rio Vista', 38.15, -121.69, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corona', 33.87, -117.56, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ripon', 37.74, -121.12, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coronado', 32.68, -117.18, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverbank', 37.73, -120.93, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corte Madera', 37.92, -122.52, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverside', 33.95, -117.39, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Costa Mesa', 33.64, -117.91, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rocklin', 38.79, -121.23, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cotati', 38.32, -122.7, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rohnert Park', 38.33, -122.7, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covina', 34.09, -117.89, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolling Hills', 33.75, -118.35, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crescent City', 41.75, -124.2, 'Del Norte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolling Hills Estates', 33.78, -118.35, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cudahy', 33.96, -118.18, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Culver City', 34.02, -118.39, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseville', 38.75, -121.28, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cupertino', 37.32, -122.03, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cypress', 33.81, -118.03, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sacramento', 38.58, -121.49, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Daly City', 37.7, -122.46, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salinas', 36.67, -121.65, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dana Point', 33.46, -117.69, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Anselmo', 37.97, -122.56, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 37.82, -121.99, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Bernardino', 34.1, -117.28, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davis', 38.54, -121.74, 'Yolo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Bruno', 37.63, -122.41, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Del Mar', 32.95, -117.26, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Carlos', 37.5, -122.26, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Del Rey Oaks', 36.59, -121.83, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Clemente', 33.42, -117.61, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delano', 35.76, -119.24, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Diego', 32.71, -117.15, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Desert Hot Springs', 33.96, -116.5, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Dimas', 34.1, -117.8, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Diamond Bar', 34.02, -117.81, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Fernando', 34.28, -118.43, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dinuba', 36.54, -119.38, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Francisco', 37.77, -122.41, 'San Francisco', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dixon', 38.44, -121.82, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Gabriel', 34.09, -118.1, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Jacinto', 33.78, -116.95, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Joaquin', 36.6, -120.18, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Jose', 37.33, -121.89, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Downey', 33.94, -118.13, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duarte', 34.13, -117.97, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Juan Capistrano', 33.5, -117.66, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dublin', 37.7, -121.93, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Leandro', 37.72, -122.15, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunsmuir', 41.2, -122.27, 'Siskiyou', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Luis Obispo', 35.28, -120.65, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Palo Alto', 37.46, -122.14, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Marcos', 33.14, -117.16, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Cajon', 32.79, -116.96, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Marino', 34.12, -118.1, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Centro', 32.79, -115.56, 'Imperial', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Mateo', 37.56, -122.32, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Cerrito', 37.91, -122.31, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Pablo', 37.96, -122.34, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Monte', 34.06, -118.02, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Rafael', 37.97, -122.53, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Segundo', 33.91, -118.41, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Ramon', 37.77, -121.97, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk Grove', 38.4, -121.37, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sand City', 36.61, -121.84, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emeryville', 37.83, -122.28, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sanger', 36.7, -119.55, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Encinitas', 33.03, -117.29, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Ana', 33.74, -117.86, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Escalon', 37.79, -120.99, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Barbara', 34.42, -119.69, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Escondido', 33.11, -117.08, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Clara', 37.35, -121.95, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Clarita', 34.39, -118.54, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eureka', 40.8, -124.16, 'Humboldt', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Cruz', 36.97, -122.03, 'Santa Cruz', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Fe Springs', 33.94, -118.08, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfax', 37.98, -122.58, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Maria', 34.95, -120.43, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfield', 38.24, -122.03, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Monica', 34.01, -118.49, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Paula', 34.35, -119.05, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferndale', 40.57, -124.26, 'Humboldt', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Rosa', 38.44, -122.71, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fillmore', 34.39, -118.91, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santee', 32.83, -116.97, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Firebaugh', 36.85, -120.45, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saratoga', 37.26, -122.02, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Folsom', 38.67, -121.17, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sausalito', 37.85, -122.48, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fontana', 34.09, -117.43, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scotts Valley', 37.05, -122.01, 'Santa Cruz', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Bragg', 39.44, -123.8, 'Mendocino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seal Beach', 33.74, -118.1, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seaside', 36.61, -121.85, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fortuna', 40.59, -124.15, 'Humboldt', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sebastopol', 38.4, -122.82, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Foster City', 37.55, -122.27, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selma', 36.57, -119.61, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fountain Valley', 33.7, -117.95, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shafter', 35.5, -119.27, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fowler', 36.63, -119.67, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shasta Lake', 40.68, -122.37, 'Shasta', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fremont', 37.54, -121.98, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fresno', 36.74, -119.77, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Signal Hill', 33.8, -118.16, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fullerton', 33.87, -117.92, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Simi Valley', 34.26, -118.78, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Galt', 38.25, -121.29, 'Sacramento', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Solana Beach', 32.99, -117.27, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden Grove', 33.77, -117.94, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Soledad', 36.42, -121.32, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gardena', 33.88, -118.3, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Solvang', 34.59, -120.13, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gilroy', 37, -121.56, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sonoma', 38.29, -122.45, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 34.14, -118.25, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sonora', 37.98, -120.38, 'Tuolumne', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendora', 34.13, -117.86, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South El Monte', 34.05, -118.04, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goleta', 34.43, -119.82, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Gate', 33.95, -118.21, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gonzales', 36.5, -121.44, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Lake Tahoe', 38.93, -119.98, 'El Dorado', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Pasadena', 34.11, -118.15, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grass Valley', 39.21, -121.06, 'Nevada', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South San Francisco', 37.65, -122.4, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenfield', 36.32, -121.24, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Helena', 38.5, -122.47, 'Napa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gridley', 39.36, -121.69, 'Butte', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stanton', 33.8, -117.99, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grover Beach', 35.12, -120.62, 'San Luis Obispo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stockton', 37.95, -121.29, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guadalupe', 34.97, -120.57, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Suisun City', 38.23, -122.04, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gustine', 37.25, -120.99, 'Merced', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunnyvale', 37.36, -122.03, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Half Moon Bay', 37.46, -122.42, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Susanville', 40.41, -120.65, 'Lassen', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hanford', 36.32, -119.64, 'Kings', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sutter Creek', 38.39, -120.8, 'Amador', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawaiian Gardens', 33.83, -118.07, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taft', 35.14, -119.45, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawthorne', 33.91, -118.35, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tehachapi', 35.13, -118.44, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hayward', 37.66, -122.08, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Healdsburg', 38.61, -122.86, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Temecula', 33.49, -117.14, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hemet', 33.74, -116.97, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Temple City', 34.1, -118.05, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hercules', 38.01, -122.28, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thousand Oaks', 34.17, -118.83, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hermosa Beach', 33.86, -118.39, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tiburon', 37.87, -122.45, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hesperia', 34.42, -117.3, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Torrance', 33.83, -118.34, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hidden Hills', 34.16, -118.65, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tracy', 37.73, -121.42, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland', 34.12, -117.2, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillsborough', 37.57, -122.37, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Truckee', 39.32, -120.18, 'Nevada', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hollister', 36.85, -121.4, 'San Benito', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulare', 36.2, -119.34, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holtville', 32.81, -115.38, 'Imperial', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hughson', 37.59, -120.86, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Turlock', 37.49, -120.84, 'Stanislaus', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntington Beach', 33.66, -117.99, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tustin', 33.74, -117.82, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntington Park', 33.98, -118.22, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Twentynine Palms', 34.13, -116.05, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ukiah', 39.15, -123.2, 'Mendocino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Imperial', 32.84, -115.56, 'Imperial', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union City', 37.59, -122.08, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Imperial Beach', 32.58, -117.11, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Upland', 34.09, -117.64, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indian Wells', 33.71, -116.3, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vacaville', 38.35, -121.98, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indio', 33.72, -116.21, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vallejo', 38.1, -122.25, 'Solano', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Industry', 34.01, -117.95, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ventura', 34.27, -119.29, 'Ventura', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Inglewood', 33.96, -118.35, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vernon', 34, -118.23, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ione', 38.35, -120.93, 'Amador', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Victorville', 34.53, -117.29, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irvine', 33.66, -117.82, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Villa Park', 33.81, -117.81, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irwindale', 34.1, -117.93, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Visalia', 36.33, -119.29, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vista', 33.2, -117.24, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 38.34, -120.77, 'Amador', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walnut', 34.02, -117.86, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walnut Creek', 37.9, -122.06, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('King City', 36.21, -121.12, 'Monterey', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wasco', 35.59, -119.34, 'Kern', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsburg', 36.51, -119.55, 'Fresno', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Cañada Flintridge', 34.19, -118.18, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watsonville', 36.91, -121.75, 'Santa Cruz', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Habra', 33.93, -117.94, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weed', 41.42, -122.38, 'Siskiyou', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Habra Heights', 33.96, -117.95, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Covina', 34.06, -117.93, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Mesa', 32.76, -117.02, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Hollywood', 34.09, -118.36, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Mirada', 33.91, -118.01, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Sacramento', 38.58, -121.53, 'Yolo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Palma', 33.84, -118.04, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Puente', 34.02, -117.94, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westminster', 33.75, -118, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Quinta', 33.66, -116.31, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Verne', 34.1, -117.76, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lafayette', 37.88, -122.11, 'Contra Costa', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whittier', 33.97, -118.03, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laguna Beach', 33.54, -117.78, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laguna Hills', 33.61, -117.71, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laguna Niguel', 33.52, -117.7, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laguna Woods', 33.61, -117.72, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windsor', 38.54, -122.81, 'Sonoma', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Elsinore', 33.66, -117.32, 'Riverside', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winters', 38.52, -121.97, 'Yolo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Forest', 33.64, -117.68, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodlake', 36.41, -119.09, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodland', 38.67, -121.77, 'Yolo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakewood', 33.85, -118.13, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodside', 37.42, -122.25, 'San Mateo', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 34.69, -118.13, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yorba Linda', 33.88, -117.81, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Larkspur', 37.93, -122.53, 'Marin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lathrop', 37.82, -121.27, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawndale', 33.88, -118.35, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yuba City', 39.14, -121.61, 'Sutter', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lemon Grove', 32.74, -117.03, 'San Diego', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yucaipa', 34.03, -117.04, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lemoore', 36.3, -119.78, 'Kings', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yucca Valley', 34.11, -116.43, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln', 38.89, -121.29, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindsay', 36.2, -119.08, 'Tulare', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Livermore', 37.68, -121.76, 'Alameda', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lodi', 38.13, -121.27, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loma Linda', 34.04, -117.26, 'San Bernardino', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lomita', 33.79, -118.31, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lompoc', 34.63, -120.45, 'Santa Barbara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Beach', 33.76, -118.18, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loomis', 38.82, -121.19, 'Placer', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Alamitos', 33.8, -118.07, 'Orange', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Altos', 37.38, -122.11, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Altos Hills', 37.37, -122.13, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Angeles', 34.05, -118.24, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Angeles', 34.05, -118.24, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Banos', 37.05, -120.84, 'Merced', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Gatos', 37.22, -121.97, 'Santa Clara', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lynwood', 33.93, -118.21, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madera', 36.96, -120.06, 'Madera', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Malibu', 34, -118.81, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mammoth Lakes', 37.64, -118.97, 'Mono', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manhattan Beach', 33.88, -118.41, 'Los Angeles', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manteca', 37.79, -121.21, 'San Joaquin', 'CA', 'California');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinole', 38, -122.29, 'Marin', 'CA', 'California');
