INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Breckenridge', 39.48, -106.03, 'Summit', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brighton', 39.98, -104.82, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Broomfield', 39.92, -105.08, 'Broomfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brush', 40.25, -103.62, 'Morgan', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cañon City', 38.39, -105.21, 'Fremont', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carbondale', 39.4, -107.21, 'Garfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Castle Rock', 39.37, -104.85, 'Douglas', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedaredge', 38.9, -107.92, 'Delta', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centennial', 39.57, -104.87, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cherry Hills Village', 39.64, -104.95, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colorado Springs', 38.83, -104.82, 'El Paso', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Commerce City', 39.8, -104.93, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cortez', 37.34, -108.58, 'Montezuma', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Craig', 40.51, -107.54, 'Moffat', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crested Butte', 38.86, -106.98, 'Gunnison', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cripple Creek', 38.74, -105.17, 'Teller', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dacono', 40.08, -104.93, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deer Trail', 39.61, -104.04, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delta', 38.74, -108.06, 'Delta', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denver', 39.73, -104.98, 'Denver', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dillon', 39.63, -106.04, 'Summit', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durango', 37.27, -107.88, 'La Plata', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle', 39.65, -106.82, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eaton', 40.53, -104.71, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgewater', 39.75, -105.06, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Englewood', 39.64, -104.98, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Erie', 40.05, -105.04, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Estes Park', 40.37, -105.52, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evans', 40.37, -104.69, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairplay', 39.22, -106, 'Park', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Federal Heights', 39.85, -104.99, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Firestone', 40.11, -104.93, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Collins', 40.58, -105.08, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Lupton', 40.08, -104.81, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Morgan', 40.25, -103.79, 'Morgan', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fountain', 38.68, -104.7, 'El Paso', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frederick', 40.09, -104.93, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frisco', 39.57, -106.09, 'Summit', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fruita', 39.15, -108.72, 'Mesa', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Georgetown', 39.7, -105.69, 'Clear Creek', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 39.7, -104.93, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glenwood Springs', 39.55, -107.32, 'Garfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Golden', 39.75, -105.22, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Junction', 39.06, -108.55, 'Mesa', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greeley', 40.42, -104.7, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenwood Village', 39.61, -104.95, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gunnison', 38.54, -106.92, 'Gunnison', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gypsum', 39.64, -106.95, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hayden', 40.49, -107.25, 'Routt', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudson', 40.07, -104.64, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Idaho Springs', 39.74, -105.51, 'Clear Creek', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnstown', 40.33, -104.91, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Junta', 37.98, -103.54, 'Otero', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lafayette', 39.99, -105.08, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakewood', 39.7, -105.08, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lamar', 38.08, -102.62, 'Prowers', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Limon', 39.26, -103.69, 'Lincoln', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Littleton', 39.61, -105.01, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lone Tree', 39.53, -104.89, 'Douglas', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longmont', 40.16, -105.1, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Louisville', 39.97, -105.13, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loveland', 40.39, -105.07, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lyons', 40.22, -105.27, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manitou Springs', 38.85, -104.91, 'El Paso', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Meeker', 40.03, -107.91, 'Rio Blanco', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milliken', 40.32, -104.85, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minturn', 39.58, -106.43, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monte Vista', 37.57, -106.14, 'Rio Grande', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montrose', 38.47, -107.87, 'Montrose', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monument', 39.09, -104.87, 'El Paso', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrison', 39.65, -105.19, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Village', 37.93, -107.85, 'San Miguel', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nederland', 39.96, -105.51, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Castle', 39.57, -107.53, 'Garfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northglenn', 39.88, -104.98, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pagosa Springs', 37.26, -107, 'Archuleta', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palmer Lake', 39.12, -104.91, 'El Paso', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parker', 39.51, -104.76, 'Douglas', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Platteville', 40.21, -104.82, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poncha Springs', 38.51, -106.07, 'Chaffee', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pueblo', 38.25, -104.6, 'Pueblo', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rifle', 39.53, -107.78, 'Garfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sheridan', 39.64, -105.02, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silt', 39.54, -107.65, 'Garfield', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silverthorne', 39.63, -106.06, 'Summit', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silverton', 37.81, -107.66, 'San Juan', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snowmass Village', 39.21, -106.93, 'Pitkin', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Fork', 37.67, -106.63, 'Rio Grande', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Steamboat Springs', 40.48, -106.83, 'Routt', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sterling', 40.62, -103.2, 'Logan', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stratton', 39.3, -102.6, 'Kit Carson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Superior', 39.95, -105.16, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Telluride', 37.93, -107.81, 'San Miguel', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thornton', 39.86, -104.97, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Timnath', 40.52, -104.98, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trinidad', 37.16, -104.5, 'Las Animas', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vail', 39.64, -106.37, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alamosa', 37.46, -105.87, 'Alamosa', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arvada', 39.8, -105.08, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aspen', 39.19, -106.81, 'Pitkin', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wellington', 40.7, -105, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 39.72, -104.83, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westminster', 39.83, -105.03, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon', 39.63, -106.52, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wheat Ridge', 39.76, -105.07, 'Jefferson', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Basalt', 39.36, -107.03, 'Eagle', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bayfield', 37.22, -107.59, 'La Plata', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bennett', 39.75, -104.42, 'Adams', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windsor', 40.47, -104.9, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berthoud', 40.3, -105.08, 'Larimer', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winter Park', 39.89, -105.76, 'Grand', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodland Park', 38.99, -105.05, 'Teller', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black Hawk', 39.79, -105.49, 'Gilpin', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wray', 40.07, -102.22, 'Yuma', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blanca', 37.43, -105.51, 'Costilla', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boulder', 40.01, -105.27, 'Boulder', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Erie', 40.05, -105.04, 'Weld', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 39.72, -104.83, 'Arapahoe', 'CO', 'Colorado');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Basalt', 39.36, -107.03, 'Pitkin', 'CO', 'Colorado');
