INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeport', 41.16, -73.2, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bristol', 41.67, -72.94, 'Hartford', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danbury', 41.39, -73.45, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Derby', 41.32, -73.08, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Groton', 41.35, -72.07, 'New London', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 41.76, -72.68, 'Hartford', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Litchfield', 41.74, -73.18, 'Litchfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Meriden', 41.53, -72.8, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 41.56, -72.65, 'Middlesex', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milford', 41.22, -73.05, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Naugatuck', 41.48, -73.05, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Britain', 41.66, -72.77, 'Hartford', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Haven', 41.3, -72.92, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New London', 41.35, -72.09, 'New London', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newtown', 41.41, -73.3, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwalk', 41.11, -73.4, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwich', 41.52, -72.07, 'New London', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelton', 41.31, -73.09, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stamford', 41.05, -73.53, 'Fairfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stonington', 41.33, -71.9, 'New London', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Torrington', 41.8, -73.12, 'Litchfield', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterbury', 41.55, -73.05, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Haven', 41.27, -72.94, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ansonia', 41.34, -73.07, 'New Haven', 'CT', 'Connecticut');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 41.76, -72.68, 'Middlesex', 'CT', 'Connecticut');
