INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellefonte', 39.76, -75.5, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethany Beach', 38.53, -75.05, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeville', 38.74, -75.6, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheswold', 39.21, -75.58, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clayton', 39.29, -75.63, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delaware City', 39.57, -75.58, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dewey Beach', 38.69, -75.07, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dover', 39.15, -75.52, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elsmere', 39.73, -75.59, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fenwick Island', 38.46, -75.05, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Georgetown', 38.69, -75.38, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrington', 38.92, -75.57, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenton', 39.22, -75.66, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurel', 38.55, -75.57, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewes', 38.77, -75.13, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 39.44, -75.71, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milford', 38.91, -75.42, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millsboro', 38.59, -75.29, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milton', 38.77, -75.3, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Castle', 39.66, -75.56, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newark', 39.68, -75.74, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 39.71, -75.6, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean View', 38.54, -75.08, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Odessa', 39.45, -75.66, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rehoboth Beach', 38.72, -75.07, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seaford', 38.64, -75.61, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selbyville', 38.46, -75.22, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smyrna', 39.29, -75.6, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Bethany', 38.51, -75.05, 'Sussex', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Townsend', 39.39, -75.69, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Viola', 39.04, -75.57, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilmington', 39.74, -75.54, 'New Castle', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyoming', 39.11, -75.55, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milford', 38.91, -75.42, 'Kent', 'DE', 'Delaware');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smyrna', 39.29, -75.6, 'New Castle', 'DE', 'Delaware');
