INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belle Isle', 28.45, -81.35, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belleair', 27.93, -82.8, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belleair Beach', 27.92, -82.84, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakland Park', 26.17, -80.13, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belleair Bluffs', 27.92, -82.81, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocala', 29.18, -82.14, 'Marion', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean Ridge', 26.52, -80.04, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocoee', 28.56, -81.54, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Okeechobee', 27.24, -80.82, 'Okeechobee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oldsmar', 28.03, -82.66, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boca Raton', 26.35, -80.08, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bonita Springs', 26.33, -81.77, 'Lee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boynton Beach', 26.52, -80.06, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orlando', 28.53, -81.37, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bradenton', 27.49, -82.57, 'Manatee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ormond Beach', 29.28, -81.05, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oviedo', 28.66, -81.2, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palatka', 29.64, -81.63, 'Putnam', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Bay', 28.03, -80.58, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Beach', 26.7, -80.03, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooksville', 28.55, -82.38, 'Hernando', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Beach Gardens', 26.82, -80.13, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Beach Shores', 26.77, -80.03, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Coast', 29.58, -81.2, 'Flagler', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Callaway', 30.15, -85.56, 'Bay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palm Springs', 26.63, -80.09, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palmetto', 27.52, -82.57, 'Manatee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cape Canaveral', 28.4, -80.6, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cape Coral', 26.56, -81.94, 'Lee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Panama City', 30.15, -85.66, 'Bay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Panama City Beach', 30.17, -85.8, 'Bay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Casselberry', 28.67, -81.32, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkland', 26.31, -80.23, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pembroke Pines', 26, -80.22, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pensacola', 30.42, -87.21, 'Escambia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chipley', 30.78, -85.53, 'Washington', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cinco Bayou', 30.42, -86.6, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinecrest', 25.66, -80.3, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearwater', 27.96, -82.8, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinellas Park', 27.84, -82.69, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plant City', 28.01, -82.11, 'Hillsborough', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clewiston', 26.75, -80.93, 'Hendry', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plantation', 26.12, -80.23, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Polk City', 28.18, -81.82, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cocoa', 28.38, -80.74, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cocoa Beach', 28.32, -80.6, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pompano Beach', 26.23, -80.12, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coconut Creek', 26.25, -80.17, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ponce Inlet', 29.09, -80.93, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cooper City', 26.05, -80.27, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Orange', 29.13, -80.99, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coral Gables', 25.72, -80.26, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coral Springs', 26.27, -80.27, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Saint Lucie', 27.29, -80.35, 'St. Lucie', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Punta Gorda', 26.92, -82.04, 'Charlotte', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quincy', 30.58, -84.58, 'Gadsden', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crystal River', 28.9, -82.59, 'Citrus', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redington Beach', 27.8, -82.81, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dade City', 28.36, -82.19, 'Pasco', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redington Shores', 27.82, -82.82, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dania Beach', 26.05, -80.14, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riviera Beach', 26.77, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockledge', 28.35, -80.72, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davie', 26.06, -80.23, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Royal Palm Beach', 26.7, -80.23, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Daytona Beach', 29.21, -81.02, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Safety Harbor', 27.99, -82.69, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Daytona Beach Shores', 29.17, -80.98, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('DeBary', 28.88, -81.3, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deerfield Beach', 26.31, -80.09, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('De Land', 29.02, -81.3, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delray Beach', 26.46, -80.07, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deltona', 28.9, -81.26, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Destin', 30.39, -86.49, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sanford', 28.8, -81.27, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunedin', 28.01, -82.77, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sanibel', 26.44, -82.02, 'Lee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunnellon', 29.04, -82.46, 'Marion', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sarasota', 27.33, -82.53, 'Sarasota', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle Lake', 27.97, -81.75, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Satellite Beach', 28.17, -80.59, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sebastian', 27.81, -80.47, 'Indian River', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgewater', 28.98, -80.9, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgewood', 28.48, -81.37, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shalimar', 30.44, -86.57, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eustis', 28.85, -81.68, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sneads', 30.7, -84.92, 'Jackson', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Daytona', 29.16, -81, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Miami', 25.7, -80.29, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fernandina Beach', 30.66, -81.46, 'Nassau', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flagler Beach', 29.47, -81.12, 'Flagler', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Pasadena', 27.75, -82.73, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southwest Ranches', 26.05, -80.33, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florida City', 25.44, -80.47, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 30.15, -85.61, 'Bay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Lauderdale', 26.12, -80.14, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Meade', 27.75, -81.8, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stuart', 27.19, -80.25, 'Martin', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Myers', 26.64, -81.87, 'Lee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunny Isles Beach', 25.95, -80.12, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Myers Beach', 26.45, -81.94, 'Lee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunrise', 26.13, -80.11, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Pierce', 27.44, -80.32, 'St. Lucie', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Surfside', 25.87, -80.12, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Walton Beach', 30.4, -86.61, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tallahassee', 30.43, -84.28, 'Leon', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tamarac', 26.21, -80.24, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tampa', 27.94, -82.45, 'Hillsborough', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fruitland Park', 28.86, -81.9, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tarpon Springs', 28.14, -82.75, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gainesville', 29.65, -82.32, 'Alachua', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tavares', 28.8, -81.72, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Temple Terrace', 28.03, -82.38, 'Hillsborough', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tequesta', 26.96, -80.12, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Titusville', 28.61, -80.8, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Treasure Island', 27.76, -82.76, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valparaiso', 30.5, -86.5, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Venice', 27.09, -82.45, 'Sarasota', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green Cove Springs', 29.99, -81.67, 'Clay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenacres City', 26.62, -80.12, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vero Beach', 27.63, -80.39, 'Indian River', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gulf Breeze', 30.35, -87.16, 'Santa Rosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gulfport', 27.74, -82.7, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wellington', 26.65, -80.24, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haines City', 28.11, -81.61, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Melbourne', 28.07, -80.65, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hallandale Beach', 25.98, -80.14, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Palm Beach', 26.71, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weston', 26.1, -80.39, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hialeah', 25.85, -80.27, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hialeah Gardens', 25.86, -80.32, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('High Springs', 29.82, -82.59, 'Alachua', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland Beach', 26.39, -80.06, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilton Manors', 26.16, -80.13, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windermere', 28.49, -81.53, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winter Garden', 28.56, -81.58, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winter Haven', 28.02, -81.73, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winter Park', 28.59, -81.33, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holly Hill', 29.24, -81.03, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winter Springs', 28.69, -81.3, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hollywood', 26.01, -80.14, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holmes Beach', 27.49, -82.71, 'Manatee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homestead', 25.46, -80.47, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zephyrhills', 28.23, -82.18, 'Pasco', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hypoluxo', 26.56, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indialantic', 28.08, -80.56, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Islamorada', 24.92, -80.62, 'Monroe', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 30.33, -81.65, 'Duval', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville Beach', 30.29, -81.39, 'Duval', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Juno Beach', 26.87, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jupiter', 26.93, -80.09, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Key Biscayne', 25.69, -80.16, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Key Colony Beach', 24.72, -81.01, 'Monroe', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Key West', 24.55, -81.78, 'Monroe', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kissimmee', 28.29, -81.4, 'Osceola', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lady Lake', 28.91, -81.92, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Alfred', 28.09, -81.72, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Mary', 28.75, -81.31, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Park', 26.8, -80.06, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Placid', 27.29, -81.36, 'Highlands', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Wales', 27.9, -81.58, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Worth', 26.61, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeland', 28.03, -81.94, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lantana', 26.58, -80.05, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Largo', 27.9, -82.78, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lauderdale Lakes', 26.16, -80.2, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lauderhill', 26.14, -80.21, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leesburg', 28.81, -81.87, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lighthouse Point', 26.27, -80.08, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Live Oak', 30.29, -82.98, 'Suwannee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longboat Key', 27.41, -82.65, 'Manatee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longwood', 28.7, -81.33, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lynn Haven', 30.24, -85.64, 'Bay', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Macclenny', 30.28, -82.12, 'Baker', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madeira Beach', 27.79, -82.79, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maitland', 28.62, -81.36, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Malabar', 28, -80.56, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marathon', 24.71, -81.09, 'Monroe', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marco', 25.97, -81.72, 'Collier', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Margate', 26.24, -80.2, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mary Esther', 30.4, -86.66, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melbourne', 28.08, -80.6, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melbourne Beach', 28.06, -80.56, 'Brevard', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami', 25.77, -80.19, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami Beach', 25.79, -80.13, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami Gardens', 25.94, -80.24, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami Lakes', 25.9, -80.3, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami Shores', 25.86, -80.19, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami Springs', 25.82, -80.28, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alachua', 29.75, -82.42, 'Alachua', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midway', 30.49, -84.45, 'Gadsden', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milton', 30.63, -87.03, 'Santa Rosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altamonte Springs', 28.66, -81.36, 'Seminole', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minneola', 28.57, -81.74, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miramar', 25.98, -80.23, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anna Maria', 27.53, -82.73, 'Manatee', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Apopka', 28.68, -81.5, 'Orange', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcadia', 27.21, -81.85, 'DeSoto', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Dora', 28.8, -81.64, 'Lake', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Naples', 26.14, -81.79, 'Collier', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlantic Beach', 30.33, -81.39, 'Duval', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Neptune Beach', 30.31, -81.39, 'Duval', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlantis', 26.59, -80.1, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Port Richey', 28.24, -82.71, 'Pasco', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburndale', 28.06, -81.78, 'Polk', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Smyrna Beach', 29.02, -80.92, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aventura', 25.95, -80.13, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon Park', 27.59, -81.5, 'Highlands', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niceville', 30.51, -86.48, 'Okaloosa', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bal Harbour', 25.89, -80.12, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Bay Village', 25.84, -80.15, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Lauderdale', 26.21, -80.22, 'Broward', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Miami', 25.89, -80.18, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay Harbor Islands', 25.88, -80.13, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Miami Beach', 25.93, -80.16, 'Miami-Dade', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Palm Beach', 26.81, -80.08, 'Palm Beach', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Port', 27.04, -82.23, 'Sarasota', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Redington Beach', 27.81, -82.82, 'Pinellas', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flagler Beach', 29.47, -81.12, 'Volusia', 'FL', 'Florida');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longboat Key', 27.41, -82.65, 'Sarasota', 'FL', 'Florida');
