INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('College Park', 33.65, -84.44, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 32.46, -84.98, 'Muscogee', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 33.61, -83.86, 'Newton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Commerce', 34.2, -83.45, 'Jackson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conyers', 33.66, -84.01, 'Rockdale', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peachtree City', 33.39, -84.59, 'Fayette', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearson', 31.29, -82.85, 'Atkinson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 33.59, -83.86, 'Newton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pembroke', 32.13, -81.62, 'Bryan', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perry', 32.45, -83.73, 'Houston', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cumming', 34.2, -84.14, 'Forsyth', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pine Lake', 33.79, -84.2, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dacula', 33.98, -83.89, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dahlonega', 34.53, -83.98, 'Lumpkin', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pooler', 32.11, -81.24, 'Chatham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Wentworth', 32.14, -81.16, 'Chatham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Powder Springs', 33.85, -84.68, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dawsonville', 34.42, -84.11, 'Dawson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decatur', 33.77, -84.29, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Doraville', 33.89, -84.28, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Douglas', 31.5, -82.84, 'Coffee', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Douglasville', 33.75, -84.74, 'Douglas', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond Hill', 31.93, -81.3, 'Bryan', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dublin', 32.54, -82.9, 'Laurens', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rincon', 32.29, -81.23, 'Effingham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duluth', 34, -84.14, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ringgold', 34.91, -85.1, 'Catoosa', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverdale', 33.57, -84.41, 'Clayton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Point', 33.67, -84.43, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockmart', 34, -85.04, 'Polk', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rome', 34.25, -85.16, 'Floyd', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elberton', 34.11, -82.86, 'Elbert', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellaville', 32.23, -84.3, 'Schley', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roswell', 34.02, -84.36, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellijay', 34.69, -84.48, 'Gilmer', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rutledge', 33.62, -83.61, 'Morgan', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Marys', 30.73, -81.54, 'Camden', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Euharlee', 34.14, -84.93, 'Bartow', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandersville', 32.98, -82.81, 'Washington', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairburn', 33.56, -84.58, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayetteville', 33.44, -84.45, 'Fayette', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Savannah', 32.08, -81.09, 'Chatham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fitzgerald', 31.71, -83.25, 'Ben Hill', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Senoia', 33.3, -84.55, 'Coweta', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flowery Branch', 34.18, -83.92, 'Hall', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Park', 33.62, -84.36, 'Clayton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forsyth', 33.03, -83.93, 'Monroe', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Valley', 32.55, -83.88, 'Peach', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smyrna', 33.88, -84.51, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snellville', 33.85, -84.01, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gainesville', 34.29, -83.82, 'Hall', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 32.37, -81.31, 'Effingham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Statesboro', 32.44, -81.78, 'Bulloch', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stockbridge', 33.54, -84.23, 'Henry', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stone Mountain', 33.8, -84.17, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sugar Hill', 34.1, -84.03, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gray', 33, -83.53, 'Jones', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Suwanee', 34.05, -84.07, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swainsboro', 32.59, -82.33, 'Emanuel', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Griffin', 33.24, -84.26, 'Spalding', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sylvania', 32.75, -81.63, 'Screven', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hahira', 30.99, -83.37, 'Lowndes', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hampton', 33.38, -84.28, 'Henry', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hapeville', 33.66, -84.41, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Temple', 33.73, -85.03, 'Carroll', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawkinsville', 32.28, -83.47, 'Pulaski', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thomasville', 30.83, -83.97, 'Thomas', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tifton', 31.45, -83.5, 'Tift', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hinesville', 31.84, -81.59, 'Liberty', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Toccoa', 34.57, -83.33, 'Stephens', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holly Springs', 34.17, -84.5, 'Cherokee', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoschton', 34.09, -83.76, 'Jackson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tybee Island', 32, -80.84, 'Chatham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tyrone', 33.47, -84.59, 'Fayette', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union City', 33.58, -84.54, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valdosta', 30.83, -83.27, 'Lowndes', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 33.29, -83.96, 'Butts', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Acworth', 34.06, -84.67, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vidalia', 32.21, -82.41, 'Toombs', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vienna', 32.09, -83.79, 'Dooly', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Villa Rica', 33.73, -84.91, 'Carroll', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 31.57, -84.15, 'Dougherty', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jonesboro', 33.52, -84.35, 'Clayton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kennesaw', 34.02, -84.61, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alpharetta', 34.07, -84.29, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warner Robins', 32.62, -83.59, 'Houston', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsland', 30.79, -81.68, 'Camden', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Americus', 32.07, -84.23, 'Sumter', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Grange', 33.03, -85.03, 'Troup', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waycross', 31.21, -82.35, 'Ware', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waynesboro', 33.08, -82.01, 'Burke', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Point', 32.87, -85.18, 'Troup', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawrenceville', 33.95, -83.98, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Athens', 33.96, -83.37, 'Clarke', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlanta', 33.74, -84.38, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lilburn', 33.89, -84.14, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winder', 33.99, -83.72, 'Barrow', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 34.01, -83.82, 'Barrow', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winterville', 33.96, -83.27, 'Clarke', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Augusta', 33.47, -81.97, 'Richmond', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Austell', 33.81, -84.63, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Locust Grove', 33.34, -84.1, 'Henry', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loganville', 33.83, -83.9, 'Walton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodstock', 34.1, -84.51, 'Cherokee', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avondale Estates', 33.77, -84.26, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baconton', 31.37, -84.16, 'Mitchell', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lookout Mountain', 34.97, -85.35, 'Walker', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bainbridge', 30.9, -84.57, 'Decatur', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barnesville', 33.05, -84.15, 'Lamar', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lumpkin', 32.05, -84.79, 'Stewart', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baxley', 31.77, -82.34, 'Appling', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berkeley Lake', 33.98, -84.18, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Macon', 32.84, -83.63, 'Bibb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 33.59, -83.46, 'Morgan', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 32.85, -84.61, 'Meriwether', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marietta', 33.95, -84.54, 'Cobb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomingdale', 32.13, -81.29, 'Chatham', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boston', 30.79, -83.78, 'Thomas', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bowdon', 33.53, -85.25, 'Carroll', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Braselton', 34.1, -83.76, 'Jackson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Metter', 32.39, -82.06, 'Candler', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bremen', 33.72, -85.14, 'Haralson', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooks', 33.29, -84.45, 'Fayette', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milledgeville', 33.08, -83.23, 'Baldwin', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brunswick', 31.14, -81.49, 'Glynn', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buford', 34.12, -84, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 33.79, -83.71, 'Walton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Byromville', 32.2, -83.9, 'Dooly', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montezuma', 32.3, -84.02, 'Macon', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cairo', 30.87, -84.2, 'Grady', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calhoun', 34.5, -84.95, 'Gordon', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camilla', 31.23, -84.21, 'Mitchell', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrow', 33.58, -84.33, 'Clayton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moultrie', 31.17, -83.78, 'Colquitt', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 34.23, -84.49, 'Cherokee', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carrollton', 33.58, -85.07, 'Carroll', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Park', 34.08, -84.41, 'Fulton', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cartersville', 34.16, -84.79, 'Bartow', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chamblee', 33.89, -84.29, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newnan', 33.38, -84.79, 'Coweta', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norcross', 33.94, -84.21, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarkston', 33.8, -84.23, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Odum', 31.66, -82.02, 'Wayne', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Villa Rica', 33.73, -84.91, 'Douglas', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Point', 32.87, -85.18, 'Harris', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlanta', 33.74, -84.38, 'DeKalb', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loganville', 33.83, -83.9, 'Gwinnett', 'GA', 'Georgia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 32.85, -84.61, 'Talbot', 'GA', 'Georgia');
