INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Storm Lake', 42.64, -95.2, 'Buena Vista', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mitchellville', 41.66, -93.35, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bettendorf', 41.52, -90.51, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monona', 43.05, -91.38, 'Clayton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monticello', 42.23, -91.18, 'Jones', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morning Sun', 41.09, -91.25, 'Louisa', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granger', 41.76, -93.82, 'Dallas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tama', 41.96, -92.57, 'Tama', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bondurant', 41.7, -93.46, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boone', 42.05, -93.88, 'Boone', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Pleasant', 40.96, -91.55, 'Henry', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boyden', 43.19, -96, 'Sioux', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 41.92, -91.41, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muscatine', 41.42, -91.04, 'Muscatine', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grinnell', 41.74, -92.72, 'Poweshiek', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Griswold', 41.23, -95.13, 'Cass', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tipton', 41.76, -91.12, 'Cedar', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grundy Center', 42.36, -92.76, 'Grundy', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nevada', 42.02, -93.45, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Hampton', 43.05, -92.31, 'Chickasaw', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Treynor', 41.23, -95.61, 'Pottawattamie', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buffalo Center', 43.38, -93.94, 'Winnebago', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 40.8, -91.11, 'Des Moines', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Underwood', 41.38, -95.67, 'Pottawattamie', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University Heights', 41.65, -91.55, 'Johnson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calmar', 43.18, -91.86, 'Winneshiek', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harlan', 41.65, -95.32, 'Shelby', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newton', 41.69, -93.04, 'Jasper', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Urbandale', 41.62, -93.71, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartley', 43.17, -95.47, 'O''Brien', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlisle', 41.5, -93.49, 'Warren', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Liberty', 41.74, -91.59, 'Johnson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Van Meter', 41.53, -93.95, 'Dallas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carson', 41.23, -95.41, 'Pottawattamie', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carter Lake', 41.29, -95.91, 'Pottawattamie', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northwood', 43.44, -93.22, 'Worth', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawarden', 42.99, -96.48, 'Sioux', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwalk', 41.47, -93.67, 'Warren', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Falls', 42.52, -92.44, 'Black Hawk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Rapids', 42, -91.64, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Odebolt', 42.31, -95.25, 'Sac', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oelwein', 42.67, -91.91, 'Fayette', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wahpeton', 43.36, -95.17, 'Dickinson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Central City', 42.2, -91.52, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walcott', 41.58, -90.77, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chariton', 41.01, -93.3, 'Lucas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cherokee', 42.74, -95.55, 'Cherokee', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hubbard', 42.3, -93.3, 'Hardin', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterloo', 42.49, -92.34, 'Black Hawk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Humboldt', 42.72, -94.21, 'Humboldt', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oskaloosa', 41.29, -92.64, 'Mahaska', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waukee', 41.61, -93.88, 'Dallas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarence', 41.88, -91.05, 'Cedar', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huxley', 41.89, -93.6, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waverly', 42.72, -92.47, 'Bremer', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarksville', 42.78, -92.66, 'Butler', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 42.46, -91.88, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indianola', 41.35, -93.55, 'Warren', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clear Lake', 43.13, -93.37, 'Cerro Gordo', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ottumwa', 41.02, -92.41, 'Wapello', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Webster City', 42.46, -93.81, 'Hamilton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Iowa City', 41.66, -91.53, 'Johnson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Iowa Falls', 42.52, -93.25, 'Hardin', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford Junction', 41.98, -90.95, 'Jones', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clermont', 43, -91.65, 'Fayette', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clive', 41.6, -93.72, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Branch', 41.67, -91.34, 'Cedar', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Burlington', 40.82, -91.15, 'Des Moines', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jesup', 42.47, -92.06, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Des Moines', 41.57, -93.71, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnston', 41.67, -93.69, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkersburg', 42.57, -92.78, 'Butler', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Liberty', 41.57, -91.26, 'Muscatine', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Union', 42.96, -91.8, 'Fayette', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colo', 42.01, -93.31, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paullina', 42.97, -95.68, 'O''Brien', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westfield', 42.75, -96.6, 'Plymouth', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pella', 41.4, -92.91, 'Marion', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus Junction', 41.28, -91.36, 'Louisa', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conrad', 42.22, -92.87, 'Grundy', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whittemore', 43.06, -94.42, 'Kossuth', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coralville', 41.67, -91.58, 'Johnson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainfield', 42.84, -92.53, 'Bremer', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Hill', 41.58, -93.51, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williamsburg', 41.66, -92, 'Iowa', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windsor Heights', 41.59, -93.7, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Council Bluffs', 41.26, -95.86, 'Pottawattamie', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plymouth', 43.24, -93.12, 'Cerro Gordo', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pocahontas', 42.73, -94.66, 'Pocahontas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wiota', 41.4, -94.88, 'Cass', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cresco', 43.38, -92.11, 'Howard', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Knoxville', 41.32, -93.1, 'Marion', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Postville', 43.08, -91.56, 'Allamakee', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prairie City', 41.59, -93.23, 'Jasper', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Park', 43.45, -95.32, 'Dickinson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Primghar', 43.08, -95.62, 'O''Brien', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyoming', 42.05, -91, 'Jones', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake View', 42.31, -95.05, 'Sac', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zearing', 42.16, -93.29, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quasqueton', 42.39, -91.76, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 40.86, -91.31, 'Des Moines', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davenport', 41.52, -90.57, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decorah', 43.3, -91.78, 'Winneshiek', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawton', 42.47, -96.18, 'Woodbury', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Le Claire', 41.59, -90.34, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redfield', 41.58, -94.19, 'Dallas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reinbeck', 42.32, -92.59, 'Grundy', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denison', 42.01, -95.35, 'Crawford', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denver', 42.67, -92.33, 'Bremer', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Des Moines', 41.6, -93.6, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Donnellson', 40.64, -91.56, 'Lee', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Linn Grove', 42.89, -95.24, 'Buena Vista', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lisbon', 41.92, -91.38, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Robins', 42.07, -91.66, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Falls', 43.2, -93.08, 'Cerro Gordo', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dubuque', 42.5, -90.66, 'Dubuque', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Logan', 41.64, -95.78, 'Harrison', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockwell', 42.98, -93.19, 'Cerro Gordo', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunlap', 41.85, -95.6, 'Harrison', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Grove', 41.69, -90.58, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roland', 42.16, -93.5, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolfe', 42.81, -94.52, 'Pocahontas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lost Nation', 41.96, -90.81, 'Clinton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lowden', 41.85, -90.92, 'Cedar', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Adel', 41.61, -94.01, 'Dallas', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Afton', 41.02, -94.19, 'Union', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albert City', 42.78, -94.94, 'Buena Vista', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eldridge', 41.65, -90.58, 'Scott', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elgin', 42.95, -91.63, 'Fayette', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alexander', 42.8, -93.47, 'Franklin', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Algona', 43.06, -94.23, 'Kossuth', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maharishi Vedic City', 41.0525185, -91.9948961, 'Jefferson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 42.48, -91.45, 'Delaware', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manilla', 41.88, -95.23, 'Crawford', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altoona', 41.64, -93.46, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ely', 41.87, -91.58, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ames', 42.03, -93.61, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emmetsburg', 43.11, -94.68, 'Palo Alto', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maquoketa', 42.06, -90.66, 'Jackson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anita', 41.44, -94.76, 'Cass', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sergeant Bluff', 42.4, -96.35, 'Woodbury', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ankeny', 41.72, -93.6, 'Polk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evansdale', 42.46, -92.28, 'Black Hawk', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marengo', 41.79, -92.07, 'Iowa', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aplington', 42.58, -92.88, 'Butler', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 42.03, -91.59, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairbank', 42.63, -92.04, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshalltown', 42.04, -92.9, 'Marshall', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelby', 41.51, -95.45, 'Shelby', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfield', 41, -91.96, 'Jefferson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sheldon', 43.18, -95.85, 'O''Brien', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arnolds Park', 43.37, -95.12, 'Dickinson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mason City', 43.15, -93.2, 'Cerro Gordo', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shell Rock', 42.71, -92.58, 'Butler', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayette', 42.84, -91.8, 'Fayette', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atkins', 41.99, -91.86, 'Benton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McCallsburg', 42.16, -93.38, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sioux Center', 43.07, -96.17, 'Sioux', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 42.61, -91.72, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sioux City', 42.49, -96.4, 'Woodbury', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Dodge', 42.49, -94.16, 'Webster', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mechanicsville', 41.9, -91.25, 'Cedar', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Slater', 41.87, -93.67, 'Story', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Solon', 41.8, -91.49, 'Johnson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spencer', 43.14, -95.14, 'Clay', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baxter', 41.82, -93.15, 'Jasper', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miles', 42.04, -90.31, 'Jackson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milford', 43.32, -95.14, 'Dickinson', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springville', 42.05, -91.44, 'Linn', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stacyville', 43.43, -92.78, 'Mitchell', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stanhope', 42.28, -93.79, 'Hamilton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stanley', 42.64, -91.81, 'Buchanan', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belle Plaine', 41.89, -92.27, 'Benton', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belmond', 42.84, -93.61, 'Wright', 'IA', 'Iowa');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granger', 41.76, -93.82, 'Polk', 'IA', 'Iowa');
