INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moscow', 46.73, -117, 'Latah', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Home', 43.13, -115.69, 'Elmore', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nampa', 43.54, -116.56, 'Canyon', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Meadows', 44.97, -116.28, 'Adams', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Plymouth', 43.96, -116.81, 'Payette', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Payette', 44.07, -116.93, 'Payette', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Post Falls', 47.71, -116.95, 'Kootenai', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Priest River', 48.18, -116.9, 'Bonner', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rathdrum', 47.81, -116.89, 'Kootenai', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rexburg', 43.82, -111.78, 'Madison', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rigby', 43.67, -111.91, 'Jefferson', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rupert', 42.61, -113.67, 'Minidoka', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Anthony', 43.96, -111.68, 'Fremont', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salmon', 45.17, -113.89, 'Lemhi', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandpoint', 48.27, -116.55, 'Bonner', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelley', 43.38, -112.12, 'Bingham', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Soda Springs', 42.65, -111.6, 'Caribou', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Star', 43.69, -116.49, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sun Valley', 43.69, -114.35, 'Blaine', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Twin Falls', 42.56, -114.46, 'Twin Falls', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ammon', 43.46, -111.96, 'Bonneville', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashton', 44.07, -111.44, 'Fremont', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boise', 43.61, -116.2, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burley', 42.53, -113.79, 'Cassia', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caldwell', 43.66, -116.68, 'Canyon', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carey', 43.3, -113.94, 'Blaine', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coeur d''Alene', 47.67, -116.78, 'Kootenai', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dietrich', 42.9, -114.26, 'Lincoln', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Driggs', 43.72, -111.11, 'Teton', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle', 43.69, -116.35, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 42.01, -111.8, 'Franklin', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fruitland', 44, -116.91, 'Payette', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden City', 43.62, -116.23, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hailey', 43.51, -114.31, 'Blaine', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hauser', 47.77, -117.02, 'Kootenai', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hayden', 47.76, -116.78, 'Kootenai', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homedale', 43.61, -116.93, 'Owyhee', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Idaho Falls', 43.46, -112.03, 'Bonneville', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jerome', 42.72, -114.51, 'Jerome', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kellogg', 47.53, -116.11, 'Shoshone', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ketchum', 43.68, -114.36, 'Blaine', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kimberly', 42.53, -114.36, 'Twin Falls', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kuna', 43.49, -116.42, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewiston', 46.41, -117.01, 'Nez Perce', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McCall', 44.91, -116.09, 'Valley', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melba', 43.37, -116.52, 'Canyon', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Meridian', 43.61, -116.39, 'Ada', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middleton', 43.7, -116.62, 'Canyon', 'ID', 'Idaho');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montpelier', 42.32, -111.29, 'Bear Lake', 'ID', 'Idaho');
