INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belleville', 38.52, -89.98, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 39.73, -90.22, 'Morgan', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsfield', 39.6, -90.8, 'Pike', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Carbon', 38.74, -89.98, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Champaign', 40.11, -88.24, 'Champaign', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Ellyn', 41.87, -88.06, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glencoe', 42.13, -87.75, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Lenox', 41.51, -87.96, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainfield', 41.62, -88.2, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellwood', 41.88, -87.88, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale Heights', 41.91, -88.07, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Savanna', 42.09, -90.15, 'Carroll', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tower Lake', 42.23, -88.15, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glenview', 42.06, -87.78, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jerome', 39.76, -89.68, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belvidere', 42.26, -88.84, 'Boone', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Channahon', 41.42, -88.22, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glenwood', 41.54, -87.6, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plano', 41.66, -88.53, 'Kendall', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Savoy', 40.05, -88.25, 'Champaign', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zion', 42.44, -87.83, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charleston', 39.49, -88.17, 'Coles', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Alton', 38.88, -90.11, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnsburg', 42.38, -88.24, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 38.72, -89.88, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Schaumburg', 42.03, -88.08, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bensenville', 41.95, -87.94, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chatham', 39.67, -89.7, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Schiller Park', 41.95, -87.87, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Dundee', 42.09, -88.27, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Joliet', 41.52, -88.08, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berkeley', 41.88, -87.9, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Hazel Crest', 41.57, -87.64, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cherry Valley', 42.23, -88.94, 'Winnebago', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Moline', 41.5, -90.44, 'Rock Island', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marengo', 42.24, -88.6, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niles', 42.01, -87.8, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pontiac', 40.88, -88.62, 'Livingston', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berwyn', 41.85, -87.79, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Justice', 41.74, -87.83, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethalto', 38.9, -90.04, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Peoria', 40.66, -89.58, 'Tazewell', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 37.73, -88.93, 'Williamson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Urbana', 40.11, -88.2, 'Champaign', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chicago', 41.85, -87.65, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kankakee', 41.12, -87.86, 'Kankakee', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chicago Heights', 41.5, -87.63, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chicago Ridge', 41.7, -87.77, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Byron', 41.6, -90.33, 'Rock Island', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chillicothe', 40.92, -89.48, 'Peoria', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Normal', 40.51, -88.99, 'McLean', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edwardsville', 38.81, -89.95, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Effingham', 39.12, -88.54, 'Effingham', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshall', 39.39, -87.69, 'Clark', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Aurora', 41.8, -88.32, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Paso', 40.73, -89.01, 'Woodford', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Barrington', 42.2, -88.14, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Chicago', 42.32, -87.84, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grayslake', 42.34, -88.04, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elburn', 41.89, -88.47, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green Oaks', 42.29, -87.9, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarendon Hills', 41.79, -87.95, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomingdale', 41.95, -88.08, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elgin', 42.03, -88.28, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mascoutah', 38.49, -89.79, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Riverside', 41.84, -87.82, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomington', 40.48, -88.99, 'McLean', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northbrook', 42.12, -87.82, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Princeville', 40.92, -89.75, 'Peoria', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shiloh', 38.56, -89.89, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabeth', 42.31, -90.22, 'Jo Daviess', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vernon Hills', 42.21, -87.97, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blue Island', 41.65, -87.68, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prospect Heights', 42.09, -87.93, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk Grove Village', 42, -87.97, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northlake', 41.91, -87.89, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Matteson', 41.5, -87.71, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kildeer', 42.17, -88.04, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shorewood', 41.52, -88.2, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quincy', 39.93, -91.4, 'Adams', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Brook', 41.83, -87.92, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Forest', 41.6, -87.74, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Villa Grove', 39.86, -88.16, 'Douglas', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bolingbrook', 41.69, -88.06, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Villa Park', 41.88, -87.98, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coal City', 41.28, -88.28, 'Grundy', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Lawn', 41.71, -87.75, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maywood', 41.87, -87.84, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Park', 41.88, -87.78, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakbrook Terrace', 41.85, -87.96, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McHenry', 42.33, -88.26, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rantoul', 40.3, -88.15, 'Champaign', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elmhurst', 41.89, -87.94, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gurnee', 42.37, -87.9, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skokie', 42.03, -87.73, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bourbonnais', 41.14, -87.87, 'Kankakee', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sleepy Hollow', 42.09, -88.3, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elmwood Park', 41.92, -87.8, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Grange', 41.8, -87.86, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oblong', 39, -87.9, 'Crawford', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elsah', 38.95, -90.35, 'Jersey', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hainesville', 42.34, -88.06, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Grange Park', 41.83, -87.86, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wadsworth', 42.42, -87.92, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Addison', 41.93, -87.98, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collinsville', 38.67, -89.98, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('O''Fallon', 38.59, -89.91, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bradley', 41.14, -87.86, 'Kankakee', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melrose Park', 41.9, -87.85, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia', 38.44, -90.2, 'Monroe', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hampshire', 42.09, -88.53, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Breese', 38.61, -89.52, 'Clinton', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mendota', 41.54, -89.11, 'La Salle', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Algonquin', 42.16, -88.29, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Elgin', 41.99, -88.29, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hanover', 42.25, -90.27, 'Jo Daviess', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hanover Park', 41.99, -88.14, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Bluff', 42.27, -87.83, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 42.47, -88.3, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Forest', 42.25, -87.84, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richton Park', 41.48, -87.7, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake in the Hills', 42.18, -88.33, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Villa', 42.41, -88.07, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warrenville', 41.81, -88.17, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Zurich', 42.19, -88.09, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Metropolis', 37.15, -88.73, 'Massac', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookfield', 41.82, -87.85, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 40.7, -89.4, 'Tazewell', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cortland', 41.92, -88.68, 'DeKalb', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evanston', 42.04, -87.69, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evergreen Park', 41.72, -87.7, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altamont', 39.06, -88.74, 'Effingham', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterloo', 38.33, -90.14, 'Monroe', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alton', 38.89, -90.18, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 38.83, -90.09, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watseka', 40.77, -87.73, 'Iroquois', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harvard', 42.42, -88.61, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('River Forest', 41.89, -87.81, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wauconda', 42.25, -88.13, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harvey', 41.61, -87.64, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverside', 41.83, -87.82, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waukegan', 42.36, -87.84, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairview Heights', 38.58, -89.99, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harwood Heights', 41.96, -87.8, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverwoods', 42.16, -87.89, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawthorn Woods', 42.21, -88.04, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roanoke', 40.79, -89.19, 'Woodford', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Grove', 42.44, -88.23, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Antioch', 42.47, -88.09, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orland Hills', 41.58, -87.84, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orland Park', 41.63, -87.85, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Valley', 41.32, -89.19, 'Bureau', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester', 39.74, -89.53, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcola', 39.68, -88.3, 'Douglas', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 39.8, -89.64, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lemont', 41.67, -88, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minooka', 41.45, -88.26, 'Grundy', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lena', 42.37, -89.82, 'Stephenson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Chicago', 41.88, -88.2, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buffalo Grove', 42.15, -87.95, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crystal Lake', 42.24, -88.31, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Falls', 41.77, -89.68, 'Whiteside', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oswego', 41.68, -88.35, 'Kendall', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Island', 41.5, -90.57, 'Rock Island', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Dundee', 42.09, -88.28, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arlington Heights', 42.08, -87.98, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mokena', 41.52, -87.88, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moline', 41.5, -90.51, 'Rock Island', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockdale', 41.5, -88.11, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockford', 42.27, -89.09, 'Winnebago', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sterling', 41.78, -89.69, 'Whiteside', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockton', 42.45, -89.07, 'Winnebago', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monmouth', 40.91, -90.64, 'Warren', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland', 38.73, -89.67, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palatine', 42.11, -88.03, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westchester', 41.85, -87.88, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland Park', 42.18, -87.8, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stickney', 41.82, -87.78, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Libertyville', 42.28, -87.95, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolling Meadows', 42.08, -88.01, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montgomery', 41.73, -88.34, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burr Ridge', 41.74, -87.91, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Romeoville', 41.64, -88.08, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monticello', 40.02, -88.57, 'Piatt', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palos Heights', 41.66, -87.79, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westmont', 41.79, -87.97, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flossmoor', 41.54, -87.68, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillside', 41.87, -87.9, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palos Hills', 41.69, -87.81, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palos Park', 41.66, -87.83, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 40.12, -87.63, 'Vermilion', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Darien', 41.75, -87.97, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hinsdale', 41.8, -87.93, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincolnshire', 42.19, -87.9, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincolnwood', 42, -87.73, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wheaton', 41.86, -88.1, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Park', 41.87, -87.81, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindenhurst', 42.41, -88.02, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wheeling', 42.13, -87.92, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrison', 41.8, -89.96, 'Whiteside', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoffman Estates', 42.04, -88.07, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roselle', 41.98, -88.07, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morton', 40.61, -89.45, 'Tazewell', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Streamwood', 42.02, -88.17, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lisle', 41.8, -88.07, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morton Grove', 42.04, -87.78, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paris', 39.61, -87.69, 'Edgar', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forsyth', 39.93, -88.95, 'Macon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Litchfield', 39.17, -89.65, 'Montgomery', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 39.59, -89.74, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park Forest', 41.49, -87.67, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decatur', 39.84, -88.95, 'Macon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homer Glen', 41.6, -87.93, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park Ridge', 42.01, -87.84, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homewood', 41.55, -87.66, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sugar Grove', 41.76, -88.44, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake', 42.35, -88.09, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 41.76, -88.32, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fox Lake', 42.39, -88.18, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake Beach', 42.37, -88.09, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deer Park', 42.16, -88.08, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fox River Grove', 42.2, -88.21, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake Heights', 42.38, -88.1, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake Park', 42.35, -88.07, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deerfield', 42.17, -87.84, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frankfort', 41.49, -87.84, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lockport', 41.58, -88.05, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('DeKalb', 41.92, -88.75, 'DeKalb', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Freeburg', 38.42, -89.91, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Prospect', 42.06, -87.93, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willowbrook', 41.76, -87.93, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilmette', 42.07, -87.72, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lombard', 41.88, -88, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swansea', 38.53, -89.98, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Freeport', 42.29, -89.62, 'Stephenson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 38.31, -88.9, 'Jefferson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Des Plaines', 42.03, -87.88, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Zion', 39.77, -88.87, 'Macon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pekin', 40.56, -89.64, 'Tazewell', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fulton', 41.86, -90.15, 'Whiteside', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carbondale', 37.72, -89.21, 'Jackson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Grove', 42.17, -87.99, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winfield', 41.86, -88.16, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntley', 42.16, -88.42, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlyle', 38.61, -89.37, 'Clinton', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Galena', 42.41, -90.42, 'Jo Daviess', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winnetka', 42.1, -87.73, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Galesburg', 40.94, -90.37, 'Knox', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peoria', 40.69, -89.58, 'Peoria', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barrington', 42.15, -88.13, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mundelein', 42.26, -88, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peotone', 41.33, -87.78, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Charles', 41.91, -88.3, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winthrop Harbor', 42.47, -87.82, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barrington Hills', 42.14, -88.15, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carol Stream', 41.91, -88.13, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Murphysboro', 37.76, -89.33, 'Jackson', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylorville', 39.54, -89.29, 'Christian', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carpentersville', 42.12, -88.25, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dolton', 41.63, -87.6, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wood River', 38.86, -90.09, 'Madison', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bartlett', 41.99, -88.18, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Naperville', 41.78, -88.14, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pesotum', 39.91, -88.27, 'Champaign', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Batavia', 41.85, -88.31, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodridge', 41.74, -88.05, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Geneva', 41.88, -88.3, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cary', 42.21, -88.23, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beach Park', 42.42, -87.85, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodstock', 42.31, -88.44, 'McHenry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salem', 38.62, -88.94, 'Marion', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Downers Grove', 41.8, -88.01, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Worth', 41.68, -87.79, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Germantown Hills', 40.76, -89.46, 'Woodford', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tinley Park', 41.57, -87.78, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Machesney Park', 42.34, -89.03, 'Winnebago', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gilberts', 42.1, -88.37, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Macomb', 40.45, -90.67, 'McDonough', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beecher', 41.34, -87.62, 'Will', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Berlin', 39.72, -89.91, 'Sangamon', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandwich', 41.64, -88.62, 'DeKalb', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centralia', 38.52, -89.13, 'Marion', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Itasca', 41.97, -88, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinckneyville', 38.08, -89.38, 'Perry', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berkeley', 41.88, -87.9, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elgin', 42.03, -88.28, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collinsville', 38.67, -89.98, 'St. Clair', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roselle', 41.98, -88.07, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 41.76, -88.32, 'DuPage', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barrington', 42.15, -88.13, 'Lake', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barrington Hills', 42.14, -88.15, 'Kane', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carpentersville', 42.12, -88.25, 'Cook', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 41.76, -88.32, 'Kendall', 'IL', 'Illinois');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 41.76, -88.32, 'Will', 'IL', 'Illinois');
