INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clear Lake', 41.73, -84.83, 'Steuben', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Lafayette', 40.42, -86.9, 'Tippecanoe', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Bend', 41.68, -86.25, 'St. Joseph', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hammond', 41.58, -87.5, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westfield', 40.04, -86.12, 'Hamilton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orleans', 38.66, -86.45, 'Orange', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Speedway', 39.8, -86.26, 'Marion', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westville', 41.54, -86.9, 'LaPorte', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whiteland', 39.55, -86.07, 'Johnson', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia City', 41.15, -85.48, 'Whitley', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whiting', 41.67, -87.49, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 39.2, -85.92, 'Bartholomew', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Connersville', 39.64, -85.14, 'Fayette', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anderson', 40.1, -85.68, 'Madison', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winona Lake', 41.22, -85.82, 'Kosciusko', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pendleton', 39.99, -85.74, 'Madison', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Angola', 41.63, -84.99, 'Steuben', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford City', 40.45, -85.36, 'Blackford', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lowell', 41.29, -87.42, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crown Point', 41.41, -87.36, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cumberland', 39.77, -85.95, 'Marion', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 41.36, -85.05, 'DeKalb', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon', 39.76, -86.39, 'Hendricks', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Syracuse', 41.42, -85.75, 'Kosciusko', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 39.76, -86.52, 'Hendricks', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peru', 40.75, -86.06, 'Miami', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Petersburg', 38.49, -87.27, 'Pike', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Terre Haute', 39.46, -87.41, 'Vigo', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bedford', 38.86, -86.48, 'Lawrence', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delphi', 40.58, -86.67, 'Carroll', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Topeka', 41.53, -85.53, 'LaGrange', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudson', 41.53, -85.08, 'Steuben', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trail Creek', 41.69, -86.85, 'LaPorte', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainfield', 39.7, -86.39, 'Hendricks', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntingburg', 38.29, -86.95, 'Dubois', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntington', 40.88, -85.49, 'Huntington', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dune Acres', 41.64, -87.08, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indianapolis', 39.76, -86.15, 'Marion', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dyer', 41.49, -87.52, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomington', 39.16, -86.52, 'Monroe', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Chicago', 41.63, -87.45, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McCordsville', 39.9, -85.92, 'Hancock', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portage', 41.57, -87.17, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bluffton', 40.73, -85.17, 'Wells', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Porter', 41.61, -87.07, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Meridian Hills', 39.89, -86.15, 'Marion', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Merrillville', 41.48, -87.33, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Michiana Shores', 41.75, -86.81, 'LaPorte', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Michigan City', 41.7, -86.89, 'LaPorte', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkhart', 41.68, -85.97, 'Elkhart', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellettsville', 39.23, -86.62, 'Monroe', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middlebury', 41.67, -85.7, 'Elkhart', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elwood', 40.27, -85.84, 'Madison', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brazil', 39.52, -87.12, 'Clay', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Princeton', 38.35, -87.56, 'Gibson', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evansville', 37.97, -87.55, 'Vanderburgh', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valparaiso', 41.47, -87.06, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mishawaka', 41.66, -86.15, 'St. Joseph', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brownsburg', 39.84, -86.39, 'Hendricks', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jasper', 38.39, -86.93, 'Dubois', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fishers', 39.95, -86.01, 'Hamilton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flora', 40.54, -86.52, 'Carroll', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burns Harbor', 41.62, -87.13, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Butler', 41.42, -84.87, 'DeKalb', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Wayne', 41.13, -85.12, 'Allen', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 39.82, -84.89, 'Wayne', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fowler', 40.61, -87.32, 'Benton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vincennes', 38.67, -87.52, 'Knox', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wabash', 40.79, -85.82, 'Wabash', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frankfort', 40.27, -86.51, 'Clinton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 39.48, -86.05, 'Johnson', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester', 41.06, -86.21, 'Fulton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walkerton', 41.46, -86.48, 'St. Joseph', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carmel', 39.97, -86.11, 'Hamilton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morocco', 40.94, -87.45, 'Newton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warsaw', 41.23, -85.85, 'Kosciusko', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 38.65, -87.17, 'Daviess', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muncie', 40.19, -85.38, 'Delaware', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rushville', 39.6, -85.44, 'Rush', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Munster', 41.56, -87.51, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nashville', 39.2, -86.25, 'Brown', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garrett', 41.34, -85.13, 'DeKalb', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gary', 41.59, -87.34, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Albany', 38.28, -85.82, 'Floyd', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint John', 41.45, -87.47, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Haven', 41.07, -85.01, 'Allen', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goshen', 41.58, -85.83, 'Elkhart', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Knox', 41.29, -86.62, 'Starke', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newburgh', 37.94, -87.4, 'Warrick', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kokomo', 40.48, -86.13, 'Howard', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Schererville', 41.47, -87.45, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lafayette', 40.41, -86.87, 'Tippecanoe', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesterton', 41.61, -87.06, 'Porter', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Churubusco', 41.23, -85.31, 'Whitley', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Noblesville', 40.04, -86, 'Hamilton', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Station', 41.57, -87.23, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seymour', 38.95, -85.89, 'Jackson', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Manchester', 41, -85.76, 'Wabash', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarksville', 38.29, -85.75, 'Clark', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenfield', 39.78, -85.76, 'Hancock', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('LaPorte', 41.61, -86.72, 'LaPorte', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelbyville', 39.52, -85.77, 'Shelby', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shipshewana', 41.67, -85.58, 'LaGrange', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawrence', 39.83, -86.02, 'Marion', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenwood', 39.61, -86.1, 'Johnson', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Griffith', 41.52, -87.42, 'Lake', 'IN', 'Indiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 40.04, -86.46, 'Boone', 'IN', 'Indiana');
