INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Halstead', 38, -97.5, 'Harvey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newton', 38.04, -97.34, 'Harvey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 38.19, -95.74, 'Coffey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edwardsville', 39.06, -94.81, 'Wyandotte', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Dorado', 37.81, -96.86, 'Butler', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roeland Park', 39.03, -94.63, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rose Hill', 37.55, -97.13, 'Butler', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkhart', 37, -101.89, 'Morton', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellis', 38.93, -99.56, 'Ellis', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Newton', 38.07, -97.34, 'Harvey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindsborg', 38.57, -97.67, 'McPherson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ulysses', 37.58, -101.35, 'Grant', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Russell', 38.89, -98.85, 'Russell', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sabetha', 39.9, -95.8, 'Nemaha', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hays', 38.87, -99.32, 'Ellis', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emporia', 38.4, -96.18, 'Lyon', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haysville', 37.56, -97.35, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint John', 38, -98.76, 'Stafford', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hesston', 38.13, -97.43, 'Harvey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley Center', 37.83, -97.37, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salina', 38.84, -97.61, 'Saline', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olathe', 38.88, -94.81, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abilene', 38.91, -97.21, 'Dickinson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Osage City', 38.63, -95.82, 'Osage', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holton', 39.46, -95.73, 'Jackson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sedgwick', 37.91, -97.42, 'Harvey', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chanute', 37.67, -95.45, 'Neosho', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Horton', 39.66, -95.52, 'Brown', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairway', 39.02, -94.63, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ottawa', 38.61, -95.26, 'Franklin', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hugoton', 37.17, -101.34, 'Stevens', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Overland Park', 38.98, -94.67, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shawnee', 39.04, -94.72, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hutchinson', 38.06, -97.92, 'Reno', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andover', 37.71, -97.13, 'Butler', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maize', 37.77, -97.46, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 38.24, -96.92, 'Marion', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manhattan', 39.18, -96.57, 'Riley', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arkansas City', 37.06, -97.03, 'Cowley', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paola', 38.57, -94.87, 'Miami', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arma', 37.54, -94.7, 'Crawford', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Iola', 37.92, -95.39, 'Allen', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park City', 37.8, -97.31, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fredonia', 37.53, -95.82, 'Wilson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearwater', 37.5, -97.5, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McFarland', 39.05, -96.23, 'Wabaunsee', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coffeyville', 37.03, -95.61, 'Montgomery', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colby', 39.39, -101.05, 'Thomas', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden City', 37.97, -100.87, 'Finney', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McPherson', 38.37, -97.66, 'McPherson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baldwin City', 38.77, -95.18, 'Douglas', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gardner', 38.81, -94.92, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wellington', 37.26, -97.37, 'Sumner', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsburg', 37.41, -94.7, 'Crawford', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Junction City', 39.02, -96.83, 'Geary', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kansas City', 39.11, -94.62, 'Wyandotte', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Basehor', 39.14, -94.93, 'Leavenworth', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kechi', 37.79, -97.27, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Merriam', 39.02, -94.69, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Hill', 38.74, -94.82, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellaire', 37.76, -97.26, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Elder', 39.49, -98.3, 'Mitchell', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minneapolis', 39.12, -97.7, 'Ottawa', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goddard', 37.65, -97.57, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beloit', 39.45, -98.1, 'Mitchell', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mission', 39.02, -94.65, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mission Hills', 39.01, -94.61, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wichita', 37.69, -97.33, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stockton', 39.43, -99.26, 'Rooks', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prairie Village', 38.99, -94.63, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansing', 39.24, -94.9, 'Leavenworth', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winfield', 37.23, -96.99, 'Cowley', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawrence', 38.97, -95.23, 'Douglas', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Derby', 37.54, -97.26, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leavenworth', 39.31, -94.92, 'Leavenworth', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leawood', 38.96, -94.61, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dodge City', 37.75, -100.01, 'Ford', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lenexa', 38.95, -94.73, 'Johnson', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mulvane', 37.47, -97.24, 'Sumner', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tonganoxie', 39.1, -95.08, 'Leavenworth', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bonner Springs', 39.05, -94.88, 'Wyandotte', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liberal', 37.04, -100.92, 'Seward', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Topeka', 39.04, -95.67, 'Shawnee', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sabetha', 39.9, -95.8, 'Brown', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sedgwick', 37.91, -97.42, 'Sedgwick', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manhattan', 39.18, -96.57, 'Pottawatomie', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Hill', 38.74, -94.82, 'Miami', 'KS', 'Kansas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mulvane', 37.47, -97.24, 'Sedgwick', 'KS', 'Kansas');
