INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 39.09, -84.49, 'Campbell', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bowling Green', 36.99, -86.44, 'Warren', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brandenburg', 37.99, -86.16, 'Meade', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olive Hill', 38.3, -83.17, 'Carter', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Owensboro', 37.77, -87.11, 'Daviess', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paducah', 37.08, -88.6, 'McCracken', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Campbellsville', 37.34, -85.34, 'Taylor', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carrollton', 38.68, -85.17, 'Carroll', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prospect', 38.34, -85.61, 'Jefferson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Radcliff', 37.84, -85.94, 'Hardin', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 37.74, -84.29, 'Madison', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 39.08, -84.5, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crescent Springs', 39.05, -84.58, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Regis Park', 38.22, -85.61, 'Jefferson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crestview Hills', 39.02, -84.58, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Science Hill', 37.17, -84.63, 'Pulaski', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 37.64, -84.77, 'Boyle', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 39.11, -84.47, 'Campbell', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelbyville', 38.21, -85.22, 'Shelby', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shepherdsville', 37.98, -85.71, 'Bullitt', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Somerset', 37.09, -84.6, 'Pulaski', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkton', 36.81, -87.15, 'Todd', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Erlanger', 39.01, -84.6, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 37.68, -85.22, 'Washington', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 38.99, -84.62, 'Boone', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Mitchell', 39.05, -84.54, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Thomas', 39.07, -84.44, 'Campbell', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Wright', 39.05, -84.53, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union', 38.94, -84.68, 'Boone', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frankfort', 38.2, -84.87, 'Franklin', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 36.72, -86.57, 'Simpson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Versailles', 38.05, -84.72, 'Woodford', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walton', 38.87, -84.61, 'Boone', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warsaw', 38.78, -84.9, 'Gallatin', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glasgow', 36.99, -85.91, 'Barren', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Liberty', 37.92, -83.25, 'Morgan', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grayson', 38.33, -82.94, 'Carter', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greensburg', 37.26, -85.49, 'Green', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guthrie', 36.64, -87.16, 'Todd', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williamstown', 38.63, -84.56, 'Grant', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winchester', 37.99, -84.17, 'Clark', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hazard', 37.24, -83.19, 'Perry', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hopkinsville', 36.86, -87.48, 'Christian', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 38.94, -84.54, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jeffersontown', 38.19, -85.56, 'Jefferson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jenkins', 37.17, -82.63, 'Letcher', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 37.56, -85.25, 'Marion', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leitchfield', 37.48, -86.29, 'Grayson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 37.98, -84.47, 'Fayette', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Louisville', 38.25, -85.75, 'Jefferson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ludlow', 39.09, -84.54, 'Kenton', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madisonville', 37.32, -87.49, 'Hopkins', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayfield', 36.74, -88.63, 'Graves', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maysville', 38.64, -83.74, 'Mason', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 38.47, -82.63, 'Boyd', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bardstown', 37.8, -85.46, 'Nelson', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellefonte', 38.49, -82.69, 'Greenup', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Murray', 36.61, -88.31, 'Calloway', 'KY', 'Kentucky');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellevue', 39.1, -84.47, 'Campbell', 'KY', 'Kentucky');
