INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Golden Meadow', 29.37, -90.26, 'Lafourche', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gonzales', 30.23, -90.92, 'Ascension', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gretna', 29.91, -90.05, 'Jefferson', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hammond', 30.5, -90.46, 'Tangipahoa', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hornbeck', 31.32, -93.39, 'Vernon', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Houma', 29.5957696, -90.7195348, 'Terrebonne', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jennings', 30.22, -92.65, 'Jefferson Davis', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jonesboro', 32.24, -92.71, 'Jackson', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenner', 29.99, -90.24, 'Jefferson', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lafayette', 30.22, -92.01, 'Lafayette', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Charles', 30.22, -93.21, 'Calcasieu', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Livingston', 30.5, -90.74, 'Livingston', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lockport', 29.64, -90.53, 'Lafourche', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loreauville', 30.05, -91.73, 'Iberia', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mandeville', 30.35, -90.06, 'St. Tammany', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minden', 32.61, -93.28, 'Webster', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 32.5, -92.11, 'Ouachita', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morgan City', 29.69, -91.2, 'St. Mary', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Natchitoches', 31.76, -93.08, 'Natchitoches', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Iberia', 30, -91.81, 'Iberia', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Orleans', 29.95, -90.07, 'Orleans', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Roads', 30.7, -91.43, 'Pointe Coupee', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Opelousas', 30.53, -92.08, 'St. Landry', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pineville', 31.32, -92.43, 'Rapides', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plaquemine', 30.28, -91.23, 'Iberville', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ponchatoula', 30.43, -90.44, 'Tangipahoa', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Allen', 30.45, -91.21, 'West Baton Rouge', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Vincent', 30.33, -90.84, 'Livingston', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rayne', 30.23, -92.26, 'Acadia', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ruston', 32.52, -92.63, 'Lincoln', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Francisville', 30.77, -91.37, 'West Feliciana', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Gabriel', 30.25, -91.09, 'Iberville', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Joseph', 31.91, -91.23, 'Tensas', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Addis', 30.35, -91.26, 'West Baton Rouge', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shreveport', 32.52, -93.75, 'Caddo', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alexandria', 31.31, -92.44, 'Rapides', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcadia', 32.54, -92.92, 'Bienville', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Slidell', 30.27, -89.78, 'St. Tammany', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springhill', 33, -93.46, 'Webster', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sulphur', 30.23, -93.37, 'Calcasieu', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baton Rouge', 30.45, -91.15, 'East Baton Rouge', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunset', 30.41, -92.06, 'St. Landry', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bernice', 32.82, -92.65, 'Union', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berwick', 29.69, -91.21, 'St. Mary', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thibodaux', 29.79, -90.82, 'Lafourche', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blanchard', 32.58, -93.89, 'Caddo', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bogalusa', 30.79, -89.84, 'Washington', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bossier City', 32.51, -93.73, 'Bossier', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Broussard', 30.14, -91.96, 'Lafayette', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ville Platte', 30.68, -92.27, 'Evangeline', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brusly', 30.39, -91.25, 'West Baton Rouge', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vinton', 30.19, -93.58, 'Calcasieu', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 30.61, -92.05, 'St. Landry', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Welsh', 30.23, -92.82, 'Jefferson Davis', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carencro', 30.31, -92.04, 'Lafayette', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westwego', 29.9, -90.14, 'Jefferson', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chatham', 32.3, -92.45, 'Jackson', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Choudrant', 32.53, -92.51, 'Lincoln', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winnfield', 31.92, -92.63, 'Winn', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Youngsville', 30.09, -91.99, 'Lafayette', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zwolle', 31.63, -93.64, 'Sabine', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 30.47, -90.1, 'St. Tammany', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crowley', 30.21, -92.37, 'Acadia', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eunice', 30.49, -92.41, 'St. Landry', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmerville', 32.77, -92.4, 'Union', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferriday', 31.63, -91.55, 'Concordia', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklinton', 30.84, -90.15, 'Washington', 'LA', 'Louisiana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('French Settlement', 30.29, -90.79, 'Livingston', 'LA', 'Louisiana');
