INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aberdeen', 39.5, -76.16, 'Harford', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Annapolis', 38.97, -76.49, 'Anne Arundel', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baltimore', 39.29, -76.61, 'Baltimore (city)', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barnesville', 39.22, -77.37, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bel Air', 39.53, -76.34, 'Harford', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berlin', 38.32, -75.21, 'Worcester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berwyn Heights', 38.99, -76.91, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bladensburg', 38.93, -76.93, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boonsboro', 39.5, -77.65, 'Washington', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bowie', 39, -76.77, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brentwood', 38.94, -76.95, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookeville', 39.18, -77.05, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brunswick', 39.31, -77.62, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cambridge', 38.56, -76.07, 'Dorchester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cecilton', 39.4, -75.86, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centreville', 39.04, -76.06, 'Queen Anne''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charlestown', 39.57, -75.97, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesapeake Beach', 38.68, -76.53, 'Calvert', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesapeake City', 39.53, -75.8, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chestertown', 39.2, -76.06, 'Kent', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheverly', 38.92, -76.91, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chevy Chase Section Five', 38.98, -77.07, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chevy Chase Section Three', 38.97, -77.07, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chevy Chase View', 39.01, -77.08, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chevy Chase Village', 38.96, -77.07, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('College Park', 38.98, -76.93, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crisfield', 37.98, -75.85, 'Somerset', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cumberland', 39.65, -78.76, 'Allegany', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denton', 38.88, -75.82, 'Caroline', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('District Heights', 38.85, -76.88, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Easton', 38.77, -76.07, 'Talbot', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkton', 39.6, -75.83, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emmitsburg', 39.7, -77.32, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Federalsburg', 38.69, -75.77, 'Caroline', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frederick', 39.41, -77.41, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frostburg', 39.65, -78.92, 'Allegany', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fruitland', 38.32, -75.62, 'Wicomico', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gaithersburg', 39.14, -77.2, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garrett Park', 39.03, -77.09, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Echo', 38.96, -77.14, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glenarden', 38.92, -76.86, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenbelt', 39, -76.87, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greensboro', 38.97, -75.8, 'Caroline', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hagerstown', 39.64, -77.71, 'Washington', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hampstead', 39.6, -76.84, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Havre de Grace', 39.54, -76.09, 'Harford', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hurlock', 38.62, -75.85, 'Dorchester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hyattsville', 38.95, -76.94, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indian Head', 38.6, -77.16, 'Charles', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kensington', 39.02, -77.07, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kitzmiller', 39.38, -79.18, 'Garrett', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Plata', 38.52, -76.97, 'Charles', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Landover Hills', 38.94, -76.89, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurel', 39.09, -76.84, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laytonsville', 39.21, -77.14, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leonardtown', 38.29, -76.63, 'St. Mary''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 39.66, -76.88, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Martins Additions', 38.97, -77.06, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 39.44, -77.54, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morningside', 38.83, -76.89, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Airy', 39.37, -77.15, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Rainier', 38.94, -76.96, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Lake Park', 39.39, -79.38, 'Garrett', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Myersville', 39.5, -77.56, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Carrollton', 38.96, -76.87, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Market', 39.38, -77.26, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Windsor', 39.54, -77.1, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Beach', 38.7, -76.53, 'Calvert', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Brentwood', 38.94, -76.95, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Chevy Chase', 39, -77.07, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North East', 39.6, -75.94, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean City', 38.33, -75.08, 'Worcester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 38.68, -76.17, 'Talbot', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perryville', 39.56, -76.07, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pocomoke City', 38.07, -75.56, 'Worcester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poolesville', 39.14, -77.41, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Deposit', 39.6, -76.11, 'Cecil', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Queenstown', 38.99, -76.15, 'Queen Anne''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgely', 38.94, -75.88, 'Caroline', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverdale Park', 38.96, -76.93, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Hall', 39.13, -76.23, 'Kent', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockville', 39.08, -77.15, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salisbury', 38.36, -75.59, 'Wicomico', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seat Pleasant', 38.89, -76.9, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithsburg', 39.65, -77.57, 'Washington', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snow Hill', 38.17, -75.39, 'Worcester', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Somerset', 38.96, -77.09, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sudlersville', 39.18, -75.85, 'Queen Anne''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sykesville', 39.37, -76.96, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Takoma Park', 38.97, -77, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taneytown', 39.65, -77.17, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thurmont', 39.62, -77.41, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trappe', 38.65, -76.05, 'Talbot', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union Bridge', 39.56, -77.17, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University Park', 38.97, -76.94, 'Prince George''s', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington Grove', 39.13, -77.17, 'Montgomery', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westminster', 39.57, -76.99, 'Carroll', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Airy', 39.37, -77.15, 'Frederick', 'MD', 'Maryland');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Takoma Park', 38.97, -77, 'Prince George''s', 'MD', 'Maryland');
