INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brewer', 44.79, -68.76, 'Penobscot', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Old Town', 44.93, -68.64, 'Penobscot', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caribou', 46.86, -68.01, 'Aroostook', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portland', 43.66, -70.25, 'Cumberland', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Presque Isle', 46.68, -68.01, 'Aroostook', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockland', 44.1, -69.1, 'Knox', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eastport', 44.9, -66.98, 'Washington', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellsworth', 44.54, -68.41, 'Hancock', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Portland', 43.64, -70.24, 'Cumberland', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gardiner', 44.23, -69.77, 'Kennebec', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hallowell', 44.28, -69.79, 'Kennebec', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterville', 44.55, -69.63, 'Kennebec', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westbrook', 43.67, -70.37, 'Cumberland', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewiston', 44.1, -70.21, 'Androscoggin', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 44.09, -70.23, 'Androscoggin', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Augusta', 44.31, -69.77, 'Kennebec', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bangor', 44.8, -68.77, 'Penobscot', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bath', 43.91, -69.82, 'Sagadahoc', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belfast', 44.42, -69, 'Waldo', 'ME', 'Maine');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Biddeford', 43.49, -70.45, 'York', 'ME', 'Maine');
