INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheboygan', 45.64, -84.47, 'Cheboygan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chelsea', 42.31, -84.02, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferrysburg', 43.08, -86.22, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntington Woods', 42.48, -83.16, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Huron', 42.97, -82.42, 'St. Clair', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sylvan Lake', 42.61, -83.32, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melvindale', 42.28, -83.17, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesaning', 43.18, -84.11, 'Saginaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesaning', 43.18, -84.11, 'Saginaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portage', 42.2, -85.58, 'Kalamazoo', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tawas City', 44.26, -83.51, 'Iosco', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flat Rock', 42.09, -83.29, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flint', 43.01, -83.68, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylor', 42.24, -83.26, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tecumseh', 42, -83.94, 'Lenawee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn Hills', 42.68, -83.23, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flushing', 43.06, -83.85, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portland', 42.86, -84.9, 'Ionia', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clare', 43.81, -84.76, 'Clare', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prescott', 44.19, -83.93, 'Ogemaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Three Rivers', 41.94, -85.63, 'St. Joseph', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middleville', 42.71, -85.46, 'Barry', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midland', 43.61, -84.24, 'Midland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bangor', 42.31, -86.11, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clawson', 42.53, -83.14, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ishpeming', 46.48, -87.66, 'Marquette', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milan', 42.08, -83.68, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Traverse City', 44.76, -85.62, 'Grand Traverse', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frankenmuth', 43.33, -83.73, 'Saginaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trenton', 42.13, -83.17, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frankfort', 44.63, -86.23, 'Benzie', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 42.24, -84.4, 'Jackson', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 42.52, -83.3, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 42.6, -83.14, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fraser', 42.53, -82.94, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reading', 41.83, -84.74, 'Hillsdale', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 42.07, -83.97, 'Lenawee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jonesville', 41.98, -84.66, 'Hillsdale', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Battle Creek', 42.32, -85.17, 'Calhoun', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reed City', 43.87, -85.51, 'Osceola', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay City', 43.59, -83.88, 'Bay', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clio', 43.17, -83.73, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kalamazoo', 42.29, -85.58, 'Kalamazoo', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fremont', 43.46, -85.94, 'Newaygo', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bear Lake', 44.42, -86.14, 'Manistee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 41.91, -83.39, 'Monroe', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coldwater', 41.94, -85, 'Branch', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Utica', 42.62, -83.03, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Keego Harbor', 42.6, -83.34, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaverton', 43.88, -84.48, 'Gladwin', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vassar', 43.37, -83.58, 'Tuscola', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kentwood', 42.86, -85.64, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 42.8, -82.75, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belding', 43.09, -85.22, 'Ionia', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellaire', 44.98, -85.21, 'Antrim', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsford', 45.79, -88.07, 'Dickinson', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belleville', 42.2, -83.48, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrice', 42.83, -84.17, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden City', 42.32, -83.33, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Clemens', 42.59, -82.87, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverview', 42.17, -83.17, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Morris', 43.11, -83.69, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester', 42.68, -83.13, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Pleasant', 43.59, -84.76, 'Isabella', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester Hills', 42.65, -83.14, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockford', 43.12, -85.56, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berkley', 42.5, -83.18, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coopersville', 43.06, -85.93, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walker', 43, -85.76, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Linden', 47.19, -88.4, 'Houghton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Odessa', 42.78, -85.13, 'Ionia', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muskegon', 43.23, -86.24, 'Muskegon', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walled Lake', 42.53, -83.48, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corunna', 42.98, -84.11, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gibraltar', 42.09, -83.18, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muskegon Heights', 43.2, -86.23, 'Muskegon', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Romulus', 42.22, -83.39, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warren', 42.47, -83.02, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beulah', 44.63, -86.09, 'Benzie', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beverly Hills', 42.52, -83.22, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gladstone', 45.85, -87.02, 'Delta', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Negaunee', 46.49, -87.61, 'Marquette', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Croswell', 43.27, -82.62, 'Sanilac', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gladwin', 43.98, -84.48, 'Gladwin', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Rapids', 43.69, -85.48, 'Mecosta', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crystal Falls', 46.09, -88.33, 'Iron', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Baltimore', 42.68, -82.73, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseville', 42.49, -82.93, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bingham Farms', 42.51, -83.27, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watervliet', 42.18, -86.26, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Royal Oak', 42.48, -83.14, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Birmingham', 42.54, -83.21, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Beach', 41.77, -86.79, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansing', 42.73, -84.55, 'Ingham', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Blanc', 42.92, -83.62, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wayland', 42.67, -85.64, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lapeer', 43.05, -83.31, 'Lapeer', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Haven', 43.06, -86.22, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wayne', 42.28, -83.38, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lathrup Village', 42.49, -83.22, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Ledge', 42.75, -84.74, 'Eaton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurium', 47.23, -88.44, 'Houghton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saginaw', 43.41, -83.95, 'Saginaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blissfield', 41.83, -83.86, 'Lenawee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Rapids', 42.96, -85.66, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niles', 41.82, -86.25, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davison', 43.03, -83.51, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grandville', 42.9, -85.76, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Charles', 43.29, -84.14, 'Saginaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomfield Hills', 42.58, -83.24, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Clair', 42.82, -82.48, 'St. Clair', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Clair Shores', 42.49, -82.88, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dearborn', 42.32, -83.17, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dearborn Heights', 42.33, -83.27, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Muskegon', 43.25, -86.26, 'Muskegon', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Branch', 44.27, -84.23, 'Ogemaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decatur', 42.1, -85.97, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Johns', 43, -84.55, 'Clinton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Joseph', 42.1, -86.48, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Louis', 43.4, -84.6, 'Gratiot', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westland', 42.32, -83.4, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northville', 42.43, -83.48, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saline', 42.16, -83.78, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westphalia', 42.92, -84.79, 'Clinton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grayling', 44.66, -84.71, 'Crawford', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norton Shores', 43.16, -86.26, 'Muskegon', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boyne City', 45.21, -85.01, 'Charlevoix', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norway', 45.78, -87.9, 'Dickinson', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandusky', 43.42, -82.82, 'Sanilac', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Cloud', 43.55, -85.77, 'Newaygo', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Detroit', 42.33, -83.04, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Novi', 42.48, -83.47, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saugatuck', 42.65, -86.2, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('DeWitt', 42.84, -84.56, 'Clinton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 43.17, -85.25, 'Montcalm', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln Park', 42.25, -83.17, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sault Ste. Marie', 46.49, -84.34, 'Chippewa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dexter', 42.33, -83.88, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Park', 42.45, -83.18, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitehall', 43.41, -86.34, 'Muskegon', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dimondale', 42.64, -84.64, 'Eaton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgman', 41.94, -86.55, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grosse Pointe', 42.38, -82.91, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottville', 43.95, -86.28, 'Mason', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brighton', 42.52, -83.78, 'Livingston', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grosse Pointe Farms', 42.4, -82.89, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grosse Pointe Park', 42.37, -82.93, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Linden', 42.81, -83.78, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grosse Pointe Shores', 42.43, -82.87, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Litchfield', 42.04, -84.75, 'Hillsdale', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dowagiac', 41.98, -86.1, 'Cass', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grosse Pointe Woods', 42.44, -82.9, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Livonia', 42.36, -83.35, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooklyn', 42.1, -84.24, 'Jackson', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dundee', 41.95, -83.65, 'Monroe', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brown City', 43.21, -82.98, 'Sanilac', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durand', 42.91, -83.98, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shepherd', 43.52, -84.69, 'Isabella', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wixom', 42.52, -83.53, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wolverine Lake', 42.55, -83.47, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buchanan', 41.82, -86.36, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodhaven', 42.13, -83.24, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lowell', 42.93, -85.34, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Grand Rapids', 42.94, -85.61, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamtramck', 42.39, -83.04, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Jordan', 45.15, -85.12, 'Charlevoix', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hancock', 47.12, -88.58, 'Houghton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ludington', 43.95, -86.45, 'Mason', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orchard Lake', 42.58, -83.35, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Lansing', 42.73, -84.48, 'Ingham', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Tawas', 44.27, -83.49, 'Iosco', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eastpointe', 42.46, -82.95, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyandotte', 42.21, -83.14, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eaton Rapids', 42.5, -84.65, 'Eaton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyoming', 42.91, -85.7, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ortonville', 42.85, -83.44, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mackinaw City', 45.78, -84.72, 'Cheboygan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ypsilanti', 42.24, -83.61, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zeeland', 42.81, -86.01, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Otsego', 42.46, -85.69, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burton', 42.99, -83.61, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison Heights', 42.48, -83.1, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edwardsburg', 41.79, -86.08, 'Cass', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 42.2, -86.16, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 42.15, -84.03, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Byron', 42.82, -83.94, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hastings', 42.64, -85.29, 'Barry', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manistee', 44.24, -86.32, 'Manistee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cadillac', 44.25, -85.4, 'Wexford', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk Rapids', 44.89, -85.41, 'Antrim', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manistique', 45.95, -86.24, 'Schoolcraft', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Owosso', 42.99, -84.17, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Adrian', 41.89, -84.03, 'Lenawee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Haven', 42.4, -86.27, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Lyon', 42.46, -83.65, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hazel Park', 42.46, -83.1, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parchment', 42.32, -85.56, 'Kalamazoo', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southfield', 42.47, -83.22, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southgate', 42.21, -83.19, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sparta', 43.16, -85.71, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paw Paw', 42.21, -85.89, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albion', 42.24, -84.75, 'Calhoun', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Lake', 43.07, -86.19, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pellston', 45.55, -84.78, 'Emmet', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Algonac', 42.61, -82.53, 'St. Clair', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caro', 43.49, -83.39, 'Tuscola', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marine City', 42.71, -82.49, 'St. Clair', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 42.32, -85.23, 'Calhoun', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allegan', 42.52, -85.85, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland Park', 42.4, -83.09, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allen Park', 42.25, -83.21, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillsdale', 41.92, -84.63, 'Hillsdale', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Escanaba', 45.74, -87.06, 'Delta', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perry', 42.82, -84.21, 'Shiawassee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alma', 43.37, -84.65, 'Gratiot', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holland', 42.78, -86.1, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marquette', 46.54, -87.39, 'Marquette', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Essexville', 43.61, -83.84, 'Bay', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Petoskey', 45.37, -84.95, 'Emmet', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holly', 42.79, -83.62, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshall', 42.27, -84.96, 'Calhoun', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evart', 43.9, -85.25, 'Osceola', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alpena', 45.06, -83.43, 'Alpena', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinckney', 42.45, -83.94, 'Livingston', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marysville', 42.91, -82.48, 'St. Clair', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mason', 42.57, -84.44, 'Ingham', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sterling Heights', 42.58, -83.03, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stevensville', 42.01, -86.51, 'Berrien', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ann Arbor', 42.27, -83.72, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ann Arbor', 42.27, -83.72, 'Washtenaw', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Springs', 43.22, -85.55, 'Kent', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stockbridge', 42.45, -84.18, 'Ingham', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturgis', 41.79, -85.41, 'St. Joseph', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Center Line', 42.48, -83.02, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mattawan', 42.2, -85.78, 'Van Buren', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Houghton', 47.12, -88.56, 'Houghton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainwell', 42.44, -85.64, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington', 42.46, -83.37, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Howell', 42.6, -83.92, 'Livingston', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington Hills', 42.48, -83.37, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plymouth', 42.37, -83.47, 'Wayne', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charlevoix', 45.31, -85.25, 'Charlevoix', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charlotte', 42.56, -84.83, 'Eaton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fennville', 42.59, -86.1, 'Allegan', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudsonville', 42.87, -85.86, 'Ottawa', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pontiac', 42.63, -83.29, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferndale', 42.46, -83.13, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swartz Creek', 42.95, -83.83, 'Genesee', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Royal Oak', 42.48, -83.14, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansing', 42.73, -84.55, 'Eaton', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northville', 42.43, -83.48, 'Oakland', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mackinaw City', 45.78, -84.72, 'Emmet', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison Heights', 42.48, -83.1, 'Macomb', 'MI', 'Michigan');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansing', 42.73, -84.55, 'Clinton', 'MI', 'Michigan');
