INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paynesville', 45.38, -94.71, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodbury', 44.92, -92.95, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minnesota Lake', 43.84, -93.83, 'Faribault', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Louis Park', 44.94, -93.34, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodland', 44.94, -93.5, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frazee', 46.72, -95.7, 'Becker', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minnetonka', 44.91, -93.5, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minnetonka Beach', 44.93, -93.57, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thomson', 46.66, -92.39, 'Carlton', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arden Hills', 45.05, -93.15, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minnetrista', 44.93, -93.71, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Marys Point', 44.91, -92.76, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dellwood', 45.08, -92.97, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Le Sueur', 44.46, -93.91, 'Le Sueur', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pelican Rapids', 46.57, -96.08, 'Otter Tail', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burnsville', 44.76, -93.27, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Michael', 45.2, -93.66, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Argyle', 48.33, -96.82, 'Marshall', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Paul', 44.94, -93.09, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Paul Park', 44.84, -92.99, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Peter', 44.32, -93.95, 'Nicollet', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Worthington', 43.61, -95.59, 'Nobles', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fridley', 45.08, -93.26, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pequot Lakes', 46.6, -94.3, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tonka Bay', 44.9, -93.59, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Byron', 44.03, -92.64, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Detroit Lakes', 46.81, -95.84, 'Becker', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montevideo', 44.94, -95.72, 'Chippewa', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perham', 46.59, -95.57, 'Otter Tail', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caledonia', 43.63, -91.49, 'Houston', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monticello', 45.3, -93.79, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tower', 47.8, -92.27, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tracy', 44.23, -95.61, 'Lyon', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyoming', 45.33, -92.99, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('City of Scandia', 45.2538714, -92.827739, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dodge Center', 44.02, -92.85, 'Dodge', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moorhead', 46.87, -96.76, 'Clay', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandstone', 46.13, -92.86, 'Pine', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cambridge', 45.57, -93.22, 'Isanti', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trimont', 43.76, -94.7, 'Martin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gaylord', 44.55, -94.22, 'Sibley', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gem Lake', 45.05, -93.03, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Truman', 43.82, -94.43, 'Martin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zumbrota', 44.29, -92.66, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 47.52, -92.23, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dover', 43.97, -92.13, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sartell', 45.62, -94.2, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canby', 44.7, -96.27, 'Yellow Medicine', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pine City', 45.82, -92.96, 'Pine', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sauk Centre', 45.73, -94.95, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Austin', 43.66, -92.97, 'Mower', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pine Island', 44.2, -92.64, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sauk Rapids', 45.59, -94.16, 'Benton', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cannon Falls', 44.5, -92.9, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hopkins', 44.92, -93.46, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Savage', 44.77, -93.33, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon', 45.6, -94.45, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Babbitt', 47.7, -91.94, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Houston', 43.76, -91.56, 'Houston', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Backus', 46.82, -94.51, 'Cass', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lilydale', 44.91, -93.12, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morris', 45.58, -95.91, 'Stevens', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duluth', 46.78, -92.1, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Howard Lake', 45.06, -94.07, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoyt Lakes', 47.51, -92.13, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Twin Valley', 47.26, -96.25, 'Norman', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gibbon', 44.53, -94.52, 'Sibley', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morristown', 44.22, -93.44, 'Rice', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gilbert', 47.48, -92.46, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pipestone', 44, -96.31, 'Pipestone', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainview', 44.16, -92.17, 'Wabasha', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hugo', 45.15, -92.99, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tyler', 44.27, -96.13, 'Lincoln', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morton', 44.55, -94.98, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlton', 46.66, -92.42, 'Carlton', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sebeka', 46.62, -95.08, 'Wadena', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagan', 44.8, -93.16, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindstrom', 45.38, -92.84, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle Bend', 46.16, -95.03, 'Todd', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lino Lakes', 45.16, -93.08, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle Lake', 44.16, -93.88, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glencoe', 44.76, -94.15, 'McLeod', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mound', 44.93, -93.66, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carver', 44.76, -93.62, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hutchinson', 44.88, -94.36, 'McLeod', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lismore', 43.74, -95.94, 'Nobles', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mounds View', 45.1, -93.2, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shakopee', 44.79, -93.52, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barnesville', 46.65, -96.41, 'Clay', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Upsala', 45.81, -94.57, 'Morrison', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Bethel', 45.31, -93.2, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Little Canada', 45.02, -93.08, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Iron', 47.53, -92.62, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plymouth', 45.01, -93.45, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Lake', 43.93, -94.92, 'Cottonwood', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Grand Forks', 47.92, -97.02, 'Polk', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 45.02, -93.7, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Gull Lake', 46.4, -94.35, 'Cass', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Golden Valley', 45, -93.34, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vadnais Heights', 45.05, -93.07, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('International Falls', 48.6, -93.41, 'Koochiching', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Inver Grove Heights', 44.84, -93.04, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centerville', 45.16, -93.05, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sherburn', 43.65, -94.72, 'Martin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Champlin', 45.18, -93.39, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goodview', 44.06, -91.69, 'Winona', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nashwauk', 47.38, -93.16, 'Itasca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baxter', 46.34, -94.28, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eden Prairie', 44.85, -93.47, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chanhassen', 44.86, -93.53, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Isanti', 45.49, -93.24, 'Isanti', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Lake', 44.98, -93.57, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bayport', 45.02, -92.78, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chaska', 44.78, -93.6, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shoreview', 45.07, -93.14, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eden Valley', 45.32, -94.54, 'Meeker', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shorewood', 44.9, -93.58, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chatfield', 43.84, -92.18, 'Fillmore', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Prairie', 45.97, -94.86, 'Todd', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edina', 44.88, -93.34, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lonsdale', 44.48, -93.42, 'Rice', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ivanhoe', 44.46, -96.24, 'Lincoln', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Preston', 43.67, -92.08, 'Fillmore', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silver Bay', 47.29, -91.25, 'Lake', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Victoria', 44.85, -93.66, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nevis', 46.96, -94.83, 'Hubbard', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Princeton', 45.56, -93.58, 'Mille Lacs', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silver Lake', 44.9, -94.19, 'McLeod', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Janesville', 44.11, -93.7, 'Waseca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prior Lake', 44.71, -93.42, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Brighton', 45.06, -93.2, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chisago City', 45.37, -92.88, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Proctor', 46.74, -92.22, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chisholm', 47.48, -92.88, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Rapids', 47.23, -93.53, 'Itasca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Virginia', 47.52, -92.53, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Becker', 45.39, -93.87, 'Sherburne', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Circle Pines', 45.14, -93.15, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Hope', 45.03, -93.38, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wabasha', 44.38, -92.03, 'Wabasha', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Luverne', 43.65, -96.21, 'Rock', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waconia', 44.85, -93.78, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk River', 45.3, -93.56, 'Sherburne', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Market', 44.57, -93.35, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grant', 45.08, -92.91, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ramsey', 45.26, -93.45, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarkfield', 44.79, -95.8, 'Yellow Medicine', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elko', 44.56, -93.32, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Randall', 46.09, -94.5, 'Morrison', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wadena', 46.44, -95.13, 'Wadena', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belle Plaine', 44.62, -93.76, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jordan', 44.66, -93.62, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Prague', 44.54, -93.57, 'Le Sueur', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Slayton', 43.98, -95.75, 'Murray', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sleepy Eye', 44.29, -94.72, 'Brown', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Richland', 43.89, -93.49, 'Waseca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waite Park', 45.55, -94.22, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearwater', 45.41, -94.04, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madelia', 44.05, -94.41, 'Watonwan', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Ulm', 44.31, -94.46, 'Brown', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York Mills', 46.51, -95.37, 'Otter Tail', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belview', 44.6, -95.32, 'Redwood', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 45, -96.19, 'Lac qui Parle', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bemidji', 47.47, -94.88, 'Beltrami', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison Lake', 44.2, -93.81, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Wing', 44.56, -92.53, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 44.86, -93, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kasson', 44.02, -92.75, 'Dodge', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redwood Falls', 44.53, -95.11, 'Redwood', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenfield', 45.1, -93.69, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benson', 45.31, -95.6, 'Swift', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Keewatin', 47.39, -93.07, 'Itasca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mahtomedi', 45.06, -92.95, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wanamingo', 44.3, -92.79, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kelliher', 47.94, -94.44, 'Beltrami', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Saint Paul', 44.89, -93.03, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenwood', 44.91, -93.55, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kennedy', 48.64, -96.9, 'Kittson', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nisswa', 46.52, -94.28, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Renville', 44.78, -95.21, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenyon', 44.27, -92.98, 'Goodhue', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Falls', 48.19, -93.8, 'Koochiching', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Lake', 45.33, -93.74, 'Sherburne', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mankato', 44.16, -93.99, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waseca', 44.07, -93.5, 'Waseca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cohasset', 47.26, -93.62, 'Itasca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cokato', 45.07, -94.18, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Grove', 43.56, -91.63, 'Houston', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cold Spring', 45.45, -94.42, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kettle River', 46.49, -92.87, 'Carlton', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mantorville', 44.06, -92.75, 'Dodge', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bigfork', 47.74, -93.65, 'Itasca', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hadley', 44, -95.85, 'Murray', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richfield', 44.88, -93.28, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Grove', 45.07, -93.45, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Branch', 45.51, -92.98, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watertown', 44.96, -93.84, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Park', 44.93, -93.63, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cologne', 44.77, -93.78, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterville', 44.21, -93.56, 'Le Sueur', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia Heights', 45.04, -93.26, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Lake', 45.22, -94, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 45.26, -93.05, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Plain', 45, -93.65, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Mankato', 44.17, -94.03, 'Nicollet', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Birchwood', 45.06, -92.97, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Oaks', 45.1, -93.07, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bird Island', 44.76, -94.89, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Halstad', 47.35, -96.82, 'Norman', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Comfrey', 44.11, -94.9, 'Brown', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eveleth', 47.46, -92.53, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Saint Paul', 45.01, -92.99, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ham Lake', 45.25, -93.24, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mapleton', 43.92, -93.95, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waverly', 45.06, -93.96, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maplewood', 44.95, -92.99, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northfield', 44.45, -93.16, 'Rice', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wayzata', 44.97, -93.5, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Excelsior', 44.9, -93.56, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Robbinsdale', 45.03, -93.33, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eyota', 43.98, -92.22, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blackduck', 47.73, -94.54, 'Beltrami', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester', 44.02, -92.46, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stacy', 45.39, -92.98, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blaine', 45.16, -93.23, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marine on Saint Croix', 45.36, -92.77, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coon Rapids', 45.11, -93.28, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfax', 44.52, -94.72, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hancock', 45.49, -95.79, 'Stevens', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wells', 43.74, -93.72, 'Faribault', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corcoran', 45.09, -93.54, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockford', 45.08, -93.73, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairmont', 43.65, -94.46, 'Martin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hanover', 45.15, -93.66, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Crescent', 43.82, -91.3, 'Houston', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwood Young America', 44.77, -93.92, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockville', 45.47, -94.34, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blooming Prairie', 43.86, -93.05, 'Steele', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Grove', 45.34, -93.32, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Falcon Heights', 44.99, -93.16, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomington', 44.84, -93.29, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Park Heights', 45.03, -92.79, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harmony', 43.55, -92.01, 'Fillmore', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rogers', 45.18, -93.55, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Saint Paul', 44.91, -93.1, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blue Earth', 43.63, -94.1, 'Faribault', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottage Grove', 44.82, -92.94, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakdale', 44.96, -92.96, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottonwood', 44.6, -95.67, 'Lyon', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Faribault', 44.29, -93.26, 'Rice', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayer', 44.88, -93.88, 'Carver', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stewartville', 43.85, -92.48, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stillwater', 45.05, -92.8, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington', 44.64, -93.14, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Benton', 44.26, -96.28, 'Lincoln', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake City', 44.44, -92.26, 'Wabasha', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Crystal', 44.1, -94.21, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hastings', 44.74, -92.85, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Afton', 44.9, -92.78, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Elmo', 44.99, -92.87, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wheaton', 45.8, -96.49, 'Traverse', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crookston', 47.77, -96.6, 'Polk', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olivia', 44.77, -94.98, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseau', 48.84, -95.76, 'Roseau', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Bear Lake', 45.08, -93, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aitkin', 46.53, -93.71, 'Aitkin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boy River', 47.16, -94.12, 'Cass', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fergus Falls', 46.28, -96.07, 'Otter Tail', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cross Lake', 46.65, -94.11, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawley', 46.88, -96.31, 'Clay', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rosemount', 44.73, -93.12, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseville', 45, -93.15, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Braham', 45.72, -93.17, 'Isanti', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturgeon Lake', 46.38, -92.82, 'Pine', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brainerd', 46.35, -94.2, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crystal', 45.03, -93.36, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hayfield', 43.89, -92.84, 'Dodge', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 45.62, -94.57, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orono', 44.97, -93.6, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Lillian', 44.94, -94.87, 'Kandiyohi', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oronoco', 44.16, -92.53, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albert Lea', 43.64, -93.36, 'Freeborn', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medford', 44.17, -93.24, 'Steele', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fisher', 47.8, -96.8, 'Polk', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medicine Lake', 44.99, -93.41, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medina', 45.03, -93.58, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albertville', 45.23, -93.65, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ortonville', 45.3, -96.44, 'Big Stone', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Breezy Point', 46.61, -94.21, 'Crow Wing', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hector', 44.74, -94.71, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake', 43.54, -95.46, 'Nobles', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willmar', 45.12, -95.04, 'Kandiyohi', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Saint Croix Beach', 44.92, -92.76, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Melrose', 45.67, -94.8, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Floodwood', 46.92, -92.91, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Osakis', 45.86, -95.15, 'Douglas', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Shore', 46.48, -94.36, 'Cass', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunfish Lake', 44.87, -93.09, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mendota Heights', 44.88, -93.13, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alexandria', 45.88, -95.37, 'Douglas', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rushford', 43.8, -91.75, 'Fillmore', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danube', 44.79, -95.09, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Osseo', 45.11, -93.4, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakefield', 43.67, -95.17, 'Jackson', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeland', 44.95, -92.76, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooklyn Center', 45.07, -93.33, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeland Shores', 44.94, -92.76, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooklyn Park', 45.09, -93.35, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Otsego', 45.27, -93.59, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windom', 43.86, -95.11, 'Cottonwood', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Lake', 45.27, -92.98, 'Washington', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brooten', 45.5, -95.12, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dassel', 45.08, -94.3, 'Meeker', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milaca', 45.75, -93.65, 'Mille Lacs', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Browerville', 46.08, -94.86, 'Todd', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeville', 44.64, -93.24, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milan', 45.1, -95.91, 'Chippewa', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dawson', 44.93, -96.05, 'Lac qui Parle', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Owatonna', 44.08, -93.22, 'Steele', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 45.24, -93.51, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Anthony', 45.02, -93.21, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winnebago', 43.76, -94.16, 'Faribault', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hermantown', 46.8, -92.23, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Augusta', 45.45, -94.19, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Heron Lake', 43.79, -95.32, 'Jackson', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Bonifacius', 44.9, -93.74, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winona', 44.04, -91.63, 'Winona', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Charles', 43.96, -92.06, 'Winona', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deephaven', 44.92, -93.52, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fosston', 47.57, -95.75, 'Polk', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winsted', 44.96, -94.04, 'McLeod', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andover', 45.23, -93.29, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Clair', 44.08, -93.85, 'Blue Earth', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hibbing', 47.42, -92.93, 'St. Louis', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winthrop', 44.54, -94.36, 'Sibley', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Cloud', 45.56, -94.16, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park Rapids', 46.92, -95.05, 'Hubbard', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Francis', 45.38, -93.35, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylors Falls', 45.4, -92.65, 'Chisago', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buffalo', 45.17, -93.87, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minneapolis', 44.97, -93.26, 'Hennepin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Annandale', 45.26, -94.12, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint James', 43.98, -94.62, 'Watonwan', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anoka', 45.19, -93.38, 'Anoka', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkers Prairie', 46.15, -95.32, 'Otter Tail', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hill City', 46.99, -93.59, 'Aitkin', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Joseph', 45.56, -94.31, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lauderdale', 44.99, -93.2, 'Ramsey', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Apple Valley', 44.73, -93.21, 'Dakota', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delano', 45.04, -93.78, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 44.52, -94.88, 'Renville', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eden Valley', 45.32, -94.54, 'Stearns', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chatfield', 43.84, -92.18, 'Olmsted', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Prague', 44.54, -93.57, 'Scott', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearwater', 45.41, -94.04, 'Sherburne', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Comfrey', 44.11, -94.9, 'Cottonwood', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blooming Prairie', 43.86, -93.05, 'Dodge', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 45.24, -93.51, 'Wright', 'MN', 'Minnesota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Cloud', 45.56, -94.16, 'Sherburne', 'MN', 'Minnesota');
