INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maplewood', 38.61, -90.32, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wentzville', 38.81, -90.85, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Republic', 37.12, -93.48, 'Greene', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarkson Valley', 38.61, -90.58, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Plains', 36.72, -91.85, 'Howell', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clayton', 38.64, -90.32, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshall', 39.12, -93.19, 'Saline', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maryland Heights', 38.71, -90.42, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond Heights', 38.62, -90.31, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maryville', 40.34, -94.87, 'Nodaway', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wildwood', 38.58, -90.66, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willard', 37.3, -93.42, 'Greene', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverside', 39.17, -94.61, 'Platte', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Hill', 38.6, -90.37, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrisonville', 38.65, -94.34, 'Cass', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia', 38.95, -92.33, 'Boone', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodson Terrace', 38.72, -90.35, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolla', 37.95, -91.77, 'Phelps', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mexico', 39.16, -91.88, 'Audrain', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hazelwood', 38.77, -90.37, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 40.24, -94.33, 'Gentry', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottleville', 38.74, -90.65, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Higginsville', 39.07, -93.71, 'Lafayette', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Charles', 38.78, -90.48, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Clair', 38.34, -90.98, 'Franklin', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crestwood', 38.55, -90.38, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint James', 37.99, -91.61, 'Phelps', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Creve Coeur', 38.66, -90.42, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moberly', 39.41, -92.43, 'Randolph', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Johns', 38.71, -90.34, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Joseph', 39.76, -94.84, 'Buchanan', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Louis', 38.62, -90.19, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hollister', 36.62, -93.21, 'Taney', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monett', 36.92, -93.92, 'Barry', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Peters', 38.8, -90.62, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Robert', 37.82, -92.17, 'Pulaski', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arnold', 38.43, -90.37, 'Jefferson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sedalia', 38.7, -93.22, 'Pettis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seymour', 37.14, -92.76, 'Webster', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 37.1, -93.81, 'Lawrence', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ballwin', 38.59, -90.54, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Iberia', 38.09, -92.29, 'Miller', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 39.09, -94.41, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Des Peres', 38.6, -90.43, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Neosho', 36.86, -94.36, 'Newton', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 37.38, -89.66, 'Cape Girardeau', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nevada', 37.83, -94.35, 'Vernon', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sikeston', 36.87, -89.58, 'Scott', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Franklin', 39.01, -92.73, 'Howard', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Slater', 39.21, -93.06, 'Saline', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belton', 38.81, -94.53, 'Cass', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Madrid', 36.58, -89.52, 'New Madrid', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jefferson City', 38.57, -92.17, 'Cole', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 37.21, -93.29, 'Greene', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nixa', 37.04, -93.29, 'Christian', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Normandy', 38.72, -90.29, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eldon', 38.34, -92.58, 'Miller', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Kansas City', 39.13, -94.56, 'Clay', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Joplin', 37.08, -94.51, 'Jasper', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellisville', 38.59, -90.58, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black Jack', 38.79, -90.26, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kansas City', 39.09, -94.57, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturgeon', 39.23, -92.28, 'Boone', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sugar Creek', 39.1, -94.44, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Grove', 39, -94.12, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blue Springs', 39.01, -94.28, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakland', 38.57, -90.38, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Odessa', 38.99, -93.95, 'Lafayette', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunset Hills', 38.53, -90.4, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('O''Fallon', 38.81, -90.69, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eureka', 38.5, -90.62, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boonville', 38.97, -92.74, 'Cooper', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kirksville', 40.19, -92.58, 'Adair', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kirkwood', 38.58, -90.4, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olivette', 38.66, -90.37, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Excelsior Springs', 39.33, -94.22, 'Clay', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Osage Beach', 38.15, -92.61, 'Camden', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Branson', 36.64, -93.21, 'Taney', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Town and Country', 38.61, -90.46, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brentwood', 38.61, -90.34, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington', 37.78, -90.42, 'St. Francois', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeton', 38.76, -90.41, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Overland', 38.7, -90.36, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fenton', 38.51, -90.43, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Saint Louis', 38.79, -90.78, 'St. Charles', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ozark', 37.02, -93.2, 'Christian', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferguson', 38.74, -90.3, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Festus', 38.22, -90.39, 'Jefferson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pacific', 38.48, -90.74, 'Franklin', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park Hills', 37.85, -90.51, 'St. Francois', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkville', 39.19, -94.68, 'Platte', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union', 38.45, -91, 'Franklin', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florissant', 38.78, -90.32, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pasadena Hills', 38.7, -90.29, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University City', 38.65, -90.3, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 37.68, -92.66, 'Laclede', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lees Summit', 38.91, -94.38, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Piedmont', 37.15, -90.69, 'Wayne', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fulton', 38.84, -91.94, 'Callaway', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liberty', 39.24, -94.41, 'Clay', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camdenton', 38, -92.74, 'Camden', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cameron', 39.74, -94.24, 'Clinton', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Platte City', 39.37, -94.78, 'Platte', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cape Girardeau', 37.3, -89.51, 'Cape Girardeau', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Hill', 38.78, -94.26, 'Cass', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gladstone', 39.2, -94.55, 'Clay', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 38.59, -90.37, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warrensburg', 38.76, -93.73, 'Johnson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warrenton', 38.81, -91.14, 'Warren', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warsaw', 38.24, -93.38, 'Benton', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poplar Bluff', 36.75, -90.39, 'Butler', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warson Woods', 38.6, -90.38, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 38.55, -91.01, 'Franklin', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grain Valley', 39.01, -94.19, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centralia', 39.21, -92.13, 'Boone', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grandview', 38.88, -94.53, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Webster Groves', 38.59, -90.35, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesterfield', 38.66, -90.57, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Raymore', 38.8, -94.45, 'Cass', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Raytown', 39, -94.46, 'Jackson', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chillicothe', 39.79, -93.55, 'Livingston', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 38.59, -90.5, 'St. Louis', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monett', 36.92, -93.92, 'Lawrence', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sikeston', 36.87, -89.58, 'New Madrid', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Joplin', 37.08, -94.51, 'Newton', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kansas City', 39.09, -94.57, 'Clay', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cameron', 39.74, -94.24, 'DeKalb', 'MO', 'Missouri');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kansas City', 39.09, -94.57, 'Platte', 'MO', 'Missouri');
