INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Picayune', 30.52, -89.67, 'Pearl River', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Raymond', 32.25, -90.42, 'Hinds', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgeland', 32.42, -90.13, 'Madison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aberdeen', 33.82, -88.54, 'Monroe', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southaven', 34.98, -90.01, 'DeSoto', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Starkville', 33.45, -88.81, 'Oktibbeha', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Amory', 33.98, -88.48, 'Monroe', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay Saint Louis', 30.3, -89.33, 'Hancock', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belzoni', 33.18, -90.48, 'Humphreys', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tupelo', 34.25, -88.7, 'Lee', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Biloxi', 30.39, -88.88, 'Harrison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brandon', 32.27, -89.98, 'Rankin', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vicksburg', 32.35, -90.87, 'Warren', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walnut Grove', 32.59, -89.45, 'Leake', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waveland', 30.28, -89.37, 'Hancock', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 32.61, -90.03, 'Madison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Point', 33.6, -88.65, 'Clay', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarksdale', 34.2, -90.57, 'Coahoma', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleveland', 33.74, -90.72, 'Bolivar', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 32.34, -90.32, 'Hinds', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flowood', 32.3, -90.13, 'Rankin', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gautier', 30.38, -88.61, 'Jackson', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 33.41, -91.06, 'Washington', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gulfport', 30.36, -89.09, 'Harrison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hattiesburg', 31.32, -89.29, 'Forrest', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 32.29, -90.18, 'Hinds', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurel', 31.69, -89.13, 'Jones', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leland', 33.4, -90.89, 'Washington', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Beach', 30.35, -89.15, 'Harrison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 32.46, -90.11, 'Madison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Meridian', 32.36, -88.7, 'Lauderdale', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newton', 32.32, -89.16, 'Newton', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean Springs', 30.41, -88.82, 'Jackson', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olive Branch', 34.96, -89.82, 'DeSoto', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 34.36, -89.51, 'Lafayette', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pascagoula', 30.36, -88.55, 'Jackson', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pass Christian', 30.31, -89.24, 'Harrison', 'MS', 'Mississippi');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearl', 32.27, -90.13, 'Rankin', 'MS', 'Mississippi');
