INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anaconda', 46.12, -112.94, 'Deer Lodge', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belgrade', 45.77, -111.17, 'Gallatin', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Billings', 45.78, -108.5, 'Yellowstone', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bozeman', 45.67, -111.03, 'Gallatin', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Butte', 46, -112.53, 'Silver Bow', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Great Falls', 47.5, -111.3, 'Cascade', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamilton', 46.24, -114.16, 'Ravalli', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Havre', 48.54, -109.68, 'Hill', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Helena', 46.59, -112.03, 'Lewis and Clark', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kalispell', 48.19, -114.31, 'Flathead', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurel', 45.66, -108.77, 'Yellowstone', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Libby', 48.38, -115.55, 'Lincoln', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Missoula', 46.87, -113.99, 'Missoula', 'MT', 'Montana');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelby', 48.5, -111.85, 'Toole', 'MT', 'Montana');
