INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longview', 35.72, -81.38, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whiteville', 34.33, -78.7, 'Columbus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaufort', 34.71, -76.66, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilkesboro', 36.14, -81.16, 'Wilkes', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beech Mountain', 36.21, -81.88, 'Avery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williamston', 35.85, -77.05, 'Martin', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lucama', 35.64, -78, 'Wilson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilmington', 34.22, -77.94, 'New Hanover', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belhaven', 35.54, -76.62, 'Beaufort', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilson', 35.72, -77.91, 'Wilson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belmont', 35.24, -81.03, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lumberton', 34.61, -79, 'Robeson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belville', 34.23, -77.96, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benson', 35.38, -78.54, 'Johnston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 36.38, -79.95, 'Rockingham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wingate', 34.98, -80.44, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bermuda Run', 36, -80.42, 'Davie', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maggie Valley', 35.51, -83.09, 'Haywood', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winston-Salem', 36.09, -80.24, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bessemer City', 35.28, -81.28, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winterville', 35.52, -77.4, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maiden', 35.57, -81.21, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethel', 35.8, -77.37, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manteo', 35.9, -75.67, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beulaville', 34.92, -77.77, 'Duplin', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Biltmore Forest', 35.53, -82.52, 'Buncombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 35.68, -82, 'McDowell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wrightsville Beach', 34.2, -77.79, 'New Hanover', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Biscoe', 35.35, -79.77, 'Montgomery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mars Hill', 35.82, -82.54, 'Madison', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yadkinville', 36.13, -80.65, 'Yadkin', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black Creek', 35.63, -77.93, 'Wilson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yanceyville', 36.4, -79.33, 'Caswell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black Mountain', 35.61, -82.32, 'Buncombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marvin', 34.99, -80.81, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blowing Rock', 36.13, -81.67, 'Watauga', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Matthews', 35.11, -80.72, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zebulon', 35.82, -78.31, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayodan', 36.41, -79.96, 'Rockingham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boiling Spring Lakes', 34.03, -78.06, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boiling Springs', 35.25, -81.66, 'Cleveland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boone', 36.21, -81.67, 'Watauga', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mebane', 36.09, -79.26, 'Alamance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brevard', 35.23, -82.73, 'Transylvania', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeton', 35.12, -77.02, 'Craven', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middlesex', 35.79, -78.2, 'Nash', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mills River', 35.38, -82.56, 'Henderson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mineral Springs', 34.93, -80.66, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burgaw', 34.55, -77.92, 'Pender', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mint Hill', 35.17, -80.64, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 36.09, -79.43, 'Alamance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burnsville', 35.91, -82.3, 'Yancey', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mocksville', 35.89, -80.56, 'Davie', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Calabash', 33.89, -78.56, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 34.98, -80.54, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montreat', 35.64, -82.3, 'Buncombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mooresville', 35.58, -80.81, 'Iredell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 35.53, -82.83, 'Haywood', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morehead City', 34.72, -76.72, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morganton', 35.74, -81.68, 'Burke', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carolina Beach', 34.03, -77.89, 'New Hanover', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrisville', 35.82, -78.82, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carolina Shores', 33.9, -78.58, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carrboro', 35.91, -79.07, 'Orange', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Airy', 36.49, -80.6, 'Surry', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carthage', 35.34, -79.41, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Gilead', 35.21, -80, 'Montgomery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cary', 35.79, -78.78, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Holly', 35.29, -81.01, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caswell Beach', 33.89, -78.05, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nags Head', 35.95, -75.62, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nashville', 35.97, -77.96, 'Nash', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Bern', 35.1, -77.04, 'Craven', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chapel Hill', 35.91, -79.05, 'Orange', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newland', 36.08, -81.92, 'Avery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charlotte', 35.22, -80.84, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cherryville', 35.37, -81.37, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newton', 35.66, -81.22, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newton Grove', 35.24, -78.35, 'Sampson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('China Grove', 35.56, -80.58, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Claremont', 35.71, -81.14, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Topsail Beach', 34.49, -77.43, 'Onslow', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Wilkesboro', 36.15, -81.14, 'Wilkes', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clayton', 35.65, -78.45, 'Johnston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northwest', 34.31, -78.16, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clemmons', 36.02, -80.38, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 34.99, -78.32, 'Sampson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Island', 33.91, -78.16, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Ridge', 36.17, -79.98, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coats', 35.4, -78.67, 'Harnett', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakboro', 35.22, -80.32, 'Stanly', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean Isle Beach', 33.89, -78.42, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oriental', 35.03, -76.69, 'Pamlico', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 35.25, -82.19, 'Polk', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Concord', 35.4, -80.57, 'Cabarrus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 36.31, -78.59, 'Granville', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Connelly Springs', 35.74, -81.51, 'Burke', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conover', 35.7, -81.21, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cooleemee', 35.81, -80.55, 'Davie', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cornelius', 35.48, -80.86, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cramerton', 35.23, -81.07, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pikeville', 35.49, -77.98, 'Wayne', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Creedmoor', 36.12, -78.68, 'Granville', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pilot Mountain', 36.38, -80.46, 'Surry', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pine Knoll Shores', 34.69, -76.81, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 35.31, -81.17, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinehurst', 35.19, -79.46, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davidson', 35.49, -80.84, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pinetops', 35.78, -77.63, 'Edgecombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denton', 35.63, -80.11, 'Davidson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pineville', 35.08, -80.89, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dillsboro', 35.36, -83.25, 'Jackson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsboro', 35.72, -79.17, 'Chatham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Garden', 35.96, -79.76, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plymouth', 35.86, -76.74, 'Washington', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Polkton', 35, -80.2, 'Anson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Drexel', 35.75, -81.6, 'Burke', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duck', 36.16, -75.75, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunn', 35.3, -78.6, 'Harnett', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durham', 35.99, -78.89, 'Durham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Raeford', 34.98, -79.22, 'Hoke', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Raleigh', 35.77, -78.63, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ramseur', 35.73, -79.65, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Spencer', 35.68, -80.43, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Randleman', 35.81, -79.8, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eden', 36.48, -79.76, 'Rockingham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edenton', 36.05, -76.6, 'Chowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabeth City', 36.29, -76.25, 'Pasquotank', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabethtown', 34.62, -78.6, 'Bladen', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Springs', 34.81, -79.18, 'Robeson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkin', 36.24, -80.84, 'Surry', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reidsville', 36.35, -79.66, 'Rockingham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elm City', 35.8, -77.86, 'Wilson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elon', 36.1, -79.5, 'Alamance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emerald Isle', 34.67, -76.95, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('River Bend', 35.06, -77.14, 'Craven', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Enfield', 36.18, -77.66, 'Halifax', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roanoke Rapids', 36.46, -77.65, 'Halifax', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Erwin', 35.32, -78.67, 'Harnett', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fair Bluff', 34.31, -79.03, 'Columbus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairmont', 34.49, -79.11, 'Robeson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockwell', 35.55, -80.4, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rocky Mount', 35.93, -77.79, 'Nash', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rolesville', 35.92, -78.45, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmville', 35.59, -77.58, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayetteville', 35.05, -78.87, 'Cumberland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flat Rock', 35.27, -82.44, 'Henderson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rowland', 34.53, -79.29, 'Robeson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fletcher', 35.43, -82.5, 'Henderson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roxboro', 36.39, -78.98, 'Person', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest City', 35.33, -81.86, 'Rutherford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rural Hall', 36.24, -80.29, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Foxfire', 35.17, -79.57, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 35.18, -83.38, 'Macon', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklinville', 35.74, -79.69, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Pauls', 34.8, -78.97, 'Robeson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fuquay-Varina', 35.58, -78.8, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salisbury', 35.67, -80.47, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garner', 35.71, -78.61, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sanford', 35.47, -79.18, 'Lee', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gastonia', 35.26, -81.18, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gibsonville', 36.1, -79.54, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goldsboro', 35.38, -77.99, 'Wayne', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selma', 35.53, -78.28, 'Johnston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seven Devils', 36.15, -81.83, 'Avery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Graham', 36.06, -79.4, 'Alamance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granite Falls', 35.79, -81.43, 'Caldwell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shallotte', 33.97, -78.38, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granite Quarry', 35.61, -80.44, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelby', 35.29, -81.53, 'Cleveland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green Level', 36.12, -79.34, 'Alamance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Siler City', 35.72, -79.46, 'Chatham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greensboro', 36.07, -79.79, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 35.61, -77.36, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithfield', 35.5, -78.33, 'Johnston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grifton', 35.37, -77.43, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snow Hill', 35.45, -77.68, 'Greene', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southern Pines', 35.17, -79.39, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southern Shores', 36.13, -75.73, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southport', 33.92, -78.02, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spencer', 35.69, -80.43, 'Rowan', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spindale', 35.36, -81.92, 'Rutherford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrisburg', 35.32, -80.65, 'Cabarrus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Lake', 35.16, -78.97, 'Cumberland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spruce Pine', 35.91, -82.06, 'Mitchell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Havelock', 34.87, -76.9, 'Craven', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stallings', 35.09, -80.68, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stanfield', 35.23, -80.42, 'Stanly', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stanley', 35.35, -81.09, 'Gaston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Henderson', 36.32, -78.39, 'Vance', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hendersonville', 35.31, -82.46, 'Henderson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Statesville', 35.78, -80.88, 'Iredell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hickory', 35.73, -81.34, 'Catawba', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stokesdale', 36.23, -79.97, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('High Point', 35.95, -80, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stoneville', 36.46, -79.9, 'Rockingham', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highlands', 35.05, -83.19, 'Macon', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillsborough', 36.07, -79.09, 'Orange', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summerfield', 36.2, -79.9, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hobgood', 36.02, -77.39, 'Halifax', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Surf City', 34.42, -77.54, 'Pender', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holden Beach', 33.91, -78.3, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swansboro', 34.68, -77.11, 'Onslow', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holly Springs', 35.65, -78.83, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sylva', 35.37, -83.22, 'Jackson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hope Mills', 34.97, -78.94, 'Cumberland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tarboro', 35.89, -77.53, 'Edgecombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudson', 35.84, -81.49, 'Caldwell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylorsville', 35.92, -81.17, 'Alexander', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntersville', 35.41, -80.84, 'Mecklenburg', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indian Beach', 34.68, -76.89, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indian Trail', 35.07, -80.66, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thomasville', 35.88, -80.08, 'Davidson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tobaccoville', 36.23, -80.37, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 34.75, -77.43, 'Onslow', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Topsail Beach', 34.36, -77.63, 'Pender', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jamestown', 35.99, -79.93, 'Guilford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trinity', 35.89, -79.99, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troutman', 35.7, -80.88, 'Iredell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kannapolis', 35.48, -80.62, 'Cabarrus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 35.35, -79.89, 'Montgomery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tryon', 35.2, -82.23, 'Polk', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Unionville', 35.08, -80.5, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenly', 35.59, -78.12, 'Johnston', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valdese', 35.74, -81.56, 'Burke', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kernersville', 36.11, -80.07, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kill Devil Hills', 36.03, -75.67, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('King', 36.28, -80.35, 'Stokes', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kings Mountain', 35.24, -81.34, 'Cleveland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aberdeen', 35.13, -79.42, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kinston', 35.26, -77.58, 'Lenoir', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ahoskie', 36.28, -76.98, 'Hertford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kitty Hawk', 36.06, -75.7, 'Dare', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wadesboro', 34.96, -80.07, 'Anson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albemarle', 35.35, -80.2, 'Stanly', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Knightdale', 35.78, -78.48, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kure Beach', 33.99, -77.9, 'New Hanover', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wake Forest', 35.97, -78.5, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andrews', 35.2, -83.82, 'Cherokee', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Lure', 35.42, -82.2, 'Rutherford', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wallace', 34.73, -77.99, 'Duplin', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Angier', 35.5, -78.73, 'Harnett', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Park', 35.08, -80.63, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Waccamaw', 34.31, -78.5, 'Columbus', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Apex', 35.73, -78.85, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walnut Creek', 35.3, -77.86, 'Wayne', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Archdale', 35.91, -79.97, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warsaw', 34.99, -78.09, 'Duplin', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Asheboro', 35.7, -79.81, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurel Park', 35.31, -82.49, 'Henderson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 35.54, -77.05, 'Beaufort', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Asheville', 35.6, -82.55, 'Buncombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laurinburg', 34.77, -79.46, 'Scotland', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waxhaw', 34.92, -80.74, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlantic Beach', 34.69, -76.74, 'Carteret', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leland', 34.25, -78.04, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waynesville', 35.48, -82.98, 'Haywood', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lenoir', 35.91, -81.53, 'Caldwell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weaverville', 35.69, -82.56, 'Buncombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewisville', 36.09, -80.41, 'Forsyth', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weddington', 35.02, -80.76, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ayden', 35.47, -77.41, 'Pitt', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 35.82, -80.25, 'Davidson', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Badin', 35.4, -80.11, 'Stanly', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liberty', 35.85, -79.57, 'Randolph', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wendell', 35.78, -78.36, 'Wake', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lillington', 35.39, -78.81, 'Harnett', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wesley Chapel', 35, -80.67, 'Union', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bald Head Island', 33.86, -77.99, 'Brunswick', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincolnton', 35.47, -81.25, 'Lincoln', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Jefferson', 36.4, -81.49, 'Ashe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Banner Elk', 36.16, -81.87, 'Avery', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whispering Pines', 35.25, -79.37, 'Moore', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Locust', 35.25, -80.42, 'Stanly', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beech Mountain', 36.21, -81.88, 'Watauga', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkin', 36.24, -80.84, 'Wilkes', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rocky Mount', 35.93, -77.79, 'Edgecombe', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hickory', 35.73, -81.34, 'Caldwell', 'NC', 'North Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kannapolis', 35.48, -80.62, 'Rowan', 'NC', 'North Carolina');
