INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley City', 46.92, -98, 'Barnes', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jamestown', 46.91, -98.7, 'Stutsman', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wahpeton', 46.26, -96.6, 'Richland', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rugby', 48.36, -99.99, 'Pierce', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Killdeer', 47.37, -102.75, 'Dunn', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kulm', 46.3, -98.94, 'LaMoure', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakes', 46.13, -98.09, 'Dickey', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williston', 48.14, -103.61, 'Williams', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Forks', 47.92, -97.03, 'Grand Forks', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Devils Lake', 48.11, -98.86, 'Ramsey', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dickinson', 46.87, -102.78, 'Stark', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beulah', 47.26, -101.77, 'Mercer', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bismarck', 46.8, -100.78, 'Burleigh', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mandan', 46.82, -100.88, 'Morton', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bottineau', 48.82, -100.44, 'Bottineau', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Surrey', 48.23, -101.13, 'Ward', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Turtle Lake', 47.51, -100.89, 'McLean', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fargo', 46.87, -96.78, 'Cass', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minot', 48.23, -101.29, 'Ward', 'ND', 'North Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mohall', 48.76, -101.51, 'Renville', 'ND', 'North Dakota');
