INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Geneva', 40.52, -97.59, 'Fillmore', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gering', 41.82, -103.66, 'Scotts Bluff', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sutton', 40.6, -97.85, 'Clay', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gothenburg', 40.92, -100.16, 'Dawson', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Island', 40.92, -98.34, 'Hall', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norfolk', 42.02, -97.41, 'Madison', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Platte', 41.12, -100.76, 'Lincoln', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union', 40.81, -95.92, 'Cass', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gretna', 41.14, -96.23, 'Sarpy', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Creek', 41.03, -96.09, 'Cass', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley', 41.31, -96.34, 'Douglas', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ogallala', 41.12, -101.71, 'Keith', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Omaha', 41.25, -95.93, 'Douglas', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hastings', 40.58, -98.38, 'Adams', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oshkosh', 41.4, -102.34, 'Garden', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Henderson', 40.77, -97.81, 'York', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Papillion', 41.15, -96.04, 'Sarpy', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wayne', 42.23, -97.01, 'Wayne', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weeping Water', 40.87, -96.14, 'Cass', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holdrege', 40.44, -99.36, 'Phelps', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Point', 41.84, -96.7, 'Cuming', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Imperial', 40.51, -101.64, 'Chase', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Creighton', 42.46, -97.9, 'Knox', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crete', 40.62, -96.96, 'Saline', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('York', 40.86, -97.59, 'York', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ralston', 41.2, -96.04, 'Douglas', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kearney', 40.69, -99.08, 'Buffalo', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kimball', 41.23, -103.66, 'Kimball', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln', 40.8, -96.66, 'Lancaster', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alliance', 42.1, -102.87, 'Box Butte', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alma', 40.09, -99.36, 'Harlan', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Louisville', 40.99, -96.16, 'Cass', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottsbluff', 41.86, -103.66, 'Scotts Bluff', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seward', 40.9, -97.09, 'Seward', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkhorn', 41.28, -96.23, 'Douglas', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 40.86, -98, 'Hamilton', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beatrice', 40.26, -96.74, 'Gage', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Bend', 41, -96.24, 'Cass', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Sioux City', 42.47, -96.41, 'Dakota', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Falls City', 40.06, -95.6, 'Richardson', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellevue', 41.13, -95.89, 'Sarpy', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benkelman', 40.04, -101.53, 'Dundy', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Calhoun', 41.45, -96.02, 'Washington', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 41.08, -96.13, 'Sarpy', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fremont', 41.43, -96.49, 'Dodge', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blair', 41.54, -96.12, 'Washington', 'NE', 'Nebraska');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomfield', 42.59, -97.64, 'Knox', 'NE', 'Nebraska');
