INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rahway', 40.6, -74.27, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ramsey', 41.05, -74.14, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgefield Park', 40.85, -74.02, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgewood', 40.97, -74.11, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ringwood', 41.11, -74.24, 'Passaic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gibbsboro', 39.83, -74.96, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Rock', 40.96, -74.13, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseland', 40.82, -74.29, 'Essex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roselle Park', 40.66, -74.26, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hackensack', 40.88, -74.04, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rutherford', 40.82, -74.1, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hackettstown', 40.85, -74.82, 'Warren', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haddon Heights', 39.87, -75.06, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sayreville', 40.45, -74.36, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sea Isle City', 39.15, -74.69, 'Cape May', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Secaucus', 40.78, -74.05, 'Hudson', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ship Bottom', 39.64, -74.18, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Somerville', 40.57, -74.6, 'Somerset', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harvey Cedars', 39.7, -74.13, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hasbrouck Heights', 40.85, -74.08, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hawthorne', 40.94, -74.15, 'Passaic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('High Bridge', 40.66, -74.89, 'Hunterdon', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Plainfield', 40.57, -74.41, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South River', 40.44, -74.38, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hightstown', 40.26, -74.52, 'Mercer', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillsdale', 41, -74.04, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spotswood', 40.39, -74.39, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoboken', 40.74, -74.03, 'Hudson', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Lake Heights', 40.15, -74.03, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hopatcong', 40.93, -74.65, 'Sussex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stone Harbor', 39.05, -74.75, 'Cape May', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stratford', 39.82, -75.01, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summit', 40.74, -74.35, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Island Heights', 39.94, -74.14, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jersey City', 40.72, -74.07, 'Hudson', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tenafly', 40.92, -73.96, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kearny', 40.76, -74.14, 'Hudson', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tinton Falls', 40.3, -74.1, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trenton', 40.21, -74.74, 'Mercer', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lavallette', 39.97, -74.06, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ventnor City', 39.34, -74.47, 'Atlantic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vineland', 39.48, -75.02, 'Cumberland', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln Park', 40.92, -74.3, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allendale', 41.04, -74.12, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waldwick', 41.01, -74.11, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Asbury Park', 40.22, -74.01, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlantic City', 39.36, -74.42, 'Atlantic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atlantic Highlands', 40.4, -74.03, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Branch', 40.3, -73.99, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avalon', 39.1, -74.71, 'Cape May', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watchung', 40.63, -74.45, 'Somerset', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barnegat Light', 39.75, -74.1, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bayonne', 40.66, -74.11, 'Hudson', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 40.75, -74.41, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beach Haven', 39.55, -74.24, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Magnolia', 39.85, -75.03, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beachwood', 39.93, -74.19, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manasquan', 40.12, -74.04, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellmawr', 39.86, -75.09, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belvidere', 40.82, -75.07, 'Warren', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Paterson', 40.88, -74.19, 'Passaic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mantoloking', 40.03, -74.04, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westfield', 40.65, -74.34, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Margate City', 39.32, -74.5, 'Atlantic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medford Lakes', 39.85, -74.8, 'Burlington', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mendham', 40.77, -74.6, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boonton', 40.9, -74.4, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Merchantville', 39.94, -75.06, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodbury', 39.83, -75.15, 'Gloucester', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodcliff Lake', 41.02, -74.06, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wood-Ridge', 40.84, -74.08, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brielle', 40.1, -74.05, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brigantine', 39.41, -74.36, 'Atlantic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millville', 39.4, -75.03, 'Cumberland', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 40.07, -74.86, 'Burlington', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Butler', 41, -74.34, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montvale', 41.04, -74.02, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Caldwell', 40.83, -74.27, 'Essex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camden', 39.92, -75.11, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cape May', 38.93, -74.9, 'Cape May', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Arlington', 40.92, -74.63, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carteret', 40.57, -74.22, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountain Lakes', 40.89, -74.43, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chester', 40.78, -74.69, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Neptune City', 40.2, -74.02, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Netcong', 40.89, -74.7, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Brunswick', 40.48, -74.45, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Providence', 40.69, -74.4, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 40.63, -74.9, 'Hunterdon', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newark', 40.73, -74.17, 'Essex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Closter', 40.97, -73.96, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collingswood', 39.91, -75.07, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Plainfield', 40.63, -74.42, 'Somerset', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakland', 41.01, -74.26, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dover', 40.88, -74.56, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Old Tappan', 41.01, -73.99, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Orange', 40.76, -74.2, 'Essex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eatontown', 40.29, -74.05, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Passaic', 40.85, -74.12, 'Passaic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paterson', 40.91, -74.17, 'Passaic', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabeth', 40.66, -74.21, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pennington', 40.32, -74.79, 'Mercer', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Englewood', 40.89, -73.97, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perth Amboy', 40.5, -74.26, 'Middlesex', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Englishtown', 40.29, -74.35, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pine Hill', 39.78, -74.99, 'Camden', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fair Haven', 40.36, -74.03, 'Monmouth', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fair Lawn', 40.94, -74.13, 'Bergen', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pitman', 39.73, -75.13, 'Gloucester', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainfield', 40.63, -74.4, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fanwood', 40.64, -74.38, 'Union', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Point Pleasant', 40.08, -74.06, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Point Pleasant Beach', 40.09, -74.04, 'Ocean', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florham Park', 40.78, -74.38, 'Morris', 'NJ', 'New Jersey');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Lee', 40.85, -73.97, 'Bergen', 'NJ', 'New Jersey');
