INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alamogordo', 32.89, -105.96, 'Otero', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albuquerque', 35.08, -106.65, 'Bernalillo', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Angel Fire', 36.39, -105.28, 'Colfax', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Artesia', 32.84, -104.4, 'Eddy', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aztec', 36.82, -107.99, 'San Juan', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Capitan', 33.54, -105.57, 'Lincoln', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlsbad', 32.42, -104.22, 'Eddy', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cloudcroft', 32.95, -105.74, 'Otero', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clovis', 34.4, -103.2, 'Curry', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corrales', 35.23, -106.6, 'Sandoval', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deming', 32.26, -107.75, 'Luna', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Espanola', 35.99, -106.08, 'Rio Arriba', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington', 36.72, -108.21, 'San Juan', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gallup', 35.52, -108.74, 'McKinley', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hobbs', 32.7, -103.13, 'Lea', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Las Cruces', 32.31, -106.77, 'Dona Ana', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Lunas', 34.8, -106.73, 'Valencia', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Los Ranchos de Albuquerque', 35.16, -106.64, 'Bernalillo', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lovington', 32.94, -103.34, 'Lea', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portales', 34.18, -103.33, 'Roosevelt', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red River', 36.7, -105.4, 'Taos', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rio Rancho', 35.23, -106.66, 'Sandoval', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roswell', 33.39, -104.52, 'Chaves', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ruidoso Downs', 33.32, -105.6, 'Lincoln', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Fe', 35.68, -105.93, 'Santa Fe', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silver City', 32.77, -108.28, 'Grant', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taos', 36.4, -105.57, 'Taos', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taos Ski Valley', 36.59, -105.45, 'Taos', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Truth or Consequences', 33.12, -107.25, 'Sierra', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tucumcari', 35.17, -103.72, 'Quay', 'NM', 'New Mexico');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rio Rancho', 35.23, -106.66, 'Bernalillo', 'NM', 'New Mexico');
