INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scarsdale', 41, -73.78, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwich', 42.53, -75.52, 'Chenango', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Plains', 41.03, -73.76, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawrence', 40.61, -73.72, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedarhurst', 40.62, -73.72, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitesboro', 43.12, -75.29, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nyack', 41.09, -73.91, 'Rockland', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakfield', 43.06, -78.26, 'Genesee', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklinville', 42.33, -78.45, 'Cattaraugus', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean Beach', 40.64, -73.15, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williamsville', 42.96, -78.73, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Freeport', 40.65, -73.58, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ogdensburg', 44.69, -75.48, 'St. Lawrence', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Old Field', 40.95, -73.12, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olean', 42.07, -78.42, 'Cattaraugus', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilson', 43.3, -78.82, 'Niagara', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fulton', 43.32, -76.41, 'Oswego', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oneida', 43.09, -75.65, 'Madison', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liberty', 41.8, -74.74, 'Sullivan', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oneonta', 42.45, -75.06, 'Otsego', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden City', 40.72, -73.63, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindenhurst', 40.68, -73.37, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orchard Park', 42.76, -78.74, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Akron', 43.02, -78.49, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 42.65, -73.75, 'Albany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chittenango', 43.04, -75.86, 'Madison', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Geneseo', 42.79, -77.81, 'Livingston', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Churchville', 43.1, -77.88, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Geneva', 42.86, -76.97, 'Ontario', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sherrill', 43.07, -75.59, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yonkers', 40.93, -73.89, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liverpool', 43.1, -76.21, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ossining', 41.16, -73.86, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oswego', 43.45, -76.51, 'Oswego', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alfred', 42.25, -77.79, 'Allegany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allegany', 42.09, -78.49, 'Cattaraugus', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skaneateles', 42.94, -76.42, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lockport', 43.17, -78.69, 'Niagara', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Otisville', 41.47, -74.53, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glen Cove', 40.86, -73.63, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Long Beach', 40.58, -73.65, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glens Falls', 43.3, -73.64, 'Warren', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gloversville', 43.05, -74.34, 'Fulton', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 43.04, -75.37, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sodus Point', 43.27, -76.98, 'Wayne', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Amityville', 40.67, -73.41, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cobleskill', 42.67, -74.48, 'Schoharie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palmyra', 43.06, -77.23, 'Wayne', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cohoes', 42.77, -73.7, 'Albany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Great Neck', 40.8, -73.72, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Great Neck Plaza', 40.78, -73.72, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southampton', 40.88, -72.38, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Patchogue', 40.76, -73.01, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arcade', 42.53, -78.42, 'Wyoming', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colonie', 42.71, -73.83, 'Albany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ardsley', 41.01, -73.84, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Malverne', 40.67, -73.67, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Peekskill', 41.29, -73.92, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pelham', 40.9, -73.8, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mamaroneck', 40.94, -73.73, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pelham Manor', 40.89, -73.8, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Valley', 41.11, -74.04, 'Rockland', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manlius', 43, -75.97, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perry', 42.71, -78, 'Wyoming', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stamford', 42.4, -74.61, 'Delaware', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Attica', 42.86, -78.28, 'Wyoming', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 42.93, -76.56, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corinth', 43.24, -73.83, 'Saratoga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marcellus', 42.98, -76.34, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Phelps', 42.95, -77.05, 'Ontario', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cortland', 42.6, -76.18, 'Cortland', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamburg', 42.71, -78.82, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Babylon', 40.69, -73.32, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Massapequa Park', 40.68, -73.45, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Massena', 44.92, -74.89, 'St. Lawrence', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coxsackie', 42.35, -73.8, 'Greene', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Matinecock', 40.87, -73.57, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Suffern', 41.11, -74.14, 'Rockland', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maybrook', 41.48, -74.21, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Croton-on-Hudson', 41.2, -73.89, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsford', 43.09, -77.51, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Syracuse', 43.04, -76.14, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mechanicville', 42.9, -73.68, 'Saratoga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medina', 43.22, -78.38, 'Orleans', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Menands', 42.69, -73.72, 'Albany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Batavia', 42.99, -78.18, 'Genesee', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dansville', 42.56, -77.69, 'Livingston', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrison', 40.96, -73.71, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasantville', 41.13, -73.79, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beacon', 41.5, -73.96, 'Dutchess', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hastings-on-Hudson', 40.99, -73.87, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 41.44, -74.42, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('City of Tonawanda', 43.01, -78.88, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellport', 40.75, -72.93, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Byron', 43.03, -76.62, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Chester', 41, -73.66, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 42.72, -73.69, 'Rensselaer', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hempstead', 40.7, -73.61, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trumansburg', 42.54, -76.66, 'Tompkins', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Jefferson', 40.94, -73.06, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Jervis', 41.37, -74.69, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tuckahoe', 40.95, -73.82, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Depew', 42.9, -78.69, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Binghamton', 42.09, -75.91, 'Broome', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poughkeepsie', 41.7, -73.92, 'Dutchess', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 41.33, -74.18, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dobbs Ferry', 41.01, -73.87, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillburn', 41.12, -74.16, 'Rockland', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hilton', 43.28, -77.79, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union Springs', 42.83, -76.69, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dryden', 42.49, -76.29, 'Tompkins', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monticello', 41.65, -74.68, 'Sullivan', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holland Patent', 43.24, -75.25, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Utica', 43.1, -75.23, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boonville', 43.48, -75.33, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moravia', 42.71, -76.42, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Aurora', 42.76, -78.61, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hornell', 42.32, -77.66, 'Steuben', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Hampton', 40.96, -72.18, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Hook', 41.99, -73.87, 'Dutchess', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Horseheads', 42.16, -76.82, 'Chemung', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Hills', 40.79, -73.62, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Morris', 42.72, -77.87, 'Livingston', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 40.91, -73.83, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Victor', 42.98, -77.4, 'Ontario', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Rockaway', 40.64, -73.66, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Williston', 40.75, -73.63, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brockport', 43.21, -77.93, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bronxville', 40.93, -73.83, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ilion', 43.01, -75.03, 'Herkimer', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elbridge', 43.03, -76.44, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buchanan', 41.26, -73.93, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buffalo', 42.88, -78.87, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Village of Irvington', 41.0391, -73.867, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rochester', 43.15, -77.61, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Hartford', 43.07, -75.28, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockville Centre', 40.65, -73.64, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ithaca', 42.44, -76.49, 'Tompkins', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Hyde Park', 40.73, -73.68, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rome', 43.21, -75.45, 'Oneida', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elmira', 42.08, -76.8, 'Chemung', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Paltz', 41.74, -74.08, 'Ulster', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Rochelle', 40.91, -73.78, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterford', 42.79, -73.68, 'Saratoga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elmsford', 41.05, -73.82, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watertown', 43.97, -75.91, 'Jefferson', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnson City', 42.11, -75.95, 'Broome', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York', 40.71, -74, 'New York', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Lake', 42.93, -73.78, 'Saratoga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watervliet', 42.73, -73.7, 'Albany', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnstown', 43, -74.36, 'Fulton', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Esperance', 42.76, -74.25, 'Schoharie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newburgh', 41.5, -74.01, 'Orange', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canandaigua', 42.87, -77.28, 'Ontario', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fair Haven', 43.31, -76.7, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenmore', 42.96, -78.87, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rye', 40.98, -73.68, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canastota', 43.07, -75.75, 'Madison', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Webster', 43.21, -77.42, 'Monroe', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rye Brook', 41.01, -73.68, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weedsport', 43.04, -76.56, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saddle Rock', 40.79, -73.74, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmingdale', 40.73, -73.44, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niagara Falls', 43.09, -79.05, 'Niagara', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 44.59, -75.16, 'St. Lawrence', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingston', 41.92, -73.99, 'Ulster', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Carthage', 43.97, -75.61, 'Jefferson', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lackawanna', 42.82, -78.82, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saltaire', 40.63, -73.19, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sands Point', 40.85, -73.71, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Floral Park', 40.72, -73.7, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westbury', 40.75, -73.58, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flower Hill', 40.8, -73.68, 'Nassau', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westhampton Beach', 40.8, -72.61, 'Suffolk', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 42.9, -78.67, 'Erie', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Syracuse', 43.13, -76.12, 'Onondaga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saratoga Springs', 43.08, -73.78, 'Saratoga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Catskill', 42.21, -73.86, 'Greene', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansing', 42.48, -76.47, 'Tompkins', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saugerties', 42.07, -73.95, 'Ulster', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Larchmont', 40.92, -73.75, 'Westchester', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cayuga', 42.91, -76.72, 'Cayuga', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Geneva', 42.86, -76.97, 'Seneca', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York', 40.71, -74, 'Bronx', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York', 40.71, -74, 'Richmond', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York', 40.71, -74, 'Kings', 'NY', 'New York');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New York', 40.71, -74, 'Queens', 'NY', 'New York');
