INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parma', 41.4, -81.72, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 39.75, -84.19, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millersburg', 40.55, -81.91, 'Holmes', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Youngstown', 41.09, -80.64, 'Mahoning', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Broadview Heights', 41.31, -81.68, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenhills', 39.26, -84.52, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pataskala', 39.99, -82.67, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brook Park', 41.39, -81.8, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 40.1, -84.63, 'Darke', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakewood', 41.48, -81.79, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 39.71, -82.59, 'Fairfield', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zanesville', 39.94, -82.01, 'Muskingum', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookville', 39.83, -84.41, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grove City', 39.88, -83.09, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Groveport', 39.87, -82.88, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Defiance', 41.28, -84.35, 'Defiance', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pemberville', 41.41, -83.46, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delaware', 40.29, -83.06, 'Delaware', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University Heights', 41.49, -81.53, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Minster', 40.39, -84.37, 'Auglaize', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandusky', 41.44, -82.7, 'Erie', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Upper Arlington', 39.99, -83.06, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 39.43, -84.2, 'Warren', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pepper Pike', 41.47, -81.46, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Urbana', 40.1, -83.75, 'Champaign', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brunswick', 41.23, -81.84, 'Medina', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamilton', 39.39, -84.56, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 39.44, -84.36, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley View', 41.38, -81.6, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dover', 40.52, -81.47, 'Tuscarawas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Van Wert', 40.86, -84.58, 'Van Wert', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 40.67, -82.58, 'Richland', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vandalia', 39.89, -84.19, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dublin', 40.09, -83.11, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sebring', 40.92, -81.01, 'Mahoning', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrison', 39.26, -84.81, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroeville', 41.24, -82.69, 'Huron', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perrysburg', 41.55, -83.62, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seven Hills', 41.39, -81.67, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Versailles', 40.22, -84.48, 'Darke', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montgomery', 39.22, -84.35, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seville', 41.01, -81.86, 'Medina', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Liverpool', 40.61, -80.57, 'Columbiana', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shaker Heights', 41.47, -81.53, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Palestine', 40.83, -80.54, 'Columbiana', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Akron', 41.08, -81.51, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wadsworth', 41.02, -81.72, 'Medina', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pickerington', 39.88, -82.75, 'Fairfield', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eastlake', 41.65, -81.45, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sharonville', 39.26, -84.41, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moraine', 39.7, -84.21, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cambridge', 40.03, -81.58, 'Guernsey', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moreland Hills', 41.44, -81.42, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shawnee Hills', 40.15, -83.13, 'Delaware', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alliance', 40.91, -81.1, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Campbell', 41.07, -80.59, 'Mahoning', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lima', 40.74, -84.1, 'Allen', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln Heights', 39.23, -84.45, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Piqua', 40.14, -84.24, 'Miami', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canal Winchester', 39.84, -82.8, 'Fairfield', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canfield', 41.02, -80.76, 'Mahoning', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sidney', 40.28, -84.15, 'Shelby', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 40.79, -81.37, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Gilead', 40.54, -82.82, 'Morrow', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Heath', 40.02, -82.44, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Healthy', 39.23, -84.54, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elyria', 41.36, -82.1, 'Lorain', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hebron', 39.96, -82.49, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lockland', 39.22, -84.45, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlisle', 39.58, -84.32, 'Warren', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Englewood', 39.87, -84.3, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 40.39, -82.48, 'Knox', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Solon', 41.38, -81.44, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('London', 39.88, -83.44, 'Madison', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Munroe Falls', 41.14, -81.43, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Euclid', 41.59, -81.52, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lorain', 41.45, -82.18, 'Lorain', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Archbold', 41.52, -84.3, 'Fulton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairborn', 39.82, -84.01, 'Greene', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfax', 39.14, -84.39, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfield', 39.34, -84.56, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hilliard', 40.03, -83.15, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Napoleon', 41.39, -84.12, 'Henry', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Euclid', 41.52, -81.51, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 40.86, -82.31, 'Ashland', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Louisville', 40.83, -81.25, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Navarre', 40.72, -81.52, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Point', 38.41, -82.58, 'Lawrence', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashtabula', 41.86, -80.78, 'Ashtabula', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loveland', 39.26, -84.26, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Russell', 41.43, -81.36, 'Geauga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Celina', 40.54, -84.57, 'Mercer', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairlawn', 41.12, -81.6, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Athens', 39.32, -82.1, 'Athens', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Albany', 40.08, -82.8, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairview Park', 41.44, -81.86, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Bremen', 40.43, -84.37, 'Auglaize', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Clinton', 41.51, -82.93, 'Ottawa', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centerville', 39.62, -84.15, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Macedonia', 41.31, -81.5, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 41.31, -81.34, 'Portage', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chagrin Falls', 41.43, -81.38, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springboro', 39.55, -84.23, 'Warren', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madeira', 39.19, -84.36, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon', 41.45, -82.03, 'Lorain', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chardon', 41.61, -81.14, 'Geauga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Findlay', 41.04, -83.64, 'Hancock', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 41.77, -81.04, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Knoxville', 40.49, -84.31, 'Auglaize', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springdale', 39.28, -84.48, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Avon Lake', 41.5, -82.02, 'Lorain', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Lebanon', 39.74, -84.38, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 39.92, -83.8, 'Clark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Lexington', 39.71, -82.2, 'Perry', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hubbard', 41.15, -80.56, 'Trumbull', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New London', 41.08, -82.39, 'Huron', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portsmouth', 38.73, -82.99, 'Scioto', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huber Heights', 39.84, -84.12, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Powell', 40.15, -83.07, 'Delaware', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudson', 41.24, -81.44, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baltimore', 39.84, -82.6, 'Fairfield', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Park', 39.29, -84.5, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barberton', 41.01, -81.6, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Philadelphia', 40.48, -81.44, 'Tuscarawas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterville', 41.5, -83.71, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntsville', 40.44, -83.8, 'Logan', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huron', 41.39, -82.55, 'Erie', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wauseon', 41.54, -84.14, 'Fulton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fostoria', 41.15, -83.41, 'Seneca', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waverly', 39.12, -82.98, 'Pike', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 41.36, -81.63, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Steubenville', 40.36, -80.63, 'Jefferson', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('The Village of Indian Hill', 39.24, -84.29, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 39.55, -84.3, 'Warren', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheviot', 39.15, -84.61, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chillicothe', 39.33, -82.98, 'Ross', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newark', 40.05, -82.4, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay Village', 41.48, -81.92, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cincinnati', 39.16, -84.45, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beachwood', 41.46, -81.5, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newcomerstown', 40.27, -81.6, 'Tuscarawas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ravenna', 41.15, -81.24, 'Portage', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stow', 41.15, -81.44, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Streetsboro', 41.23, -81.34, 'Portage', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reading', 39.22, -84.44, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Strongsville', 41.31, -81.83, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mansfield', 40.75, -82.51, 'Richland', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beavercreek', 39.7, -84.06, 'Greene', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Heights', 41.41, -81.56, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reminderville', 41.34, -81.39, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bedford', 41.39, -81.53, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niles', 41.18, -80.76, 'Trumbull', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reynoldsburg', 39.95, -82.81, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellbrook', 39.63, -84.07, 'Greene', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richfield', 41.23, -81.63, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellefontaine', 40.36, -83.75, 'Logan', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellevue', 41.27, -82.84, 'Huron', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellville', 40.62, -82.51, 'Richland', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Canton', 40.87, -81.4, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fremont', 41.35, -83.12, 'Sandusky', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North College Hill', 39.21, -84.55, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clayton', 39.86, -84.36, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Carrollton City', 39.67, -84.25, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gahanna', 40.01, -82.87, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Olmsted', 41.41, -81.92, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Galion', 40.73, -82.78, 'Crawford', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Perry', 41.77, -81.14, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bentleyville', 41.41, -81.41, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleveland', 41.49, -81.69, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gallipolis', 38.8, -82.2, 'Gallia', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swanton', 41.58, -83.89, 'Fulton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Jefferson', 39.94, -83.26, 'Madison', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleveland Heights', 41.52, -81.55, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Ridgeville', 41.38, -82.01, 'Lorain', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleves', 39.16, -84.74, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Royalton', 41.31, -81.72, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garrettsville', 41.28, -81.09, 'Portage', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sylvania', 41.71, -83.71, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berea', 41.36, -81.85, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northwood', 41.6, -83.46, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Genoa', 41.51, -83.35, 'Ottawa', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norton', 41.02, -81.63, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwalk', 41.24, -82.61, 'Huron', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tallmadge', 41.1, -81.44, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westerville', 40.12, -82.92, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clyde', 41.3, -82.97, 'Sandusky', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mason', 39.36, -84.3, 'Warren', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norwood', 39.15, -84.45, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Massillon', 40.79, -81.52, 'Stark', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westlake', 41.45, -81.91, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Germantown', 39.62, -84.36, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maumee', 41.56, -83.65, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Harbor', 41.5, -83.14, 'Ottawa', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayfield', 41.55, -81.43, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coldwater', 40.47, -84.62, 'Mercer', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayfield Heights', 41.51, -81.45, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakwood', 39.72, -84.17, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rittman', 40.97, -81.78, 'Wayne', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Girard', 41.15, -80.7, 'Trumbull', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverside', 39.77, -84.12, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thurston', 39.84, -82.54, 'Fairfield', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Obetz', 39.87, -82.95, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 39.27, -84.45, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitehall', 39.96, -82.88, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitehouse', 41.51, -83.8, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bexley', 39.96, -82.93, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tipp City', 39.95, -84.17, 'Miami', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wickliffe', 41.6, -81.45, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rocky River', 41.47, -81.83, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 39.96, -82.99, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 39.96, -82.99, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 39.96, -82.99, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 39.96, -82.99, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Golf Manor', 39.18, -84.44, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willard', 41.05, -82.72, 'Huron', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Toledo', 41.66, -83.55, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medina', 41.13, -81.86, 'Medina', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olmsted Falls', 41.37, -81.9, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ontario', 40.75, -82.59, 'Richland', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orange', 41.44, -81.48, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willoughby', 41.63, -81.4, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trenton', 39.48, -84.45, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mentor', 41.66, -81.33, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rossford', 41.6, -83.56, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trotwood', 39.79, -84.31, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilmington', 39.44, -83.82, 'Clinton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 40.03, -84.2, 'Miami', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conneaut', 41.94, -80.55, 'Ashtabula', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oregon', 41.64, -83.48, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grand Rapids', 41.41, -83.86, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orrville', 40.84, -81.76, 'Wayne', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orwell', 41.53, -80.86, 'Ashtabula', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnstown', 40.15, -82.68, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grandview Heights', 39.97, -83.04, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blue Ash', 39.23, -84.37, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cortland', 41.33, -80.72, 'Trumbull', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miamisburg', 39.64, -84.28, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coshocton', 40.27, -81.85, 'Coshocton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granville', 40.06, -82.51, 'Licking', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ottawa', 41.01, -84.04, 'Putnam', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kent', 41.15, -81.35, 'Portage', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ottawa Hills', 41.66, -83.64, 'Lucas', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middlefield', 41.46, -81.07, 'Geauga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kettering', 39.68, -84.16, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ottoville', 40.93, -84.33, 'Putnam', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oxford', 39.5, -84.74, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green', 40.94, -81.48, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 39.51, -84.39, 'Butler', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crestline', 40.78, -82.73, 'Crawford', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bowling Green', 41.37, -83.65, 'Wood', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Worthington', 40.09, -83.01, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Bernard', 39.16, -84.49, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Twinsburg', 41.31, -81.44, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crooksville', 39.76, -82.09, 'Perry', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Painesville', 41.72, -81.24, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wyoming', 39.23, -84.46, 'Hamilton', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Clairsville', 40.08, -80.9, 'Belmont', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Xenia', 39.68, -83.92, 'Greene', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union', 39.89, -84.3, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kirtland', 41.62, -81.36, 'Lake', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yellow Springs', 39.8, -83.88, 'Greene', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('City of Cuyahoga Falls', 41.13, -81.48, 'Summit', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cuyahoga Heights', 41.43, -81.65, 'Cuyahoga', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salem', 40.9, -80.85, 'Columbiana', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pataskala', 39.99, -82.67, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Youngstown', 41.09, -80.64, 'Trumbull', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canal Winchester', 39.84, -82.8, 'Franklin', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlisle', 39.58, -84.32, 'Montgomery', 'OH', 'Ohio');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Euclid', 41.59, -81.52, 'Lake', 'OH', 'Ohio');
