INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skiatook', 36.36, -96, 'Osage', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrah', 35.48, -97.16, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ada', 34.77, -96.67, 'Pontotoc', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stillwater', 36.11, -97.05, 'Payne', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altus', 34.63, -99.33, 'Jackson', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alva', 36.8, -98.66, 'Woods', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anadarko', 35.07, -98.24, 'Caddo', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tahlequah', 35.91, -94.96, 'Cherokee', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ardmore', 34.17, -97.14, 'Carter', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tecumseh', 35.25, -96.93, 'Pottawatomie', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jenks', 36.02, -95.96, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bartlesville', 36.74, -95.98, 'Washington', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('The Village', 35.56, -97.55, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tishomingo', 34.23, -96.67, 'Johnston', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulsa', 36.15, -95.99, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bixby', 35.94, -95.88, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Velma', 34.46, -97.67, 'Stephens', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Verdigris', 36.23, -95.69, 'Rogers', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bradley', 34.87, -97.7, 'Grady', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawton', 34.6, -98.39, 'Comanche', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Broken Arrow', 36.05, -95.79, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buffalo', 36.83, -99.63, 'Harper', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waynoka', 36.58, -98.87, 'Woods', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weatherford', 35.52, -98.7, 'Custer', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marietta', 33.93, -97.11, 'Love', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodward', 36.43, -99.39, 'Woodward', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McAlester', 34.93, -95.76, 'Pittsburg', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yukon', 35.5, -97.76, 'Canadian', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chandler', 35.7, -96.88, 'Lincoln', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Miami', 36.87, -94.87, 'Ottawa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chickasha', 35.05, -97.93, 'Grady', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midwest City', 35.44, -97.39, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Choctaw', 35.49, -97.26, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Claremore', 36.31, -95.61, 'Rogers', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moore', 35.33, -97.48, 'Cleveland', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 35.51, -98.96, 'Custer', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muskogee', 35.74, -95.36, 'Muskogee', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mustang', 35.38, -97.72, 'Canadian', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nichols Hills', 35.55, -97.54, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nicoma Park', 35.49, -97.32, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coweta', 35.95, -95.65, 'Wagoner', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norman', 35.22, -97.43, 'Cleveland', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Davis', 34.5, -97.11, 'Murray', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Del City', 35.44, -97.44, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oklahoma City', 35.46, -97.51, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Owasso', 36.26, -95.85, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duncan', 34.5, -97.95, 'Stephens', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durant', 33.99, -96.37, 'Bryan', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edmond', 35.65, -97.47, 'Oklahoma', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Reno', 35.53, -97.95, 'Canadian', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perkins', 35.97, -97.03, 'Payne', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk City', 35.41, -99.4, 'Beckham', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Piedmont', 35.64, -97.74, 'Canadian', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Enid', 36.39, -97.87, 'Garfield', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ponca City', 36.7, -97.08, 'Kay', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poteau', 35.05, -94.62, 'Le Flore', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pryor', 36.3, -95.31, 'Mayes', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Purcell', 35.01, -97.36, 'McClain', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frederick', 34.39, -99.01, 'Tillman', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sallisaw', 35.46, -94.78, 'Sequoyah', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sand Springs', 36.13, -96.1, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goodwell', 36.59, -101.63, 'Texas', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sapulpa', 35.99, -96.11, 'Creek', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grove', 36.59, -94.76, 'Delaware', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guthrie', 35.87, -97.42, 'Logan', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Guymon', 36.68, -101.48, 'Texas', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shawnee', 35.32, -96.92, 'Pottawatomie', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skiatook', 36.36, -96, 'Tulsa', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulsa', 36.15, -95.99, 'Osage', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oklahoma City', 35.46, -97.51, 'Cleveland', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Skiatook', 36.36, -96, 'Woodward', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulsa', 36.15, -95.99, 'Rogers', 'OK', 'Oklahoma');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulsa', 36.15, -95.99, 'Wagoner', 'OK', 'Oklahoma');
