INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milton-Freewater', 45.93, -118.38, 'Umatilla', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milwaukie', 45.44, -122.63, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Molalla', 45.14, -122.57, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monmouth', 44.84, -123.23, 'Polk', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mosier', 45.68, -121.39, 'Wasco', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Angel', 45.06, -122.8, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Myrtle Creek', 43.02, -123.29, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newberg', 45.3, -122.97, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 44.63, -124.05, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Plains', 45.59, -122.99, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nyssa', 43.87, -116.99, 'Malheur', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oakridge', 43.74, -122.46, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ontario', 44.02, -116.96, 'Malheur', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oregon City', 45.35, -122.6, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Paisley', 42.69, -120.54, 'Lake', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pendleton', 45.67, -118.78, 'Umatilla', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Philomath', 44.54, -123.36, 'Benton', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Phoenix', 42.27, -122.81, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pilot Rock', 45.48, -118.82, 'Umatilla', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Orford', 42.74, -124.49, 'Curry', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portland', 45.52, -122.67, 'Multnomah', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prairie City', 44.46, -118.7, 'Grant', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prineville', 44.29, -120.83, 'Crook', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redmond', 44.27, -121.17, 'Deschutes', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reedsport', 43.7, -124.09, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockaway Beach', 45.61, -123.94, 'Tillamook', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rogue River', 42.43, -123.17, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roseburg', 43.21, -123.34, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Helens', 45.86, -122.8, 'Columbia', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salem', 44.94, -123.03, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandy', 45.39, -122.26, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scappoose', 45.75, -122.87, 'Columbia', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scotts Mills', 45.04, -122.66, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seaside', 45.99, -123.92, 'Clatsop', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shady Cove', 42.61, -122.81, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sherwood', 45.35, -122.84, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silverton', 45, -122.78, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sisters', 44.29, -121.54, 'Deschutes', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spray', 44.83, -119.79, 'Wheeler', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springfield', 44.04, -123.02, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stayton', 44.8, -122.79, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sublimity', 44.82, -122.79, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sutherlin', 43.39, -123.31, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sweet Home', 44.39, -122.73, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Talent', 42.24, -122.78, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tangent', 44.54, -123.1, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('The Dalles', 45.59, -121.17, 'Wasco', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tigard', 45.43, -122.77, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tillamook', 45.45, -123.84, 'Tillamook', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Toledo', 44.62, -123.93, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troutdale', 45.53, -122.38, 'Multnomah', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tualatin', 45.38, -122.76, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Turner', 44.84, -122.95, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union', 45.2, -117.86, 'Union', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vale', 43.98, -117.23, 'Malheur', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Veneta', 44.04, -123.35, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vernonia', 45.85, -123.19, 'Columbia', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waldport', 44.42, -124.06, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wallowa', 45.57, -117.52, 'Wallowa', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Linn', 45.36, -122.61, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilsonville', 45.29, -122.77, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodburn', 45.14, -122.85, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yachats', 44.31, -124.1, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yamhill', 45.34, -123.18, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 44.63, -123.1, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 42.19, -122.7, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aumsville', 44.84, -122.87, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aurora', 45.23, -122.75, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baker City', 44.77, -117.83, 'Baker', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bandon', 43.11, -124.4, 'Coos', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Banks', 45.61, -123.11, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay City', 45.52, -123.88, 'Tillamook', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaverton', 45.48, -122.8, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bend', 44.05, -121.31, 'Deschutes', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boardman', 45.83, -119.7, 'Morrow', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookings', 42.05, -124.28, 'Curry', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brownsville', 44.39, -122.98, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canby', 45.26, -122.69, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cannon Beach', 45.89, -123.96, 'Clatsop', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlton', 45.29, -123.17, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cascade Locks', 45.66, -121.89, 'Hood River', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Central Point', 42.37, -122.91, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coburg', 44.13, -123.06, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia City', 45.89, -122.8, 'Columbia', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Condon', 45.23, -120.18, 'Gilliam', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coos Bay', 43.36, -124.21, 'Coos', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coquille', 43.17, -124.18, 'Coos', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cornelius', 45.51, -123.05, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corvallis', 44.56, -123.26, 'Benton', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottage Grove', 43.79, -123.05, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Creswell', 43.91, -123.02, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 44.91, -123.31, 'Polk', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Damascus', 45.41, -122.45, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Depoe Bay', 44.8, -124.06, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Drain', 43.65, -123.31, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dundee', 45.27, -123.01, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunes City', 43.88, -124.11, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durham', 45.4, -122.75, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle Point', 42.47, -122.8, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Echo', 45.74, -119.19, 'Umatilla', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elgin', 45.56, -117.91, 'Union', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elkton', 43.63, -123.56, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Estacada', 45.28, -122.33, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eugene', 44.05, -123.08, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairview', 45.53, -122.43, 'Multnomah', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Falls City', 44.86, -123.43, 'Polk', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 43.98, -124.09, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Grove', 45.51, -123.11, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gladstone', 45.38, -122.59, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 42.73, -123.42, 'Douglas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gold Beach', 42.4, -124.42, 'Curry', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gold Hill', 42.43, -123.05, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grants Pass', 42.43, -123.32, 'Josephine', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gresham', 45.49, -122.43, 'Multnomah', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haines', 44.91, -117.93, 'Baker', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Halsey', 44.38, -123.1, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Happy Valley', 45.44, -122.53, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Heppner', 45.35, -119.55, 'Morrow', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hermiston', 45.84, -119.28, 'Umatilla', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hillsboro', 45.52, -122.98, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hood River', 45.7, -121.52, 'Hood River', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hubbard', 45.18, -122.8, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Idanha', 44.7, -122.07, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Independence', 44.85, -123.18, 'Polk', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('John Day', 44.41, -118.95, 'Grant', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jordan Valley', 42.97, -117.05, 'Malheur', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Junction City', 44.21, -123.2, 'Lane', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Keizer', 44.99, -123.02, 'Marion', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('King City', 45.4, -122.8, 'Washington', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Klamath Falls', 42.22, -121.78, 'Klamath', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Grande', 45.32, -118.08, 'Union', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lafayette', 45.24, -123.11, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Oswego', 45.42, -122.67, 'Clackamas', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeview', 42.18, -120.34, 'Lake', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 44.53, -122.9, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln City', 44.95, -124.01, 'Lincoln', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lyons', 44.77, -122.61, 'Linn', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McMinnville', 45.21, -123.19, 'Yamhill', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medford', 42.32, -122.87, 'Jackson', 'OR', 'Oregon');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mill City', 44.75, -122.47, 'Linn', 'OR', 'Oregon');
