INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trafford', 40.38, -79.75, 'Westmoreland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lock Haven', 41.13, -77.44, 'Clinton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Castle Shannon', 40.36, -80.02, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pittsburgh', 40.44, -79.99, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Erie', 42.12, -80.08, 'Erie', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farrell', 41.21, -80.49, 'Mercer', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trumbauersville', 40.41, -75.37, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lower Burrell', 40.55, -79.75, 'Westmoreland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chambersburg', 39.93, -77.66, 'Franklin', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Hills', 40.33, -79.96, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forest Hills', 40.41, -79.85, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tyrone', 40.67, -78.23, 'Blair', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Macungie', 40.51, -75.55, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chester', 39.84, -75.35, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plum', 40.5, -79.74, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fox Chapel', 40.51, -79.87, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warren', 41.84, -79.14, 'Warren', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mahanoy City', 40.81, -76.14, 'Schuylkill', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pottstown', 40.24, -75.64, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pottsville', 40.68, -76.19, 'Schuylkill', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin Park', 40.58, -80.08, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 40.17, -80.24, 'Washington', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Malvern', 40.03, -75.51, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Christiana', 39.95, -75.99, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Churchill', 40.43, -79.84, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Punxsutawney', 40.94, -78.97, 'Jefferson', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklintown', 40.07, -77.02, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterford', 41.94, -79.98, 'Erie', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Markleysburg', 39.73, -79.45, 'Fayette', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarion', 41.21, -79.38, 'Clarion', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quakertown', 40.44, -75.34, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gettysburg', 39.83, -77.23, 'Adams', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Chester', 39.96, -75.6, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marysville', 40.34, -76.92, 'Perry', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McKeesport', 40.34, -79.86, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarks Summit', 41.48, -75.7, 'Lackawanna', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Reading', 40.33, -75.92, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green Tree', 40.41, -80.04, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Mifflin', 40.36, -79.86, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alburtis', 40.51, -75.6, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mechanicsburg', 40.21, -77, 'Cumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coatesville', 39.98, -75.82, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Lion', 39.9, -76.6, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greensburg', 40.3, -79.53, 'Westmoreland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Reading', 40.33, -75.94, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westmont', 40.31, -78.95, 'Cambria', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allentown', 40.6, -75.49, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Media', 39.91, -75.38, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cochranton', 41.52, -80.04, 'Crawford', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverside', 40.95, -76.62, 'Northumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamburg', 40.55, -75.98, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Oak', 40.33, -79.8, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altoona', 40.51, -78.39, 'Blair', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middletown', 40.19, -76.73, 'Dauphin', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collegeville', 40.18, -75.45, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Marys', 41.42, -78.56, 'Elk', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hanover', 39.8, -76.98, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrisburg', 40.27, -76.88, 'Dauphin', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitehall', 40.36, -79.99, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ambler', 40.15, -75.22, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millersville', 39.99, -76.35, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coopersburg', 40.51, -75.39, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saltsburg', 40.48, -79.45, 'Indiana', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hatboro', 40.17, -75.1, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilkes-Barre', 41.24, -75.88, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ambridge', 40.58, -80.22, 'Beaver', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monongahela', 40.2, -79.92, 'Washington', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coplay', 40.67, -75.49, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saxonburg', 40.75, -79.81, 'Butler', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sayre', 41.97, -76.51, 'Bradford', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hatfield', 40.27, -75.29, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilkinsburg', 40.44, -79.88, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aspinwall', 40.49, -79.9, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroeville', 40.42, -79.78, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 41.33, -75.96, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallastown', 39.89, -76.64, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Schwenksville', 40.25, -75.46, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hazleton', 40.95, -75.97, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williamsport', 41.24, -77, 'Lycoming', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Atglen', 39.94, -75.97, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moosic', 41.35, -75.73, 'Lackawanna', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 40.96, -76.61, 'Montour', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scranton', 41.4, -75.66, 'Lackawanna', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hermitage', 41.23, -80.44, 'Mercer', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilson', 40.68, -75.24, 'Northampton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baldwin', 40.33, -79.97, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morrisville', 40.21, -74.78, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Darby', 39.91, -75.25, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selinsgrove', 40.79, -76.86, 'Snyder', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hollidaysburg', 40.42, -78.38, 'Blair', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wormleysburg', 40.26, -76.91, 'Cumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bally', 40.4, -75.58, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Murrysville', 40.42, -79.69, 'Westmoreland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Narberth', 40, -75.26, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dillsburg', 40.11, -77.03, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seven Fields', 40.69, -80.06, 'Butler', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Homewood', 40.81, -80.32, 'Beaver', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('York', 39.96, -76.72, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellefonte', 40.91, -77.77, 'Centre', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellevue', 40.49, -80.05, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nazareth', 40.74, -75.3, 'Northampton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dormont', 40.39, -80.03, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sharon Hill', 39.9, -75.27, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntingdon', 40.48, -78.01, 'Huntingdon', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Youngwood', 40.24, -79.57, 'Westmoreland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Zelienople', 40.79, -80.13, 'Butler', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bentleyville', 40.11, -80, 'Washington', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Castle', 41, -80.34, 'Lawrence', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Downingtown', 40, -75.7, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sharpsville', 41.25, -80.47, 'Mercer', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Indian Lake', 40.04, -78.85, 'Somerset', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ivyland', 40.2, -75.07, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethel Park', 40.32, -80.03, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Freedom', 39.73, -76.7, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Doylestown', 40.31, -75.12, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shippensburg', 40.05, -77.52, 'Cumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jonestown', 40.41, -76.47, 'Lebanon', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newtown', 40.22, -74.93, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dupont', 41.32, -75.74, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sinking Spring', 40.32, -76.01, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kennett Square', 39.84, -75.71, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethlehem', 40.62, -75.37, 'Northampton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norristown', 40.12, -75.33, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dushore', 41.52, -76.4, 'Sullivan', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Somerset', 40, -79.07, 'Somerset', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Grove', 39.87, -76.86, 'York', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingston', 41.26, -75.89, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomsburg', 41, -76.45, 'Columbia', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Northumberland', 40.89, -76.79, 'Northumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagles Mere', 41.41, -76.58, 'Sullivan', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Easton', 40.68, -75.22, 'Northampton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('State College', 40.79, -77.86, 'Centre', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kutztown', 40.51, -75.77, 'Berks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blossburg', 41.67, -77.06, 'Tioga', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Osborne', 40.53, -80.16, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ebensburg', 40.48, -78.72, 'Cambria', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Steelton', 40.23, -76.84, 'Dauphin', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laflin', 41.28, -75.8, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bradford', 41.95, -78.64, 'McKean', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkesburg', 39.95, -75.91, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Parkside', 39.86, -75.37, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eddystone', 39.86, -75.34, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stroudsburg', 40.98, -75.19, 'Monroe', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 40.03, -76.3, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgeport', 40.1, -75.34, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookhaven', 39.86, -75.38, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Patton', 40.63, -78.65, 'Cambria', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgewood', 40.43, -79.88, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swarthmore', 39.9, -75.34, 'Delaware', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Langhorne Manor', 40.16, -74.91, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camp Hill', 40.23, -76.91, 'Cumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pen Argyl', 40.86, -75.25, 'Northampton', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edinboro', 41.87, -80.13, 'Erie', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swoyersville', 41.29, -75.87, 'Luzerne', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lansdale', 40.24, -75.28, 'Montgomery', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carlisle', 40.2, -77.18, 'Cumberland', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perkasie', 40.37, -75.29, 'Bucks', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabethtown', 40.15, -76.6, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Terre Hill', 40.15, -76.05, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 40.34, -76.41, 'Lebanon', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lincoln', 40.31, -79.85, 'Allegheny', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carroll Valley', 39.74, -77.38, 'Adams', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Philadelphia', 39.95, -75.16, 'Philadelphia', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elverson', 40.15, -75.83, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Titusville', 41.62, -79.67, 'Crawford', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Liverpool', 40.57, -76.98, 'Perry', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carrolltown', 40.6, -78.7, 'Cambria', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Phoenixville', 40.13, -75.51, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ephrata', 40.17, -76.17, 'Lancaster', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Christiana', 39.95, -75.99, 'Chester', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bethlehem', 40.62, -75.37, 'Lehigh', 'PA', 'Pennsylvania');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trafford', 40.38, -79.75, 'Allegheny', 'PA', 'Pennsylvania');
