INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 34.85, -82.39, 'Greenville', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenwood', 34.19, -82.16, 'Greenwood', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greer', 34.93, -82.22, 'Greenville', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartsville', 34.37, -80.07, 'Darlington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hilton Head Island', 32.21, -80.75, 'Beaufort', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irmo', 34.08, -81.18, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Isle of Palms', 32.78, -79.79, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kiawah Island', 32.6, -80.08, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 33.98, -81.23, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Pleasant', 32.79, -79.86, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mullins', 34.2, -79.25, 'Marion', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Myrtle Beach', 33.68, -78.88, 'Horry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newberry', 34.27, -81.61, 'Newberry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North', 33.61, -81.1, 'Orangeburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Augusta', 33.5, -81.96, 'Aiken', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Charleston', 32.85, -79.97, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Myrtle Beach', 33.81, -78.68, 'Horry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orangeburg', 33.49, -80.85, 'Orangeburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pendleton', 34.65, -82.78, 'Anderson', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Royal', 32.37, -80.69, 'Beaufort', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prosperity', 34.2, -81.53, 'Newberry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ridgeland', 32.48, -80.98, 'Jasper', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Hill', 34.92, -81.02, 'York', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saluda', 34, -81.77, 'Saluda', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seabrook Island', 32.57, -80.17, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seneca', 34.68, -82.95, 'Oconee', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Simpsonville', 34.73, -82.25, 'Greenville', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spartanburg', 34.94, -81.93, 'Spartanburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springdale', 33.95, -81.1, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summerville', 33.01, -80.17, 'Dorchester', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sumter', 33.92, -80.34, 'Sumter', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Surfside Beach', 33.6, -78.97, 'Horry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swansea', 33.73, -81.09, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tega Cay', 35.02, -81.02, 'York', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Varnville', 32.85, -81.07, 'Hampton', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wagener', 33.65, -81.36, 'Aiken', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aiken', 33.56, -81.71, 'Aiken', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walterboro', 32.9, -80.66, 'Colleton', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anderson', 34.5, -82.65, 'Anderson', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andrews', 33.45, -79.56, 'Williamsburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Columbia', 33.99, -81.07, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bamberg', 33.29, -81.03, 'Bamberg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Batesburg-Leesville', 33.91, -81.53, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaufort', 32.43, -80.66, 'Beaufort', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williston', 33.4, -81.42, 'Barnwell', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bennettsville', 34.61, -79.68, 'Marlboro', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodruff', 34.73, -82.03, 'Spartanburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yemassee', 32.69, -80.85, 'Hampton', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('York', 34.99, -81.24, 'York', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Briarcliffe Acres', 33.78, -78.74, 'Horry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cayce', 33.96, -81.07, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Central', 34.72, -82.78, 'Pickens', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chapin', 34.16, -81.34, 'Lexington', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charleston', 32.77, -79.93, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheraw', 34.69, -79.88, 'Chesterfield', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chester', 34.7, -81.21, 'Chester', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clemson', 34.68, -82.83, 'Pickens', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 34.47, -81.88, 'Laurens', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia', 34, -81.03, 'Richland', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conway', 33.83, -79.04, 'Horry', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cowpens', 35.01, -81.8, 'Spartanburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Easley', 34.82, -82.6, 'Pickens', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edisto Beach', 32.47, -80.33, 'Colleton', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elloree', 33.53, -80.57, 'Orangeburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Florence', 34.19, -79.76, 'Florence', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Folly Beach', 32.65, -79.94, 'Charleston', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Mill', 35, -80.94, 'York', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goose Creek', 32.98, -80.03, 'Berkeley', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greer', 34.93, -82.22, 'Spartanburg', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irmo', 34.08, -81.18, 'Richland', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summerville', 33.01, -80.17, 'Berkeley', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andrews', 33.45, -79.56, 'Georgetown', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Batesburg-Leesville', 33.91, -81.53, 'Saluda', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yemassee', 32.69, -80.85, 'Beaufort', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Easley', 34.82, -82.6, 'Anderson', 'SC', 'South Carolina');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Summerville', 33.01, -80.17, 'Charleston', 'SC', 'South Carolina');
