INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kadoka', 43.83, -101.5, 'Jackson', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tulare', 44.73, -98.5, 'Spink', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elk Point', 42.68, -96.68, 'Union', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beresford', 43.08, -96.77, 'Union', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kimball', 43.74, -98.95, 'Brule', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pierre', 44.36, -100.35, 'Hughes', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Andes', 43.15, -98.54, 'Charles Mix', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valley Springs', 43.58, -96.46, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Norden', 44.58, -97.2, 'Hamlin', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Box Elder', 44.11, -103.06, 'Pennington', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brandon', 43.59, -96.57, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vermillion', 42.77, -96.92, 'Clay', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgewater', 43.55, -97.5, 'McCook', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Faith', 45.02, -102.03, 'Meade', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bristol', 45.34, -97.74, 'Day', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Faulkton', 45.03, -99.12, 'Faulk', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flandreau', 44.04, -96.59, 'Moody', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookings', 44.31, -96.79, 'Brookings', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Volga', 44.32, -96.92, 'Brookings', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lennox', 43.35, -96.89, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wagner', 43.07, -98.29, 'Charles Mix', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Letcher', 43.89, -98.13, 'Sanborn', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rapid City', 44.08, -103.23, 'Pennington', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warner', 45.32, -98.49, 'Brown', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redfield', 44.87, -98.51, 'Spink', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watertown', 44.89, -97.11, 'Codington', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gary', 44.79, -96.45, 'Deuel', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canton', 43.3, -96.59, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Castlewood', 44.72, -97.03, 'Hamlin', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 44, -97.11, 'Lake', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 43.42, -97.26, 'Turner', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitewood', 44.46, -103.63, 'Lawrence', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gregory', 43.23, -99.43, 'Gregory', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willow Lake', 44.62, -97.63, 'Clark', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Menno', 43.23, -97.57, 'Hutchinson', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winner', 43.37, -99.85, 'Tripp', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clear Lake', 44.74, -96.68, 'Deuel', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salem', 43.72, -97.38, 'McCook', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milbank', 45.21, -96.63, 'Grant', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrisburg', 43.43, -96.69, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woonsocket', 44.05, -98.27, 'Sanborn', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Worthing', 43.32, -96.76, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 43.62, -96.94, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colman', 43.98, -96.81, 'Moody', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mitchell', 43.7, -98.02, 'Davison', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yankton', 42.87, -97.39, 'Yankton', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Henry', 44.87, -97.46, 'Codington', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Herreid', 45.83, -100.06, 'Campbell', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sioux Falls', 43.54, -96.7, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aberdeen', 45.46, -98.48, 'Brown', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spearfish', 44.49, -103.85, 'Lawrence', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highmore', 44.52, -99.44, 'Hyde', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alcester', 43.02, -96.63, 'Union', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Custer', 43.76, -103.59, 'Custer', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Underwood', 44.09, -102.83, 'Pennington', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newell', 44.71, -103.42, 'Butte', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nisland', 44.67, -103.55, 'Butte', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Sioux City', 42.52, -96.48, 'Union', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hot Springs', 43.43, -103.47, 'Fall River', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('De Smet', 44.38, -97.55, 'Kingsbury', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Howard', 44.01, -97.52, 'Miner', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deadwood', 44.37, -103.72, 'Lawrence', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dell Rapids', 43.82, -96.7, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Humboldt', 43.64, -97.07, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Artesian', 44, -97.92, 'Sanborn', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huron', 44.36, -98.21, 'Beadle', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturgis', 44.4, -103.5, 'Meade', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baltic', 43.76, -96.74, 'Minnehaha', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tea', 43.44, -96.83, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beresford', 43.08, -96.77, 'Lincoln', 'SD', 'South Dakota');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sioux Falls', 43.54, -96.7, 'Lincoln', 'SD', 'South Dakota');
