INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Troy', 36.33, -89.16, 'Obion', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Unicoi', 36.19, -82.34, 'Unicoi', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Decherd', 35.2, -86.07, 'Franklin', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dickson', 36.07, -87.38, 'Dickson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dunlap', 35.37, -85.39, 'Sequatchie', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waynesboro', 35.31, -87.76, 'Wayne', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White House', 36.47, -86.65, 'Sumner', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elizabethton', 36.34, -82.21, 'Carter', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairview', 35.98, -87.12, 'Williamson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farragut', 35.88, -84.15, 'Knox', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fayetteville', 35.15, -86.57, 'Lincoln', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 35.92, -86.86, 'Williamson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gatlinburg', 35.71, -83.51, 'Sevier', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Germantown', 35.08, -89.81, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Goodlettsville', 36.32, -86.71, 'Davidson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hendersonville', 36.3, -86.61, 'Sumner', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 35.61, -88.81, 'Madison', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jellico', 36.58, -84.12, 'Campbell', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnson City', 36.31, -82.35, 'Washington', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsport', 36.54, -82.56, 'Sullivan', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingston Springs', 36.1, -87.11, 'Cheatham', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Knoxville', 35.96, -83.92, 'Knox', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Vergne', 36.01, -86.58, 'Rutherford', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeland', 35.23, -89.74, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lawrenceburg', 35.24, -87.33, 'Lawrence', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lebanon', 36.2, -86.29, 'Wilson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewisburg', 35.44, -86.78, 'Marshall', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 35.65, -88.39, 'Henderson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Loretto', 35.07, -87.43, 'Lawrence', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maryville', 35.75, -83.97, 'Blount', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medon', 35.45, -88.86, 'Madison', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Memphis', 35.14, -90.04, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milan', 35.91, -88.75, 'Gibson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Millington', 35.34, -89.89, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Morristown', 36.21, -83.29, 'Hamblen', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Juliet', 36.2, -86.51, 'Wilson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Munford', 35.44, -89.81, 'Tipton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Murfreesboro', 35.84, -86.39, 'Rutherford', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Ridge', 36.01, -84.26, 'Anderson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oliver Springs', 36.04, -84.34, 'Roane', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pegram', 36.1, -87.05, 'Cheatham', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arlington', 35.29, -89.66, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland City', 36.27, -87.06, 'Cheatham', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Piperton', 35.04, -89.62, 'Fayette', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Athens', 35.44, -84.59, 'McMinn', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pulaski', 35.19, -87.03, 'Giles', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bartlett', 35.2, -89.87, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Bank', 35.11, -85.29, 'Hamilton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brentwood', 36.03, -86.78, 'Williamson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bristol', 36.59, -82.18, 'Sullivan', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Savannah', 35.22, -88.24, 'Hardin', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sevierville', 35.86, -83.56, 'Sevier', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelbyville', 35.48, -86.46, 'Bedford', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Signal Mountain', 35.12, -85.34, 'Hamilton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithville', 35.96, -85.81, 'DeKalb', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smyrna', 35.98, -86.51, 'Rutherford', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Soddy-Daisy', 35.23, -85.19, 'Hamilton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chattanooga', 35.04, -85.3, 'Hamilton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clarksville', 36.52, -87.35, 'Montgomery', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Hill', 35.75, -86.93, 'Maury', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleveland', 35.15, -84.87, 'Bradley', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clifton', 35.38, -87.99, 'Wayne', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 36.1, -84.13, 'Anderson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Collierville', 35.04, -89.66, 'Shelby', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbia', 35.61, -87.03, 'Maury', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cookeville', 36.16, -85.5, 'Putnam', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 35.56, -89.64, 'Tipton', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White House', 36.47, -86.65, 'Robertson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsport', 36.54, -82.56, 'Hawkins', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Ridge', 36.01, -84.26, 'Roane', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oliver Springs', 36.04, -84.34, 'Anderson', 'TN', 'Tennessee');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brentwood', 36.03, -86.78, 'Davidson', 'TN', 'Tennessee');
