INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hearne', 30.87, -96.59, 'Robertson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Royse City', 32.97, -96.33, 'Rockwall', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodway', 31.5, -97.2, 'McLennan', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('College Station', 30.62, -96.33, 'Brazos', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colleyville', 32.88, -97.15, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wylie', 33.01, -96.53, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rusk', 31.79, -95.15, 'Cherokee', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yoakum', 29.28, -97.15, 'DeWitt', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sachse', 32.97, -96.59, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 29.7, -96.53, 'Colorado', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mission', 26.21, -98.32, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Henderson', 32.15, -94.79, 'Rusk', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Missouri City', 29.61, -95.53, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saginaw', 32.86, -97.36, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hewitt', 31.46, -97.19, 'McLennan', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Conroe', 30.31, -95.45, 'Montgomery', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Angelo', 31.46, -100.43, 'Tom Green', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Converse', 29.51, -98.31, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Antonio', 29.42, -98.49, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Benito', 26.13, -97.63, 'Cameron', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Coppell', 32.95, -97.01, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland Park', 32.83, -96.79, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Highland Village', 33.09, -97.04, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Copperas Cove', 31.12, -97.9, 'Coryell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hill Country Village', 29.58, -98.49, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corinth', 33.15, -97.06, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corpus Christi', 27.8, -97.39, 'Nueces', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Marcos', 29.88, -97.94, 'Hays', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hilshire Village', 29.79, -95.48, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Corsicana', 32.09, -96.46, 'Navarro', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Pleasant', 33.15, -94.96, 'Titus', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('San Saba', 31.19, -98.71, 'San Saba', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Fe', 29.37, -95.1, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Houston', 29.76, -95.36, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abilene', 32.44, -99.73, 'Taylor', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Schertz', 29.55, -98.26, 'Guadalupe', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Addison', 32.96, -96.82, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nacogdoches', 31.6, -94.65, 'Nacogdoches', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crockett', 31.31, -95.45, 'Houston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Humble', 29.99, -95.26, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seabrook', 29.56, -95.02, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alamo', 26.18, -98.12, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hunters Creek Village', 29.77, -95.49, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Nassau Bay', 29.54, -95.09, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alamo Heights', 29.48, -98.46, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntsville', 30.72, -95.55, 'Walker', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Crowley', 32.57, -97.36, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hurst', 32.82, -97.17, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sealy', 29.78, -96.15, 'Austin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seguin', 29.56, -97.96, 'Guadalupe', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selma', 29.58, -98.3, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Allen', 33.1, -96.67, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alpine', 30.35, -103.66, 'Brewster', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seymour', 33.59, -99.26, 'Baylor', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shady Shores', 33.16, -97.02, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alvarado', 32.4, -97.21, 'Johnson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Braunfels', 29.7, -98.12, 'Comal', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alvin', 29.42, -95.24, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Amarillo', 35.22, -101.83, 'Potter', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shenandoah', 30.18, -95.45, 'Montgomery', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sherman', 33.63, -96.6, 'Grayson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Irving', 32.81, -96.94, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Andrews', 32.31, -102.54, 'Andrews', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Angleton', 29.16, -95.43, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newark', 33, -97.48, 'Wise', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Annetta', 32.7, -97.67, 'Parker', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jacksonville', 31.96, -95.27, 'Cherokee', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niederwald', 30, -97.72, 'Caldwell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jasper', 30.92, -93.99, 'Jasper', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithville', 30, -97.15, 'Bastrop', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jersey Village', 29.88, -95.56, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snyder', 32.71, -100.91, 'Scurry', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deer Park', 29.7, -95.12, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Socorro', 31.65, -106.3, 'El Paso', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Del Rio', 29.36, -100.89, 'Val Verde', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denison', 33.75, -96.53, 'Grayson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sonora', 30.56, -100.64, 'Sutton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denton', 33.21, -97.13, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Richland Hills', 32.83, -97.22, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Argyle', 33.12, -97.18, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('DeSoto', 32.58, -96.85, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arlington', 32.73, -97.1, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southlake', 32.94, -97.13, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Southside Place', 29.7, -95.43, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dickinson', 29.46, -95.05, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Katy', 29.78, -95.82, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Ridge North', 30.16, -95.44, 'Montgomery', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Valley', 29.78, -95.5, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Austin', 30.26, -97.74, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Keller', 32.93, -97.25, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stafford', 29.61, -95.55, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kemah', 29.54, -95.02, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Odessa', 31.84, -102.36, 'Ector', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Donna', 26.17, -98.05, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Azle', 32.89, -97.54, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Double Oak', 33.06, -97.11, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stephenville', 32.22, -98.2, 'Erath', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Balch Springs', 32.72, -96.62, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dumas', 35.86, -101.97, 'Moore', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duncanville', 32.65, -96.9, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kerrville', 30.04, -99.14, 'Kerr', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle Pass', 28.7, -100.49, 'Maverick', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orange', 30.09, -93.73, 'Orange', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sugar Land', 29.61, -95.63, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Killeen', 31.11, -97.72, 'Bell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kingsville', 27.51, -97.85, 'Kleberg', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sulphur Springs', 33.13, -95.6, 'Hopkins', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Overton', 32.27, -94.97, 'Rusk', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunnyvale', 32.79, -96.56, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bartonville', 33.07, -97.13, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bastrop', 30.11, -97.31, 'Bastrop', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay City', 28.98, -95.96, 'Matagorda', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palacios', 28.7, -96.21, 'Matagorda', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Palestine', 31.76, -95.63, 'Anderson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baytown', 29.73, -94.97, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sweeny', 29.03, -95.69, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Krum', 33.26, -97.23, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edinburg', 26.3, -98.16, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kyle', 29.98, -97.87, 'Hays', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tahoka', 33.16, -101.79, 'Lynn', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pampa', 35.53, -100.95, 'Gray', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaumont', 30.08, -94.1, 'Jefferson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Campo', 29.19, -96.26, 'Wharton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Grange', 29.9, -96.87, 'Fayette', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bedford', 32.84, -97.14, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pantego', 32.71, -97.15, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylor', 30.57, -97.4, 'Williamson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('El Paso', 31.75, -106.48, 'El Paso', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellaire', 29.7, -95.45, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Porte', 29.66, -95.01, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pasadena', 29.69, -95.2, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Temple', 31.09, -97.34, 'Bell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lacy-Lakeview', 31.62, -97.1, 'McLennan', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Belton', 31.05, -97.46, 'Bell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearland', 29.56, -95.28, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Terrell', 32.73, -96.27, 'Kaufman', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lago Vista', 30.46, -97.98, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benbrook', 32.67, -97.46, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Texarkana', 33.42, -94.04, 'Bowie', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Texas City', 29.38, -94.9, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ennis', 32.32, -96.62, 'Ellis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Jackson', 29.03, -95.43, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('The Colony', 33.08, -96.88, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Euless', 32.83, -97.08, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('The Hills', 30.34, -97.98, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Spring', 32.25, -101.47, 'Howard', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Perryton', 36.4, -100.8, 'Ochiltree', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakeway', 30.36, -97.99, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pflugerville', 30.43, -97.62, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairview', 33.15, -96.63, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lamesa', 32.73, -101.95, 'Dawson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lampasas', 31.06, -98.18, 'Lampasas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 32.59, -96.75, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laredo', 27.5, -99.5, 'Webb', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmers Branch', 32.92, -96.89, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tomball', 30.09, -95.61, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boerne', 29.79, -98.73, 'Kendall', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('League City', 29.5, -95.09, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plainview', 34.18, -101.7, 'Hale', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leander', 30.57, -97.85, 'Williamson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plano', 33.01, -96.69, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flatonia', 29.68, -97.1, 'Fayette', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leon Valley', 29.49, -98.61, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Flower Mound', 33.01, -97.09, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trophy Club', 32.99, -97.18, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Levelland', 33.58, -102.37, 'Hockley', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lewisville', 33.04, -96.99, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Stockton', 30.89, -102.87, 'Pecos', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Aransas', 27.83, -97.06, 'Nueces', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fort Worth', 32.72, -97.32, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Arthur', 29.89, -93.92, 'Jefferson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Lavaca', 28.61, -96.62, 'Calhoun', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tyler', 32.35, -95.3, 'Smith', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brenham', 30.16, -96.39, 'Washington', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fredericksburg', 30.27, -98.87, 'Gillespie', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Freeport', 28.95, -95.35, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portland', 27.87, -97.32, 'San Patricio', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridge City', 30.02, -93.84, 'Orange', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Friendswood', 29.52, -95.2, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Universal City', 29.54, -98.29, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Frisco', 33.15, -96.82, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Littlefield', 33.91, -102.32, 'Lamb', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University Park', 32.85, -96.8, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Live Oak', 29.56, -98.33, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Livingston', 30.71, -94.93, 'Polk', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brownfield', 33.18, -102.27, 'Terry', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lockhart', 29.88, -97.66, 'Caldwell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gainesville', 33.62, -97.13, 'Cooke', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brownsville', 25.9, -97.49, 'Cameron', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brownwood', 31.7, -98.99, 'Brown', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Galveston', 29.3, -94.79, 'Galveston', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bryan', 30.67, -96.36, 'Brazos', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longview', 32.5, -94.74, 'Gregg', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prosper', 33.23, -96.8, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Victoria', 28.8, -97, 'Victoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garland', 32.91, -96.63, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buda', 30.08, -97.84, 'Hays', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gatesville', 31.43, -97.74, 'Coryell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waco', 31.54, -97.14, 'McLennan', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Quintana', 28.93, -95.3, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Georgetown', 30.63, -97.67, 'Williamson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bulverde', 29.74, -98.45, 'Comal', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bunker Hill Village', 29.76, -95.52, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lowry Crossing', 33.15, -96.54, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burkburnett', 34.09, -98.57, 'Wichita', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lubbock', 33.57, -101.85, 'Lubbock', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lucas', 33.08, -96.57, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burleson', 32.54, -97.32, 'Johnson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burnet', 30.75, -98.22, 'Burnet', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lufkin', 31.33, -94.72, 'Angelina', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watauga', 32.85, -97.25, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waxahachie', 32.38, -96.84, 'Ellis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weatherford', 32.75, -97.79, 'Parker', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Red Oak', 32.51, -96.8, 'Ellis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Webster', 29.53, -95.11, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gonzales', 29.5, -97.45, 'Gonzales', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weslaco', 26.15, -97.99, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mansfield', 32.56, -97.14, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manvel', 29.46, -95.35, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Canyon', 34.98, -101.91, 'Randall', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marble Falls', 30.57, -98.27, 'Burnet', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richardson', 32.94, -96.72, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Lake Hills', 30.29, -97.8, 'Travis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granbury', 32.44, -97.79, 'Hood', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Orange', 30.08, -93.75, 'Orange', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richland Hills', 32.81, -97.22, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West University Place', 29.71, -95.43, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carrollton', 32.95, -96.89, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westlake', 32.99, -97.19, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carthage', 32.15, -94.33, 'Panola', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshall', 32.54, -94.36, 'Harrison', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Granite Shoals', 30.58, -98.38, 'Burnet', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weston', 33.34, -96.66, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rio Grande City', 26.37, -98.82, 'Starr', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westover Hills', 32.74, -97.41, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Hill', 32.58, -96.95, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grapevine', 32.93, -97.07, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wharton', 29.31, -96.1, 'Wharton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Park', 30.5, -97.82, 'Williamson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenville', 33.13, -96.11, 'Hunt', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('River Oaks', 32.77, -97.39, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Oak', 32.52, -94.86, 'Gregg', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('White Settlement', 32.75, -97.45, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McAllen', 26.2, -98.23, 'Hidalgo', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McKinney', 33.19, -96.61, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wichita Falls', 33.91, -98.49, 'Wichita', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockport', 28.02, -97.05, 'Aransas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Willow Park', 32.76, -97.65, 'Parker', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rockwall', 32.93, -96.45, 'Rockwall', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wimberley', 29.99, -98.09, 'Hays', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Haltom City', 32.79, -97.26, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Windcrest', 29.51, -98.38, 'Bexar', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hamilton', 31.7, -98.12, 'Hamilton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleburne', 32.34, -97.38, 'Johnson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harker Heights', 31.08, -97.65, 'Bell', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mesquite', 32.76, -96.59, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rosenberg', 29.55, -95.8, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harlingen', 26.19, -97.69, 'Cameron', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midland', 31.99, -102.07, 'Midland', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clute', 29.02, -95.39, 'Brazoria', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midlothian', 32.48, -96.99, 'Ellis', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Rock', 30.5, -97.67, 'Williamson', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rowlett', 32.9, -96.56, 'Dallas', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yoakum', 29.28, -97.15, 'Lavaca', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Missouri City', 29.61, -95.53, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abilene', 32.44, -99.73, 'Jones', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Collin', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Niederwald', 30, -97.72, 'Hays', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Katy', 29.78, -95.82, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kemah', 29.54, -95.02, 'Chambers', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Azle', 32.89, -97.54, 'Parker', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearland', 29.56, -95.28, 'Fort Bend', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Trophy Club', 32.99, -97.18, 'Tarrant', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Denton', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Katy', 29.78, -95.82, 'Waller', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearland', 29.56, -95.28, 'Harris', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Kaufman', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Kaufman', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Rockwall', 'TX', 'Texas');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dallas', 32.78, -96.8, 'Rockwall', 'TX', 'Texas');
