INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alpine', 40.45, -111.77, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alta', 40.58, -111.63, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('American Fork', 40.37, -111.79, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaver', 38.27, -112.64, 'Beaver', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bountiful', 40.88, -111.88, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brigham City', 41.51, -112.01, 'Box Elder', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar City', 37.67, -113.06, 'Iron', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedar Hills', 40.41, -111.75, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centerville', 40.91, -111.87, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clearfield', 41.11, -112.02, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 41.13, -112.05, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottonwood Heights', 40.61, -111.81, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delta', 39.35, -112.57, 'Millard', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Draper', 40.52, -111.86, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Enoch', 37.77, -113.02, 'Iron', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmington', 40.98, -111.88, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fruit Heights', 41.03, -111.9, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Garden City', 41.94, -111.39, 'Rich', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gunnison', 39.15, -111.81, 'Sanpete', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Heber City', 40.5, -111.41, 'Wasatch', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Herriman', 40.51, -112.03, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holladay', 40.66, -111.82, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Huntsville', 41.26, -111.76, 'Weber', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hurricane', 37.17, -113.28, 'Washington', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ivins', 37.16, -113.67, 'Washington', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kanab', 37.04, -112.52, 'Kane', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kaysville', 41.03, -111.93, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Layton', 41.06, -111.97, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lindon', 40.34, -111.72, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Logan', 41.73, -111.83, 'Cache', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mapleton', 40.13, -111.57, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mendon', 41.7, -111.97, 'Cache', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Midvale', 40.61, -111.89, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Moab', 38.57, -109.54, 'Grand', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Logan', 41.76, -111.8, 'Cache', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Ogden', 41.3, -111.96, 'Weber', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Salt Lake', 40.84, -111.9, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ogden', 41.22, -111.97, 'Weber', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orem', 40.29, -111.69, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Park City', 40.64, -111.49, 'Summit', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Payson', 40.04, -111.73, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pleasant Grove', 40.36, -111.73, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Price', 39.59, -110.81, 'Carbon', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Provo', 40.23, -111.65, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richfield', 38.77, -112.08, 'Sevier', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverdale', 41.17, -112, 'Weber', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverton', 40.52, -111.93, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roy', 41.16, -112.02, 'Weber', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint George', 37.1, -113.58, 'Washington', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salt Lake City', 40.76, -111.89, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sandy City', 40.59, -111.88, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Santa Clara', 37.13, -113.65, 'Washington', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithfield', 41.83, -111.83, 'Cache', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Jordan', 40.56, -111.92, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Salt Lake', 40.71, -111.88, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spanish Fork', 40.11, -111.65, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Springville', 40.16, -111.61, 'Utah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunset', 41.13, -112.03, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Syracuse', 41.08, -112.06, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Taylorsville', 40.66, -111.93, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tooele', 40.53, -112.29, 'Tooele', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tremonton', 41.71, -112.16, 'Box Elder', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vernal', 40.45, -109.52, 'Uintah', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washington', 37.13, -113.5, 'Washington', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Bountiful', 40.89, -111.9, 'Davis', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Jordan', 40.6, -111.93, 'Salt Lake', 'UT', 'Utah');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woods Cross', 40.87, -111.89, 'Davis', 'UT', 'Utah');
