INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 37.75, -77.47, 'Hanover', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berryville', 39.15, -77.98, 'Clarke', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Big Stone Gap', 36.88, -82.74, 'Wise', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blacksburg', 37.22, -80.41, 'Montgomery', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bowling Green', 38.04, -77.34, 'Caroline', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bridgewater', 38.38, -78.97, 'Rockingham', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bristol', 36.59, -82.18, 'Bristol (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Broadway', 38.61, -78.79, 'Rockingham', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Buena Vista', 37.73, -79.35, 'Buena Vista (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cape Charles', 37.26, -76.01, 'Northampton', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Charlottesville', 38.02, -78.47, 'Charlottesville (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chesapeake', 36.81, -76.27, 'Chesapeake (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chincoteague', 37.93, -75.37, 'Accomack', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Christiansburg', 37.12, -80.4, 'Montgomery', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clifton Forge', 37.81, -79.82, 'Alleghany', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colonial Heights', 37.24, -77.41, 'Colonial Heights (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 37.79, -79.99, 'Covington (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Culpeper', 38.47, -77.99, 'Culpeper', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Damascus', 36.63, -81.78, 'Washington', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Danville', 36.58, -79.39, 'Danville (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 38.41, -78.93, 'Rockingham', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dublin', 37.1, -80.68, 'Pulaski', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Emporia', 36.68, -77.54, 'Emporia (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fairfax', 38.84, -77.3, 'Fairfax (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Falls Church', 38.88, -77.17, 'Falls Church (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Farmville', 37.3, -78.39, 'Prince Edward', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fredericksburg', 38.3, -77.46, 'Fredericksburg (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grottoes', 38.26, -78.82, 'Rockingham', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hampton', 37.02, -76.34, 'Hampton (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Harrisonburg', 38.44, -78.86, 'Harrisonburg (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Herndon', 38.96, -77.38, 'Fairfax', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hopewell', 37.3, -77.28, 'Hopewell (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Crosse', 36.7, -78.09, 'Mecklenburg', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Leesburg', 39.11, -77.56, 'Loudoun', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lexington', 37.78, -79.44, 'Lexington (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Louisa', 38.02, -78, 'Louisa', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Luray', 38.66, -78.45, 'Page', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lynchburg', 37.41, -79.14, 'Lynchburg (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manassas', 38.75, -77.47, 'Manassas (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manassas Park', 38.78, -77.46, 'Manassas Park (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 36.83, -81.51, 'Smyth', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Martinsville', 36.69, -79.87, 'Martinsville (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middleburg', 38.96, -77.73, 'Loudoun', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Jackson', 38.74, -78.64, 'Shenandoah', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Market', 38.64, -78.67, 'Shenandoah', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport News', 36.97, -76.42, 'Newport News (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norfolk', 36.84, -76.28, 'Norfolk (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norton', 36.93, -82.62, 'Norton (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Orange', 38.24, -78.11, 'Orange', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pearisburg', 37.32, -80.73, 'Giles', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Petersburg', 37.22, -77.4, 'Petersburg (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poquoson', 37.12, -76.34, 'Poquoson (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portsmouth', 36.83, -76.29, 'Portsmouth (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pulaski', 37.04, -80.77, 'Pulaski', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Purcellville', 39.13, -77.71, 'Loudoun', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Radford', 37.13, -80.57, 'Radford (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richmond', 37.55, -77.46, 'Richmond (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Roanoke', 37.27, -79.94, 'Roanoke (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rocky Mount', 36.99, -79.89, 'Franklin', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Round Hill', 39.13, -77.76, 'Loudoun', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rural Retreat', 36.89, -81.27, 'Wythe', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Salem', 37.29, -80.05, 'Salem (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottsville', 37.79, -78.49, 'Albemarle', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shenandoah', 38.48, -78.62, 'Page', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Smithfield', 36.98, -76.63, 'Isle of Wight', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Boston', 36.69, -78.9, 'Halifax', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Hill', 36.72, -78.12, 'Mecklenburg', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Staunton', 38.14, -79.07, 'Staunton (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Suffolk', 36.72, -76.58, 'Suffolk (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tazewell', 37.11, -81.51, 'Tazewell', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vienna', 38.9, -77.26, 'Fairfax', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vinton', 37.28, -79.89, 'Roanoke', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Virginia Beach', 36.85, -75.97, 'Virginia Beach (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Warrenton', 38.71, -77.79, 'Fauquier', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waynesboro', 38.06, -78.88, 'Waynesboro (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Point', 37.53, -76.79, 'King William', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winchester', 39.18, -78.16, 'Winchester (city)', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wytheville', 36.94, -81.08, 'Wythe', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abingdon', 36.7, -81.97, 'Washington', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Alexandria', 38.8, -77.04, 'Alexandria', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Norton', 36.93, -82.62, 'Wise', 'VA', 'Virginia');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Scottsville', 37.79, -78.49, 'Fluvanna', 'VA', 'Virginia');
