INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 44.47, -73.21, 'Chittenden', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Essex Junction', 44.49, -73.11, 'Chittenden', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Johnson', 44.63, -72.68, 'Lamoille', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ludlow', 43.39, -72.7, 'Windsor', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manchester', 43.16, -73.07, 'Bennington', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montpelier', 44.26, -72.57, 'Washington', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newfane', 42.98, -72.65, 'Windham', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 44.93, -72.2, 'Orleans', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rutland', 43.61, -72.97, 'Rutland', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Burlington', 44.46, -73.17, 'Chittenden', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Swanton Village', 44.91, -73.12, 'Franklin', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vergennes', 44.16, -73.25, 'Addison', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterbury', 44.33, -72.75, 'Washington', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Barre', 44.19, -72.5, 'Washington', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellows Falls', 43.13, -72.44, 'Windham', 'VT', 'Vermont');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Winooski', 44.49, -73.18, 'Chittenden', 'VT', 'Vermont');
