INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Arlington', 48.19, -122.12, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Washougal', 45.58, -122.35, 'Clark', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Auburn', 47.3, -122.22, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterville', 47.64, -120.07, 'Douglas', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Battle Ground', 45.78, -122.53, 'Clark', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wenatchee', 47.42, -120.31, 'Chelan', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaux Arts Village', 47.58, -122.19, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellevue', 47.61, -122.2, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Westport', 46.89, -124.1, 'Grays Harbor', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bellingham', 48.75, -122.48, 'Whatcom', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Benton City', 46.26, -119.48, 'Benton', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wilbur', 47.75, -118.7, 'Lincoln', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bingen', 45.71, -121.46, 'Klickitat', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blaine', 48.99, -122.74, 'Whatcom', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bonney Lake', 47.17, -122.18, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bothell', 47.76, -122.2, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodinville', 47.75, -122.16, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bremerton', 47.56, -122.63, 'Kitsap', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Woodland', 45.9, -122.74, 'Cowlitz', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brier', 47.78, -122.27, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yakima', 46.6, -120.5, 'Yakima', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Yarrow Point', 47.64, -122.21, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burien', 47.47, -122.34, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 48.47, -122.32, 'Skagit', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Camas', 45.58, -122.39, 'Clark', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Carnation', 47.64, -121.91, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cashmere', 47.52, -120.46, 'Chelan', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Castle Rock', 46.27, -122.9, 'Cowlitz', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Centralia', 46.71, -122.95, 'Lewis', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chelan', 47.84, -120.01, 'Chelan', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheney', 47.48, -117.57, 'Spokane', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clyde Hill', 47.63, -122.21, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Colfax', 46.88, -117.36, 'Whitman', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('College Place', 46.04, -118.38, 'Walla Walla', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Concrete', 48.53, -121.74, 'Skagit', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Connell', 46.66, -118.86, 'Franklin', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Covington', 47.34, -122.11, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Dayton', 46.32, -117.97, 'Columbia', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Des Moines', 47.4, -122.32, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('DuPont', 47.09, -122.63, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Duvall', 47.74, -121.98, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Wenatchee', 47.41, -120.29, 'Douglas', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgewood', 47.25, -122.29, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edmonds', 47.81, -122.37, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellensburg', 46.99, -120.54, 'Kittitas', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Enumclaw', 47.2, -121.99, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ephrata', 47.31, -119.55, 'Grant', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Everett', 47.97, -122.2, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Federal Way', 47.32, -122.31, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ferndale', 48.84, -122.59, 'Whatcom', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fife', 47.23, -122.35, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Forks', 47.95, -124.38, 'Clallam', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Friday Harbor', 48.53, -123.01, 'San Juan', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('George', 47.07, -119.85, 'Grant', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gig Harbor', 47.32, -122.58, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grandview', 46.25, -119.9, 'Yakima', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hoquiam', 46.98, -123.88, 'Grays Harbor', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ilwaco', 46.3, -124.04, 'Pacific', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Issaquah', 47.53, -122.03, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kalama', 46, -122.84, 'Cowlitz', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kelso', 46.14, -122.9, 'Cowlitz', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenmore', 47.75, -122.24, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kennewick', 46.21, -119.13, 'Benton', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kent', 47.38, -122.23, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kirkland', 47.68, -122.2, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Center', 45.86, -122.67, 'Clark', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Conner', 48.38, -122.49, 'Skagit', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lacey', 47.03, -122.82, 'Thurston', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Forest Park', 47.75, -122.28, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Stevens', 48.01, -122.06, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lakewood', 47.17, -122.51, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Longview', 46.13, -122.93, 'Cowlitz', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lynden', 48.94, -122.45, 'Whatcom', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lynnwood', 47.82, -122.31, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Valley', 47.4, -122.03, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marysville', 48.05, -122.17, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medical Lake', 47.57, -117.68, 'Spokane', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Medina', 47.62, -122.22, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mercer Island', 47.57, -122.22, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mill Creek', 47.86, -122.2, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milton', 47.24, -122.31, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 47.85, -121.97, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Montesano', 46.98, -123.6, 'Grays Harbor', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Vernon', 48.42, -122.33, 'Skagit', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mountlake Terrace', 47.78, -122.3, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mukilteo', 47.94, -122.3, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newcastle', 47.53, -122.15, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Newport', 48.17, -117.04, 'Pend Oreille', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Normandy Park', 47.43, -122.34, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Bend', 47.49, -121.78, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Harbor', 48.29, -122.64, 'Island', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ocean Shores', 46.97, -124.15, 'Grays Harbor', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Olympia', 47.03, -122.9, 'Thurston', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pacific', 47.26, -122.25, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pasco', 46.23, -119.1, 'Franklin', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Angeles', 48.11, -123.43, 'Clallam', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Townsend', 48.11, -122.76, 'Jefferson', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Poulsbo', 47.73, -122.64, 'Kitsap', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pullman', 46.73, -117.17, 'Whitman', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Puyallup', 47.18, -122.29, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Redmond', 47.67, -122.12, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Renton', 47.48, -122.21, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Richland', 46.28, -119.28, 'Benton', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sammamish', 47.64, -122.08, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Seattle', 47.6, -122.33, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sedro-Woolley', 48.5, -122.23, 'Skagit', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Selah', 46.65, -120.53, 'Yakima', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sequim', 48.07, -123.1, 'Clallam', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shelton', 47.21, -123.1, 'Mason', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shoreline', 47.75, -122.34, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snohomish', 47.91, -122.09, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Snoqualmie', 47.52, -121.82, 'King', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spokane', 47.65, -117.42, 'Spokane', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spokane Valley', 47.67, -117.23, 'Spokane', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Steilacoom', 47.16, -122.6, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sultan', 47.86, -121.81, 'Snohomish', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sumner', 47.2, -122.24, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sunnyside', 46.32, -120, 'Yakima', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tacoma', 47.25, -122.44, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tonasket', 48.7, -119.43, 'Okanogan', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tumwater', 47, -122.9, 'Thurston', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Union Gap', 46.55, -120.47, 'Yakima', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('University Place', 47.23, -122.55, 'Pierce', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Aberdeen', 46.97, -123.81, 'Grays Harbor', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Vancouver', 45.63, -122.66, 'Clark', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walla Walla', 46.06, -118.34, 'Walla Walla', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Almira', 47.71, -118.94, 'Lincoln', 'WA', 'Washington');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Anacortes', 48.51, -122.61, 'Skagit', 'WA', 'Washington');
