INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hewitt', 44.64, -90.1, 'Wood', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Maple Bluff', 43.11, -89.37, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Edgerton', 42.83, -89.06, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Burlington', 42.67, -88.27, 'Racine', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Allis', 43.01, -88, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Bend', 43.42, -88.18, 'Washington', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shorewood', 43.08, -87.88, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Shorewood Hills', 43.07, -89.44, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hobart', 0, 0, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marinette', 45.09, -87.63, 'Marinette', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marion', 44.67, -88.88, 'Waupaca', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('West Salem', 43.89, -91.08, 'La Crosse', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abbotsford', 44.94, -90.31, 'Clark', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Holmen', 43.96, -91.25, 'La Crosse', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Silver Lake', 42.54, -88.16, 'Kenosha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshall', 43.16, -89.06, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Adams', 43.95, -89.81, 'Adams', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Slinger', 43.33, -88.28, 'Washington', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Marshfield', 44.66, -90.17, 'Wood', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ellsworth', 44.73, -92.48, 'Pierce', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Pewaukee', 43.08, -88.26, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Howard', 44.54, -88.08, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elm Grove', 43.04, -88.07, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Weston', 44.89, -89.54, 'Marathon', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cambria', 43.54, -89.1, 'Columbia', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Elroy', 43.74, -90.27, 'Juneau', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hudson', 44.97, -92.75, 'St. Croix', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Albany', 42.7, -89.43, 'Green', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mayville', 43.49, -88.54, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('South Milwaukee', 42.91, -87.86, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Campbellsport', 43.59, -88.27, 'Fond du Lac', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mazomanie', 43.17, -89.79, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sparta', 43.94, -90.81, 'Monroe', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('McFarland', 43.01, -89.28, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ephraim', 45.15, -87.16, 'Door', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hustisford', 43.34, -88.6, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitefish Bay', 43.11, -87.9, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Algoma', 44.6, -87.43, 'Kewaunee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Platteville', 42.73, -90.47, 'Grant', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spooner', 45.82, -91.88, 'Washburn', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Whitewater', 42.83, -88.73, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Spring Green', 43.17, -90.06, 'Sauk', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evansville', 42.78, -89.29, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plover', 44.45, -89.54, 'Portage', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Williams Bay', 42.57, -88.54, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Altoona', 44.8, -91.44, 'Eau Claire', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Plymouth', 43.74, -87.97, 'Sheboygan', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Menasha', 44.2, -88.44, 'Winnebago', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 43.32, -88.16, 'Washington', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Menomonee Falls', 43.17, -88.11, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cedarburg', 43.29, -87.98, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mequon', 43.23, -87.98, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Janesville', 42.68, -89.01, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Merrill', 45.18, -89.68, 'Lincoln', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Port Washington', 43.38, -87.87, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wind Point', 42.78, -87.76, 'Racine', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Portage', 43.53, -89.46, 'Columbia', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Antigo', 45.14, -89.15, 'Langlade', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chenequa', 43.11, -88.39, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Appleton', 44.26, -88.41, 'Outagamie', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Middleton', 43.09, -89.5, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wisconsin Dells', 43.62, -89.77, 'Columbia', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wisconsin Rapids', 44.38, -89.81, 'Wood', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chilton', 44.02, -88.16, 'Calumet', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fond du Lac', 43.77, -88.44, 'Fond du Lac', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kaukauna', 44.27, -88.27, 'Outagamie', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stevens Point', 44.52, -89.57, 'Portage', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Chippewa Falls', 44.93, -91.39, 'Chippewa', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prairie du Sac', 43.28, -89.72, 'Sauk', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kenosha', 42.58, -87.82, 'Kenosha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Milwaukee', 43.03, -87.9, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Prescott', 44.74, -92.8, 'Pierce', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kewaunee', 44.45, -87.5, 'Kewaunee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Stoughton', 42.91, -89.21, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 46.59, -90.88, 'Ashland', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashwaubenon', 44.48, -88.07, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kimberly', 44.27, -88.33, 'Outagamie', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturgeon Bay', 44.83, -87.37, 'Door', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cleveland', 43.91, -87.74, 'Manitowoc', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fox Point', 43.15, -87.9, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wrightstown', 44.32, -88.16, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sturtevant', 42.69, -87.89, 'Racine', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Suamico', 44.63, -88.03, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Franklin', 42.88, -88.03, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monona', 43.06, -89.33, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Monroe', 42.6, -89.63, 'Green', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Racine', 42.72, -87.78, 'Racine', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Clinton', 42.55, -88.86, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kohler', 43.73, -87.78, 'Sheboygan', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Fredonia', 43.47, -87.95, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('La Crosse', 43.8, -91.23, 'La Crosse', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sun Prairie', 43.18, -89.21, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Superior', 46.72, -92.1, 'Douglas', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sussex', 43.13, -88.22, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Baraboo', 43.47, -89.74, 'Sauk', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mosinee', 44.79, -89.7, 'Marathon', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mount Horeb', 43, -89.73, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Columbus', 43.33, -89.01, 'Columbia', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Geneva', 42.59, -88.43, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rice Lake', 45.5, -91.73, 'Barron', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bay City', 44.58, -92.45, 'Pierce', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lake Mills', 43.08, -88.91, 'Jefferson', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Mukwonago', 42.86, -88.33, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Tigerton', 44.74, -89.06, 'Shawano', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bayside', 43.18, -87.9, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Germantown', 43.22, -88.11, 'Washington', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Muskego', 42.9, -88.13, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cottage Grove', 43.07, -89.19, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gillett', 44.88, -88.3, 'Oconto', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lancaster', 42.84, -90.71, 'Grant', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beaver Dam', 43.45, -88.83, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Neenah', 44.18, -88.46, 'Winnebago', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ripon', 43.84, -88.83, 'Fond du Lac', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cross Plains', 43.11, -89.65, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Glendale', 43.13, -87.93, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('River Falls', 44.86, -92.62, 'Pierce', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cudahy', 42.95, -87.86, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cumberland', 45.53, -92.01, 'Barron', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Beloit', 42.5, -89.03, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Berlin', 42.97, -88.1, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Grafton', 43.31, -87.95, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Glarus', 42.81, -89.63, 'Green', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Two Rivers', 44.15, -87.56, 'Manitowoc', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Berlin', 43.96, -88.94, 'Green Lake', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Lisbon', 43.87, -90.16, 'Juneau', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New Richmond', 45.12, -92.53, 'St. Croix', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rosholt', 44.62, -89.3, 'Portage', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green Bay', 44.51, -88.01, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('De Forest', 43.24, -89.34, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('De Pere', 44.44, -88.06, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greendale', 42.94, -87.99, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Valders', 44.06, -87.88, 'Manitowoc', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Greenfield', 42.96, -88.01, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Deerfield', 43.05, -89.07, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black Earth', 43.13, -89.74, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Fond du Lac', 43.81, -88.48, 'Fond du Lac', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Verona', 42.99, -89.53, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Black River Falls', 44.29, -90.85, 'Jackson', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delafield', 43.06, -88.4, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Hudson', 44.99, -92.75, 'St. Croix', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Delavan', 42.63, -88.64, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('North Prairie', 42.93, -88.4, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Francis', 42.96, -87.87, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oak Creek', 42.88, -87.86, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Bloomer', 45.1, -91.48, 'Chippewa', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Denmark', 44.34, -87.82, 'Brown', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saint Nazianz', 44, -87.92, 'Manitowoc', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wales', 43, -88.37, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lodi', 43.31, -89.52, 'Columbia', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Walworth', 42.53, -88.59, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Blue Mounds', 43.01, -89.83, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lomira', 43.59, -88.44, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oconomowoc', 43.11, -88.49, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sauk City', 43.27, -89.72, 'Sauk', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Boscobel', 43.13, -90.7, 'Grant', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saukville', 43.38, -87.94, 'Ozaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oconto Falls', 44.87, -88.14, 'Oconto', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Onalaska', 43.88, -91.23, 'La Crosse', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartford', 43.31, -88.37, 'Washington', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Luxemburg', 44.53, -87.7, 'Kewaunee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waterloo', 43.18, -88.98, 'Jefferson', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hartland', 43.1, -88.34, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oostburg', 43.62, -87.79, 'Sheboygan', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watertown', 43.19, -88.72, 'Jefferson', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brillion', 44.17, -88.06, 'Calumet', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Durand', 44.62, -91.96, 'Pepin', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oregon', 42.92, -89.38, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eagle', 42.87, -88.47, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brodhead', 42.61, -89.37, 'Green', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waukesha', 43.01, -88.23, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('East Troy', 42.78, -88.4, 'Walworth', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Madison', 43.07, -89.4, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waunakee', 43.19, -89.45, 'Dane', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brookfield', 43.06, -88.1, 'Waukesha', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Hazel Green', 42.53, -90.43, 'Grant', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Oshkosh', 44.02, -88.54, 'Winnebago', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waupaca', 44.35, -89.08, 'Waupaca', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waupun', 43.63, -88.72, 'Fond du Lac', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wausau', 44.95, -89.63, 'Marathon', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sheboygan', 43.75, -87.71, 'Sheboygan', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brown Deer', 43.16, -87.96, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eau Claire', 44.81, -91.49, 'Eau Claire', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Manitowoc', 44.08, -87.65, 'Manitowoc', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wauwatosa', 43.04, -88, 'Milwaukee', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Abbotsford', 44.94, -90.31, 'Marathon', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Appleton', 44.26, -88.41, 'Calumet', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Ashland', 46.59, -90.88, 'Bayfield', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wrightstown', 44.32, -88.16, 'Outagamie', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('New London', 44.39, -88.73, 'Outagamie', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Watertown', 43.19, -88.72, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Brodhead', 42.61, -89.37, 'Rock', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Waupun', 43.63, -88.72, 'Dodge', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Eau Claire', 44.81, -91.49, 'Chippewa', 'WI', 'Wisconsin');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Appleton', 44.26, -88.41, 'Winnebago', 'WI', 'Wisconsin');
