INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Casper', 42.86, -106.31, 'Natrona', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Cheyenne', 41.13, -104.82, 'Laramie', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Douglas', 42.75, -105.38, 'Converse', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Evanston', 41.26, -110.96, 'Uinta', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Gillette', 44.29, -105.5, 'Campbell', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Green River', 41.52, -109.46, 'Sweetwater', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Jackson', 43.47, -110.76, 'Teton', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Kemmerer', 41.79, -110.53, 'Lincoln', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Laramie', 41.31, -105.59, 'Albany', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Lyman', 41.32, -110.29, 'Uinta', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rawlins', 41.79, -107.23, 'Carbon', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Riverton', 43.02, -108.38, 'Fremont', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Rock Springs', 41.58, -109.2, 'Sweetwater', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Saratoga', 41.45, -106.8, 'Carbon', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Sheridan', 44.79, -106.95, 'Sheridan', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Thayne', 42.92, -111, 'Lincoln', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Torrington', 42.06, -104.18, 'Goshen', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Worland', 44.01, -107.95, 'Washakie', 'WY', 'Wyoming');
INSERT INTO citys (name, latitude, longitude, county, state_abbreviation, state) VALUES ('Wright', 43.74, -105.47, 'Campbell', 'WY', 'Wyoming');
