DROP TABLE IF EXISTS groups;
CREATE TABLE groups (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	name VARCHAR(45) NULL ,
	created_at BIGINT NULL ,
	pass_phrase VARCHAR(45) NULL ,
	PRIMARY KEY (id));

DROP TABLE IF EXISTS photos;
CREATE TABLE photos (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	user_id BIGINT NULL ,
	create_at BIGINT NULL ,
	PRIMARY KEY (id));

DROP TABLE IF EXISTS photo_entrys;
CREATE TABLE photo_entrys (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	photo_id BIGINT NULL ,
	group_id BIGINT NULL ,
	user_id BIGINT NULL ,
	create_at BIGINT NULL ,
	acknowledged TINYINT NULL ,
	PRIMARY KEY (id));

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	name VARCHAR(45) NULL ,
	joint_at BIGINT NULL ,
	api_key VARCHAR(45) NULL ,
	device_type VARCHAR(200) NULL ,
	udid VARCHAR(200) NULL ,
	PRIMARY KEY (id));

DROP TABLE IF EXISTS group_members;
CREATE TABLE group_members (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	group_id BIGINT NULL ,
	user_id BIGINT NULL ,
	join_at BIGINT NULL ,
	PRIMARY KEY (id));